s/[[:<:]]Dance Troupe[[:>:]]/Dance_Troupe/g;
s/[[:<:]]Maha Bandula[[:>:]]/Maha_Bandula/g;
s/[[:<:]]drawings are[[:>:]]/drawings_are/g;
s/[[:<:]]Orphan Asylum[[:>:]]/Orphan_Asylum/g;
s/[[:<:]]named “[[:>:]]/named_“/g;
s/[[:<:]]moderate success[[:>:]]/moderate_success/g;
s/[[:<:]]featured artist[[:>:]]/featured_artist/g;
s/[[:<:]]In 1848[[:>:]]/In_1848/g;
s/[[:<:]]residential districts[[:>:]]/residential_districts/g;
s/[[:<:]]Rupert Penry-Jones[[:>:]]/Rupert_Penry-Jones/g;
s/[[:<:]]but they divorced[[:>:]]/but_they_divorced/g;
s/[[:<:]]Al Shabaab[[:>:]]/Al_Shabaab/g;
s/[[:<:]]cubic lattice[[:>:]]/cubic_lattice/g;
s/[[:<:]]Hal Blaine[[:>:]]/Hal_Blaine/g;
s/[[:<:]]A champion seed[[:>:]]/A_champion_seed/g;
s/[[:<:]]Suddenly Last[[:>:]]/Suddenly_Last/g;
s/[[:<:]]Kwai Fong[[:>:]]/Kwai_Fong/g;
s/[[:<:]]public defenders[[:>:]]/public_defenders/g;
s/[[:<:]]TP Mazembe[[:>:]]/TP_Mazembe/g;
s/[[:<:]]Milorad Dodik[[:>:]]/Milorad_Dodik/g;
s/[[:<:]]Henry John[[:>:]]/Henry_John/g;
s/[[:<:]]Harry Saltzman[[:>:]]/Harry_Saltzman/g;
s/[[:<:]]Fall 2014[[:>:]]/Fall_2014/g;
s/[[:<:]]record and perform[[:>:]]/record_and_perform/g;
s/[[:<:]]steam engines[[:>:]]/steam_engines/g;
s/[[:<:]]rushing for[[:>:]]/rushing_for/g;
s/[[:<:]]Bayburt Bayburt[[:>:]]/Bayburt_Bayburt/g;
s/[[:<:]]car accident[[:>:]]/car_accident/g;
s/[[:<:]]promised them[[:>:]]/promised_them/g;
s/[[:<:]]many fields[[:>:]]/many_fields/g;
s/[[:<:]]Tech Prep[[:>:]]/Tech_Prep/g;
s/[[:<:]]Sub-Aqua Club[[:>:]]/Sub-Aqua_Club/g;
s/[[:<:]]The incident[[:>:]]/The_incident/g;
s/[[:<:]]Sucker Punch[[:>:]]/Sucker_Punch/g;
s/[[:<:]]Act amended[[:>:]]/Act_amended/g;
s/[[:<:]]Verein zur[[:>:]]/Verein_zur/g;
s/[[:<:]]professor emeritus[[:>:]]/professor_emeritus/g;
s/[[:<:]]Stacia Proefrock[[:>:]]/Stacia_Proefrock/g;
s/[[:<:]]son Arthur[[:>:]]/son_Arthur/g;
s/[[:<:]]file contains[[:>:]]/file_contains/g;
s/[[:<:]]$225 000[[:>:]]/$225_000/g;
s/[[:<:]]Thales Alenia[[:>:]]/Thales_Alenia/g;
s/[[:<:]]in Kosovo[[:>:]]/in_Kosovo/g;
s/[[:<:]]subjecting them[[:>:]]/subjecting_them/g;
s/[[:<:]]tin mines[[:>:]]/tin_mines/g;
s/[[:<:]]side-by-side rowing[[:>:]]/side-by-side_rowing/g;
s/[[:<:]]Doug Wright[[:>:]]/Doug_Wright/g;
s/[[:<:]]widows and widowers[[:>:]]/widows_and_widowers/g;
s/[[:<:]]troubled times[[:>:]]/troubled_times/g;
s/[[:<:]]Employers Confederation[[:>:]]/Employers_Confederation/g;
s/[[:<:]]Suresh Wadkar[[:>:]]/Suresh_Wadkar/g;
s/[[:<:]]Salinas Valley[[:>:]]/Salinas_Valley/g;
s/[[:<:]]Atlantic seaboard[[:>:]]/Atlantic_seaboard/g;
s/[[:<:]]car salesman[[:>:]]/car_salesman/g;
s/[[:<:]]indentured servants[[:>:]]/indentured_servants/g;
s/[[:<:]]seven-game series[[:>:]]/seven-game_series/g;
s/[[:<:]]warms up[[:>:]]/warms_up/g;
s/[[:<:]]Judy Greer[[:>:]]/Judy_Greer/g;
s/[[:<:]]Nachke Dikha[[:>:]]/Nachke_Dikha/g;
s/[[:<:]]ε 0[[:>:]]/ε_0/g;
s/[[:<:]]Lisson Gallery[[:>:]]/Lisson_Gallery/g;
s/[[:<:]]Grupo Televisa[[:>:]]/Grupo_Televisa/g;
s/[[:<:]]de Mendoza[[:>:]]/de_Mendoza/g;
s/[[:<:]]the temple[[:>:]]/the_temple/g;
s/[[:<:]]Queen Rania[[:>:]]/Queen_Rania/g;
s/[[:<:]]Australasian Championships[[:>:]]/Australasian_Championships/g;
s/[[:<:]]the Qin Dynasty[[:>:]]/the_Qin_Dynasty/g;
s/[[:<:]]political upheavals[[:>:]]/political_upheavals/g;
s/[[:<:]]40-man roster[[:>:]]/40-man_roster/g;
s/[[:<:]]Unfunded Mandates[[:>:]]/Unfunded_Mandates/g;
s/[[:<:]]his main interest[[:>:]]/his_main_interest/g;
s/[[:<:]]Islamic sciences[[:>:]]/Islamic_sciences/g;
s/[[:<:]]Duke Ellington[[:>:]]/Duke_Ellington/g;
s/[[:<:]]miscarriage of justice[[:>:]]/miscarriage_of_justice/g;
s/[[:<:]]Biblioteca Marciana[[:>:]]/Biblioteca_Marciana/g;
s/[[:<:]]Kjell Magne Bondevik[[:>:]]/Kjell_Magne_Bondevik/g;
s/[[:<:]]AFL Draft[[:>:]]/AFL_Draft/g;
s/[[:<:]]sent representatives to[[:>:]]/sent_representatives_to/g;
s/[[:<:]]Van Nistelrooy[[:>:]]/Van_Nistelrooy/g;
s/[[:<:]]was leaked[[:>:]]/was_leaked/g;
s/[[:<:]]the 27th[[:>:]]/the_27th/g;
s/[[:<:]]and runs into[[:>:]]/and_runs_into/g;
s/[[:<:]]Propionibacterium acnes[[:>:]]/Propionibacterium_acnes/g;
s/[[:<:]]Helikopter Service[[:>:]]/Helikopter_Service/g;
s/[[:<:]]a blockade[[:>:]]/a_blockade/g;
s/[[:<:]]Download Festival[[:>:]]/Download_Festival/g;
s/[[:<:]]cure for[[:>:]]/cure_for/g;
s/[[:<:]]attract tourists[[:>:]]/attract_tourists/g;
s/[[:<:]]shade tree[[:>:]]/shade_tree/g;
s/[[:<:]]consists largely of[[:>:]]/consists_largely_of/g;
s/[[:<:]]Def Leppard[[:>:]]/Def_Leppard/g;
s/[[:<:]]simulation video game[[:>:]]/simulation_video_game/g;
s/[[:<:]]Lokomotiv Plovdiv[[:>:]]/Lokomotiv_Plovdiv/g;
s/[[:<:]]Kent Hrbek[[:>:]]/Kent_Hrbek/g;
s/[[:<:]]She transited[[:>:]]/She_transited/g;
s/[[:<:]]Poison the Well[[:>:]]/Poison_the_Well/g;
s/[[:<:]]requests from[[:>:]]/requests_from/g;
s/[[:<:]]Seattle Metropolitans[[:>:]]/Seattle_Metropolitans/g;
s/[[:<:]]Shortly thereafter[[:>:]]/Shortly_thereafter/g;
s/[[:<:]]Miami-Fort Lauderdale[[:>:]]/Miami-Fort_Lauderdale/g;
s/[[:<:]]Make You Mine[[:>:]]/Make_You_Mine/g;
s/[[:<:]]mountain rescue[[:>:]]/mountain_rescue/g;
s/[[:<:]]$9 billion[[:>:]]/$9_billion/g;
s/[[:<:]]Topics covered include[[:>:]]/Topics_covered_include/g;
s/[[:<:]]Cindy Sheehan[[:>:]]/Cindy_Sheehan/g;
s/[[:<:]]descending from[[:>:]]/descending_from/g;
s/[[:<:]]was re-created[[:>:]]/was_re-created/g;
s/[[:<:]]do Amaral[[:>:]]/do_Amaral/g;
s/[[:<:]]Franz Nopcsa[[:>:]]/Franz_Nopcsa/g;
s/[[:<:]]Music Inc[[:>:]]/Music_Inc/g;
s/[[:<:]]El Texano[[:>:]]/El_Texano/g;
s/[[:<:]]Missouri Senate[[:>:]]/Missouri_Senate/g;
s/[[:<:]]constitutional right[[:>:]]/constitutional_right/g;
s/[[:<:]]in 1817[[:>:]]/in_1817/g;
s/[[:<:]]collided with[[:>:]]/collided_with/g;
s/[[:<:]]Persian خرم[[:>:]]/Persian_خرم/g;
s/[[:<:]]Richard Seddon[[:>:]]/Richard_Seddon/g;
s/[[:<:]]her last[[:>:]]/her_last/g;
s/[[:<:]]Tessa Jowell[[:>:]]/Tessa_Jowell/g;
s/[[:<:]]his request[[:>:]]/his_request/g;
s/[[:<:]]a novelist[[:>:]]/a_novelist/g;
s/[[:<:]]coastal cliffs[[:>:]]/coastal_cliffs/g;
s/[[:<:]]Good Practice[[:>:]]/Good_Practice/g;
s/[[:<:]]adoptive mother[[:>:]]/adoptive_mother/g;
s/[[:<:]]classified under[[:>:]]/classified_under/g;
s/[[:<:]]In Praise of[[:>:]]/In_Praise_of/g;
s/[[:<:]]Kopparbergs Göteborg[[:>:]]/Kopparbergs_Göteborg/g;
s/[[:<:]]Miikka Kiprusoff[[:>:]]/Miikka_Kiprusoff/g;
s/[[:<:]]Delle Donne[[:>:]]/Delle_Donne/g;
s/[[:<:]]Sheikh Mohammed[[:>:]]/Sheikh_Mohammed/g;
s/[[:<:]]Allied governments[[:>:]]/Allied_governments/g;
s/[[:<:]]Bade Ghulam[[:>:]]/Bade_Ghulam/g;
s/[[:<:]]René Auberjonois[[:>:]]/René_Auberjonois/g;
s/[[:<:]]equivalent to[[:>:]]/equivalent_to/g;
s/[[:<:]]Linux OS[[:>:]]/Linux_OS/g;
s/[[:<:]]heroes and villains[[:>:]]/heroes_and_villains/g;
s/[[:<:]]elementary school[[:>:]]/elementary_school/g;
s/[[:<:]]Contracting Parties[[:>:]]/Contracting_Parties/g;
s/[[:<:]]at Pride Park[[:>:]]/at_Pride_Park/g;
s/[[:<:]]IND Concourse[[:>:]]/IND_Concourse/g;
s/[[:<:]]meditation on[[:>:]]/meditation_on/g;
s/[[:<:]]their concerts[[:>:]]/their_concerts/g;
s/[[:<:]]Urban Districts[[:>:]]/Urban_Districts/g;
s/[[:<:]]in shaping[[:>:]]/in_shaping/g;
s/[[:<:]]Gmina Goleniów within[[:>:]]/Gmina_Goleniów_within/g;
s/[[:<:]]a confession[[:>:]]/a_confession/g;
s/[[:<:]]reed organ[[:>:]]/reed_organ/g;
s/[[:<:]]Institute for[[:>:]]/Institute_for/g;
s/[[:<:]]shopping malls[[:>:]]/shopping_malls/g;
s/[[:<:]]political crises[[:>:]]/political_crises/g;
s/[[:<:]]Annual Conferences[[:>:]]/Annual_Conferences/g;
s/[[:<:]]PET bottles[[:>:]]/PET_bottles/g;
s/[[:<:]]Philip Rivers[[:>:]]/Philip_Rivers/g;
s/[[:<:]]Baptist church[[:>:]]/Baptist_church/g;
s/[[:<:]]told by[[:>:]]/told_by/g;
s/[[:<:]]hopes to[[:>:]]/hopes_to/g;
s/[[:<:]]destined to[[:>:]]/destined_to/g;
s/[[:<:]]South African international[[:>:]]/South_African_international/g;
s/[[:<:]]Kevin Sumlin[[:>:]]/Kevin_Sumlin/g;
s/[[:<:]]Harold Laski[[:>:]]/Harold_Laski/g;
s/[[:<:]]tells about[[:>:]]/tells_about/g;
s/[[:<:]]Joan Fontaine[[:>:]]/Joan_Fontaine/g;
s/[[:<:]]provided through[[:>:]]/provided_through/g;
s/[[:<:]]Sakha Republic[[:>:]]/Sakha_Republic/g;
s/[[:<:]]Bedtime Stories[[:>:]]/Bedtime_Stories/g;
s/[[:<:]]Act II[[:>:]]/Act_II/g;
s/[[:<:]]Le Jeune[[:>:]]/Le_Jeune/g;
s/[[:<:]]casting doubt[[:>:]]/casting_doubt/g;
s/[[:<:]]high frequencies[[:>:]]/high_frequencies/g;
s/[[:<:]]aided and abetted[[:>:]]/aided_and_abetted/g;
s/[[:<:]]Northern Ostrobothnia[[:>:]]/Northern_Ostrobothnia/g;
s/[[:<:]]forced marriages[[:>:]]/forced_marriages/g;
s/[[:<:]]wants to[[:>:]]/wants_to/g;
s/[[:<:]]at Bellator[[:>:]]/at_Bellator/g;
s/[[:<:]]sports anchor[[:>:]]/sports_anchor/g;
s/[[:<:]]The 2013 season[[:>:]]/The_2013_season/g;
s/[[:<:]]Super Bowls[[:>:]]/Super_Bowls/g;
s/[[:<:]]Neotropical ecozone[[:>:]]/Neotropical_ecozone/g;
s/[[:<:]]Hsieh Su-wei[[:>:]]/Hsieh_Su-wei/g;
s/[[:<:]]was really[[:>:]]/was_really/g;
s/[[:<:]]religious ceremonies[[:>:]]/religious_ceremonies/g;
s/[[:<:]]Operational squadrons[[:>:]]/Operational_squadrons/g;
s/[[:<:]]Ashford Simpson[[:>:]]/Ashford_Simpson/g;
s/[[:<:]]Tazeh Kand-e[[:>:]]/Tazeh_Kand-e/g;
s/[[:<:]]National Flag[[:>:]]/National_Flag/g;
s/[[:<:]]anti-money laundering[[:>:]]/anti-money_laundering/g;
s/[[:<:]]Roker Park[[:>:]]/Roker_Park/g;
s/[[:<:]]Tony Gonzalez[[:>:]]/Tony_Gonzalez/g;
s/[[:<:]]landfalls extratropical transitions[[:>:]]/landfalls_extratropical_transitions/g;
s/[[:<:]]Manchester Cathedral[[:>:]]/Manchester_Cathedral/g;
s/[[:<:]]Karst topography[[:>:]]/Karst_topography/g;
s/[[:<:]]an uneventful[[:>:]]/an_uneventful/g;
s/[[:<:]]clothing designer[[:>:]]/clothing_designer/g;
s/[[:<:]]Bob Clampett[[:>:]]/Bob_Clampett/g;
s/[[:<:]]Lori McNeil[[:>:]]/Lori_McNeil/g;
s/[[:<:]]rural school districts[[:>:]]/rural_school_districts/g;
s/[[:<:]]Shanghai Beijing[[:>:]]/Shanghai_Beijing/g;
s/[[:<:]]Proto-Indo-European PIE[[:>:]]/Proto-Indo-European_PIE/g;
s/[[:<:]]Kūkō IATA[[:>:]]/Kūkō_IATA/g;
s/[[:<:]]in order that[[:>:]]/in_order_that/g;
s/[[:<:]]lower elevation[[:>:]]/lower_elevation/g;
s/[[:<:]]his fellows[[:>:]]/his_fellows/g;
s/[[:<:]]Gurbanguly Berdimuhamedov[[:>:]]/Gurbanguly_Berdimuhamedov/g;
s/[[:<:]]an entire[[:>:]]/an_entire/g;
s/[[:<:]]electrical outlet[[:>:]]/electrical_outlet/g;
s/[[:<:]]an Associate[[:>:]]/an_Associate/g;
s/[[:<:]]Growling Tigers[[:>:]]/Growling_Tigers/g;
s/[[:<:]]artillery batteries[[:>:]]/artillery_batteries/g;
s/[[:<:]]Fort Gordon[[:>:]]/Fort_Gordon/g;
s/[[:<:]]Serban Ghenea[[:>:]]/Serban_Ghenea/g;
s/[[:<:]]the field he[[:>:]]/the_field_he/g;
s/[[:<:]]Gary Russell[[:>:]]/Gary_Russell/g;
s/[[:<:]]Interview magazine[[:>:]]/Interview_magazine/g;
s/[[:<:]]Our Last[[:>:]]/Our_Last/g;
s/[[:<:]]has been capped[[:>:]]/has_been_capped/g;
s/[[:<:]]Jezreel Valley[[:>:]]/Jezreel_Valley/g;
s/[[:<:]]and enlarged[[:>:]]/and_enlarged/g;
s/[[:<:]]human emotions[[:>:]]/human_emotions/g;
s/[[:<:]]the Regent s[[:>:]]/the_Regent_s/g;
s/[[:<:]]Joint Distribution[[:>:]]/Joint_Distribution/g;
s/[[:<:]]compete together[[:>:]]/compete_together/g;
s/[[:<:]]panned by critics[[:>:]]/panned_by_critics/g;
s/[[:<:]]Several scholars[[:>:]]/Several_scholars/g;
s/[[:<:]]Red Line[[:>:]]/Red_Line/g;
s/[[:<:]]Deportivo Español[[:>:]]/Deportivo_Español/g;
s/[[:<:]]million items[[:>:]]/million_items/g;
s/[[:<:]]mentally incompetent[[:>:]]/mentally_incompetent/g;
s/[[:<:]]funded by[[:>:]]/funded_by/g;
s/[[:<:]]executive bureau[[:>:]]/executive_bureau/g;
s/[[:<:]]has rarely been[[:>:]]/has_rarely_been/g;
s/[[:<:]]El Roumi[[:>:]]/El_Roumi/g;
s/[[:<:]]delimited by[[:>:]]/delimited_by/g;
s/[[:<:]]Ichikawa Danjūrō[[:>:]]/Ichikawa_Danjūrō/g;
s/[[:<:]]Neuberger Berman[[:>:]]/Neuberger_Berman/g;
s/[[:<:]]irreparably damaged[[:>:]]/irreparably_damaged/g;
s/[[:<:]]product liability[[:>:]]/product_liability/g;
s/[[:<:]]all life on[[:>:]]/all_life_on/g;
s/[[:<:]]Dehaj District[[:>:]]/Dehaj_District/g;
s/[[:<:]]ensued with[[:>:]]/ensued_with/g;
s/[[:<:]]Amr Diab[[:>:]]/Amr_Diab/g;
s/[[:<:]]Technical Staff[[:>:]]/Technical_Staff/g;
s/[[:<:]]during the brief[[:>:]]/during_the_brief/g;
s/[[:<:]]Houbraken he[[:>:]]/Houbraken_he/g;
s/[[:<:]]National Stud[[:>:]]/National_Stud/g;
s/[[:<:]]Political Cesspool[[:>:]]/Political_Cesspool/g;
s/[[:<:]]Sealab 2021[[:>:]]/Sealab_2021/g;
s/[[:<:]]Visiting Fellow[[:>:]]/Visiting_Fellow/g;
s/[[:<:]]high energy[[:>:]]/high_energy/g;
s/[[:<:]]Cyril Washbrook[[:>:]]/Cyril_Washbrook/g;
s/[[:<:]]Utagawa Kunisada[[:>:]]/Utagawa_Kunisada/g;
s/[[:<:]]Interbank Offered[[:>:]]/Interbank_Offered/g;
s/[[:<:]]her grave[[:>:]]/her_grave/g;
s/[[:<:]]in 1831[[:>:]]/in_1831/g;
s/[[:<:]]Boswell s[[:>:]]/Boswell_s/g;
s/[[:<:]]handheld devices[[:>:]]/handheld_devices/g;
s/[[:<:]]in the leg[[:>:]]/in_the_leg/g;
s/[[:<:]]Biblical Seminary[[:>:]]/Biblical_Seminary/g;
s/[[:<:]]ALGOL 68[[:>:]]/ALGOL_68/g;
s/[[:<:]]do not[[:>:]]/do_not/g;
s/[[:<:]]Sông Lam Nghệ[[:>:]]/Sông_Lam_Nghệ/g;
s/[[:<:]]Atlanta July 22-August[[:>:]]/Atlanta_July_22-August/g;
s/[[:<:]]س ُ[[:>:]]/س_ُ/g;
s/[[:<:]]10 a m[[:>:]]/10_a_m/g;
s/[[:<:]]Jermaine Dupri[[:>:]]/Jermaine_Dupri/g;
s/[[:<:]]British protectorate[[:>:]]/British_protectorate/g;
s/[[:<:]]59 8[[:>:]]/59_8/g;
s/[[:<:]]FC Groningen[[:>:]]/FC_Groningen/g;
s/[[:<:]]much effort[[:>:]]/much_effort/g;
s/[[:<:]]BBC 6[[:>:]]/BBC_6/g;
s/[[:<:]]every 4 years[[:>:]]/every_4_years/g;
s/[[:<:]]slumber party[[:>:]]/slumber_party/g;
s/[[:<:]]presumed lost[[:>:]]/presumed_lost/g;
s/[[:<:]]Nguyen Ngoc[[:>:]]/Nguyen_Ngoc/g;
s/[[:<:]]would employ[[:>:]]/would_employ/g;
s/[[:<:]]Campeonato Brasileiro[[:>:]]/Campeonato_Brasileiro/g;
s/[[:<:]]OverClocked ReMix[[:>:]]/OverClocked_ReMix/g;
s/[[:<:]]coping skills[[:>:]]/coping_skills/g;
s/[[:<:]]Lubbock Texas[[:>:]]/Lubbock_Texas/g;
s/[[:<:]]Blind Guardian[[:>:]]/Blind_Guardian/g;
s/[[:<:]]withdrawn from[[:>:]]/withdrawn_from/g;
s/[[:<:]]divided four-lane[[:>:]]/divided_four-lane/g;
s/[[:<:]]resting place[[:>:]]/resting_place/g;
s/[[:<:]]million in sales[[:>:]]/million_in_sales/g;
s/[[:<:]]Thankful Villages[[:>:]]/Thankful_Villages/g;
s/[[:<:]]Neon Trees[[:>:]]/Neon_Trees/g;
s/[[:<:]]Arrive Alive[[:>:]]/Arrive_Alive/g;
s/[[:<:]]resolves to[[:>:]]/resolves_to/g;
s/[[:<:]]Pran Nath[[:>:]]/Pran_Nath/g;
s/[[:<:]]copper oxide[[:>:]]/copper_oxide/g;
s/[[:<:]]testify that[[:>:]]/testify_that/g;
s/[[:<:]]the Baskervilles[[:>:]]/the_Baskervilles/g;
s/[[:<:]]Averell Harriman[[:>:]]/Averell_Harriman/g;
s/[[:<:]]metal frame[[:>:]]/metal_frame/g;
s/[[:<:]]Országos Bajnokság[[:>:]]/Országos_Bajnokság/g;
s/[[:<:]]Monday November[[:>:]]/Monday_November/g;
s/[[:<:]]the Ohio Senate[[:>:]]/the_Ohio_Senate/g;
s/[[:<:]]Curling Association[[:>:]]/Curling_Association/g;
s/[[:<:]]is not visible[[:>:]]/is_not_visible/g;
s/[[:<:]]Mister Terrific[[:>:]]/Mister_Terrific/g;
s/[[:<:]]evacuation of[[:>:]]/evacuation_of/g;
s/[[:<:]]Nagorno-Karabakh Republic[[:>:]]/Nagorno-Karabakh_Republic/g;
s/[[:<:]]the oceans[[:>:]]/the_oceans/g;
s/[[:<:]]strengthened into[[:>:]]/strengthened_into/g;
s/[[:<:]]riders from[[:>:]]/riders_from/g;
s/[[:<:]]Javier Saviola[[:>:]]/Javier_Saviola/g;
s/[[:<:]]Indianapolis Raceway Park[[:>:]]/Indianapolis_Raceway_Park/g;
s/[[:<:]]Field Hospital[[:>:]]/Field_Hospital/g;
s/[[:<:]]was $34[[:>:]]/was_$34/g;
s/[[:<:]]lit year name[[:>:]]/lit_year_name/g;
s/[[:<:]]da Vida[[:>:]]/da_Vida/g;
s/[[:<:]]aged 14[[:>:]]/aged_14/g;
s/[[:<:]]likeness of[[:>:]]/likeness_of/g;
s/[[:<:]]relative frequency[[:>:]]/relative_frequency/g;
s/[[:<:]]aerial warfare[[:>:]]/aerial_warfare/g;
s/[[:<:]]ISO 3166[[:>:]]/ISO_3166/g;
s/[[:<:]]their destination[[:>:]]/their_destination/g;
s/[[:<:]]a thirty-year[[:>:]]/a_thirty-year/g;
s/[[:<:]]is famous as[[:>:]]/is_famous_as/g;
s/[[:<:]]Milwaukee Braves[[:>:]]/Milwaukee_Braves/g;
s/[[:<:]]Jean-Baptiste Mondino[[:>:]]/Jean-Baptiste_Mondino/g;
s/[[:<:]]– 1979[[:>:]]/–_1979/g;
s/[[:<:]]first published on[[:>:]]/first_published_on/g;
s/[[:<:]]Sola Scriptura[[:>:]]/Sola_Scriptura/g;
s/[[:<:]]Treat Me[[:>:]]/Treat_Me/g;
s/[[:<:]]40-yard dash[[:>:]]/40-yard_dash/g;
s/[[:<:]]Société Anonyme[[:>:]]/Société_Anonyme/g;
s/[[:<:]]Fantasy Science Fiction[[:>:]]/Fantasy_Science_Fiction/g;
s/[[:<:]]Fencing Federation[[:>:]]/Fencing_Federation/g;
s/[[:<:]]piano organ[[:>:]]/piano_organ/g;
s/[[:<:]]expressed their concern[[:>:]]/expressed_their_concern/g;
s/[[:<:]]was played against[[:>:]]/was_played_against/g;
s/[[:<:]]market index[[:>:]]/market_index/g;
s/[[:<:]]White Cliffs[[:>:]]/White_Cliffs/g;
s/[[:<:]]Upland School District[[:>:]]/Upland_School_District/g;
s/[[:<:]]State Senator[[:>:]]/State_Senator/g;
s/[[:<:]]Benigno Aquino[[:>:]]/Benigno_Aquino/g;
s/[[:<:]]110 meter hurdles[[:>:]]/110_meter_hurdles/g;
s/[[:<:]]genetic loci[[:>:]]/genetic_loci/g;
s/[[:<:]]Stanley William Hayter[[:>:]]/Stanley_William_Hayter/g;
s/[[:<:]]farther than[[:>:]]/farther_than/g;
s/[[:<:]]the team from[[:>:]]/the_team_from/g;
s/[[:<:]]AFL Premiership[[:>:]]/AFL_Premiership/g;
s/[[:<:]]girl friend[[:>:]]/girl_friend/g;
s/[[:<:]]Skate Park[[:>:]]/Skate_Park/g;
s/[[:<:]]devoted most of[[:>:]]/devoted_most_of/g;
s/[[:<:]]is a 1971[[:>:]]/is_a_1971/g;
s/[[:<:]]Abd al-Qādir[[:>:]]/Abd_al-Qādir/g;
s/[[:<:]]miraculous healing[[:>:]]/miraculous_healing/g;
s/[[:<:]]Rhineland-Palatinate Germany[[:>:]]/Rhineland-Palatinate_Germany/g;
s/[[:<:]]opéras comiques[[:>:]]/opéras_comiques/g;
s/[[:<:]]Gonçalves Zarco[[:>:]]/Gonçalves_Zarco/g;
s/[[:<:]]neutron stars[[:>:]]/neutron_stars/g;
s/[[:<:]]at sunrise[[:>:]]/at_sunrise/g;
s/[[:<:]]bonded to[[:>:]]/bonded_to/g;
s/[[:<:]]in 1507[[:>:]]/in_1507/g;
s/[[:<:]]is gone[[:>:]]/is_gone/g;
s/[[:<:]]tectonic activity[[:>:]]/tectonic_activity/g;
s/[[:<:]]the harbour[[:>:]]/the_harbour/g;
s/[[:<:]]highly automated[[:>:]]/highly_automated/g;
s/[[:<:]]a briefing[[:>:]]/a_briefing/g;
s/[[:<:]]् वत[[:>:]]/्_वत/g;
s/[[:<:]]basketball game[[:>:]]/basketball_game/g;
s/[[:<:]]Fourier transform[[:>:]]/Fourier_transform/g;
s/[[:<:]]statistical compilation by[[:>:]]/statistical_compilation_by/g;
s/[[:<:]]thousand rupees[[:>:]]/thousand_rupees/g;
s/[[:<:]]Progressive Party[[:>:]]/Progressive_Party/g;
s/[[:<:]]living conditions[[:>:]]/living_conditions/g;
s/[[:<:]]tort liability[[:>:]]/tort_liability/g;
s/[[:<:]]in the south-west[[:>:]]/in_the_south-west/g;
s/[[:<:]]younger siblings[[:>:]]/younger_siblings/g;
s/[[:<:]]British consul[[:>:]]/British_consul/g;
s/[[:<:]]Southern Conference[[:>:]]/Southern_Conference/g;
s/[[:<:]]surrounding waters[[:>:]]/surrounding_waters/g;
s/[[:<:]]The insignia[[:>:]]/The_insignia/g;
s/[[:<:]]a Democrat[[:>:]]/a_Democrat/g;
s/[[:<:]]The US Army[[:>:]]/The_US_Army/g;
s/[[:<:]]Jack McDuff[[:>:]]/Jack_McDuff/g;
s/[[:<:]]Orange Revolution[[:>:]]/Orange_Revolution/g;
s/[[:<:]]is murdered by[[:>:]]/is_murdered_by/g;
s/[[:<:]]metal halides[[:>:]]/metal_halides/g;
s/[[:<:]]State Guard[[:>:]]/State_Guard/g;
s/[[:<:]]Highly Qualified[[:>:]]/Highly_Qualified/g;
s/[[:<:]]health resort[[:>:]]/health_resort/g;
s/[[:<:]]Identity Cards[[:>:]]/Identity_Cards/g;
s/[[:<:]]consider to be[[:>:]]/consider_to_be/g;
s/[[:<:]]wikitable succession-box[[:>:]]/wikitable_succession-box/g;
s/[[:<:]]Keeper of[[:>:]]/Keeper_of/g;
s/[[:<:]]unstressed syllables[[:>:]]/unstressed_syllables/g;
s/[[:<:]]Articles of Confederation[[:>:]]/Articles_of_Confederation/g;
s/[[:<:]]in a season[[:>:]]/in_a_season/g;
s/[[:<:]]way of doing[[:>:]]/way_of_doing/g;
s/[[:<:]]endeared himself to[[:>:]]/endeared_himself_to/g;
s/[[:<:]]West Kirby[[:>:]]/West_Kirby/g;
s/[[:<:]]Redondo Beach[[:>:]]/Redondo_Beach/g;
s/[[:<:]]turned over[[:>:]]/turned_over/g;
s/[[:<:]]torrential downpour[[:>:]]/torrential_downpour/g;
s/[[:<:]]Rillington Place[[:>:]]/Rillington_Place/g;
s/[[:<:]]Zaporizhian Host[[:>:]]/Zaporizhian_Host/g;
s/[[:<:]]Between 1994[[:>:]]/Between_1994/g;
s/[[:<:]]provoked by[[:>:]]/provoked_by/g;
s/[[:<:]]Hitman Reborn[[:>:]]/Hitman_Reborn/g;
s/[[:<:]]his arm[[:>:]]/his_arm/g;
s/[[:<:]]escaped capture[[:>:]]/escaped_capture/g;
s/[[:<:]]Shari ah[[:>:]]/Shari_ah/g;
s/[[:<:]]rectus femoris[[:>:]]/rectus_femoris/g;
s/[[:<:]]assurance that[[:>:]]/assurance_that/g;
s/[[:<:]]Blur s[[:>:]]/Blur_s/g;
s/[[:<:]]before heading[[:>:]]/before_heading/g;
s/[[:<:]]Russian SFSR[[:>:]]/Russian_SFSR/g;
s/[[:<:]]M40 motorway[[:>:]]/M40_motorway/g;
s/[[:<:]]By 1956[[:>:]]/By_1956/g;
s/[[:<:]]Soviet intelligence[[:>:]]/Soviet_intelligence/g;
s/[[:<:]]Butterfield Overland[[:>:]]/Butterfield_Overland/g;
s/[[:<:]]Weather Forecast[[:>:]]/Weather_Forecast/g;
s/[[:<:]]Best Books[[:>:]]/Best_Books/g;
s/[[:<:]]Film critic[[:>:]]/Film_critic/g;
s/[[:<:]]at sea with[[:>:]]/at_sea_with/g;
s/[[:<:]]Tension between[[:>:]]/Tension_between/g;
s/[[:<:]]Communications Network[[:>:]]/Communications_Network/g;
s/[[:<:]]compatible computers[[:>:]]/compatible_computers/g;
s/[[:<:]]tou dromou[[:>:]]/tou_dromou/g;
s/[[:<:]]Fight Like Apes[[:>:]]/Fight_Like_Apes/g;
s/[[:<:]]military service[[:>:]]/military_service/g;
s/[[:<:]]gave recitals[[:>:]]/gave_recitals/g;
s/[[:<:]]hunting ground[[:>:]]/hunting_ground/g;
s/[[:<:]]Jens Lekman[[:>:]]/Jens_Lekman/g;
s/[[:<:]]Zyuden Sentai Kyoryuger[[:>:]]/Zyuden_Sentai_Kyoryuger/g;
s/[[:<:]]dialect continuum[[:>:]]/dialect_continuum/g;
s/[[:<:]]Hedo Türkoğlu[[:>:]]/Hedo_Türkoğlu/g;
s/[[:<:]]claims against[[:>:]]/claims_against/g;
s/[[:<:]]Sheung Shui[[:>:]]/Sheung_Shui/g;
s/[[:<:]]Metropolitan Stadium[[:>:]]/Metropolitan_Stadium/g;
s/[[:<:]]José Maria[[:>:]]/José_Maria/g;
s/[[:<:]]– 1936[[:>:]]/–_1936/g;
s/[[:<:]]Warriston Cemetery[[:>:]]/Warriston_Cemetery/g;
s/[[:<:]]Deanna Troi[[:>:]]/Deanna_Troi/g;
s/[[:<:]]Davie Florida[[:>:]]/Davie_Florida/g;
s/[[:<:]]Super Soaker[[:>:]]/Super_Soaker/g;
s/[[:<:]]at up to[[:>:]]/at_up_to/g;
s/[[:<:]]Republican nominee[[:>:]]/Republican_nominee/g;
s/[[:<:]]melting glaciers[[:>:]]/melting_glaciers/g;
s/[[:<:]]Monte Bello[[:>:]]/Monte_Bello/g;
s/[[:<:]]Oakland A s[[:>:]]/Oakland_A_s/g;
s/[[:<:]]pituitary adenoma[[:>:]]/pituitary_adenoma/g;
s/[[:<:]]smaller firms[[:>:]]/smaller_firms/g;
s/[[:<:]]Seattle Storm[[:>:]]/Seattle_Storm/g;
s/[[:<:]]Orange California[[:>:]]/Orange_California/g;
s/[[:<:]]In 1567[[:>:]]/In_1567/g;
s/[[:<:]]unwed mother[[:>:]]/unwed_mother/g;
s/[[:<:]]Richard T[[:>:]]/Richard_T/g;
s/[[:<:]]customs officers[[:>:]]/customs_officers/g;
s/[[:<:]]prefrontal cortex[[:>:]]/prefrontal_cortex/g;
s/[[:<:]]Comedy Club[[:>:]]/Comedy_Club/g;
s/[[:<:]]document containing[[:>:]]/document_containing/g;
s/[[:<:]]heated up[[:>:]]/heated_up/g;
s/[[:<:]]Huntsville AL[[:>:]]/Huntsville_AL/g;
s/[[:<:]]Sinéad Cusack[[:>:]]/Sinéad_Cusack/g;
s/[[:<:]]transitional justice[[:>:]]/transitional_justice/g;
s/[[:<:]]Born Sinner[[:>:]]/Born_Sinner/g;
s/[[:<:]]the Valiants[[:>:]]/the_Valiants/g;
s/[[:<:]]would survive[[:>:]]/would_survive/g;
s/[[:<:]]Diane Cilento[[:>:]]/Diane_Cilento/g;
s/[[:<:]]Cape Farewell[[:>:]]/Cape_Farewell/g;
s/[[:<:]]athletics events[[:>:]]/athletics_events/g;
s/[[:<:]]Rookwood Cemetery[[:>:]]/Rookwood_Cemetery/g;
s/[[:<:]]lieutenant governors[[:>:]]/lieutenant_governors/g;
s/[[:<:]]Katalog Film Indonesia[[:>:]]/Katalog_Film_Indonesia/g;
s/[[:<:]]the shaping of[[:>:]]/the_shaping_of/g;
s/[[:<:]]at 28 August[[:>:]]/at_28_August/g;
s/[[:<:]]Jimmie Foxx[[:>:]]/Jimmie_Foxx/g;
s/[[:<:]]explanatory variable[[:>:]]/explanatory_variable/g;
s/[[:<:]]a motion of[[:>:]]/a_motion_of/g;
s/[[:<:]]is grown[[:>:]]/is_grown/g;
s/[[:<:]]wireless network[[:>:]]/wireless_network/g;
s/[[:<:]]an article from[[:>:]]/an_article_from/g;
s/[[:<:]]and video recordings[[:>:]]/and_video_recordings/g;
s/[[:<:]]rampant corruption[[:>:]]/rampant_corruption/g;
s/[[:<:]]countless other[[:>:]]/countless_other/g;
s/[[:<:]]24 2[[:>:]]/24_2/g;
s/[[:<:]]IgA nephropathy[[:>:]]/IgA_nephropathy/g;
s/[[:<:]]Northern Beaches[[:>:]]/Northern_Beaches/g;
s/[[:<:]]Kansas Legislature[[:>:]]/Kansas_Legislature/g;
s/[[:<:]]political appointments[[:>:]]/political_appointments/g;
s/[[:<:]]Zhongshu Shilang 中書侍郎[[:>:]]/Zhongshu_Shilang_中書侍郎/g;
s/[[:<:]]Stu Hart[[:>:]]/Stu_Hart/g;
s/[[:<:]]the team for[[:>:]]/the_team_for/g;
s/[[:<:]]McAllen Texas[[:>:]]/McAllen_Texas/g;
s/[[:<:]]Olimpia Milano[[:>:]]/Olimpia_Milano/g;
s/[[:<:]]tempered glass[[:>:]]/tempered_glass/g;
s/[[:<:]]general manager[[:>:]]/general_manager/g;
s/[[:<:]]Jim Stynes[[:>:]]/Jim_Stynes/g;
s/[[:<:]]Elm Yellows[[:>:]]/Elm_Yellows/g;
s/[[:<:]]at Mosport[[:>:]]/at_Mosport/g;
s/[[:<:]]unseeded teams[[:>:]]/unseeded_teams/g;
s/[[:<:]]the 18th season[[:>:]]/the_18th_season/g;
s/[[:<:]]alluding to[[:>:]]/alluding_to/g;
s/[[:<:]]family Rutaceae[[:>:]]/family_Rutaceae/g;
s/[[:<:]]role-playing games[[:>:]]/role-playing_games/g;
s/[[:<:]]Old Colony[[:>:]]/Old_Colony/g;
s/[[:<:]]premeditated murder[[:>:]]/premeditated_murder/g;
s/[[:<:]]Mister Mind[[:>:]]/Mister_Mind/g;
s/[[:<:]]Each participant[[:>:]]/Each_participant/g;
s/[[:<:]]Tracie Thoms[[:>:]]/Tracie_Thoms/g;
s/[[:<:]]Ramya Krishna[[:>:]]/Ramya_Krishna/g;
s/[[:<:]]USL PDL[[:>:]]/USL_PDL/g;
s/[[:<:]]motivating force[[:>:]]/motivating_force/g;
s/[[:<:]]Shaka Hislop[[:>:]]/Shaka_Hislop/g;
s/[[:<:]]Brock s[[:>:]]/Brock_s/g;
s/[[:<:]]fertile valley[[:>:]]/fertile_valley/g;
s/[[:<:]]Slate Meagher Flom[[:>:]]/Slate_Meagher_Flom/g;
s/[[:<:]]a shelter for[[:>:]]/a_shelter_for/g;
s/[[:<:]]was remastered[[:>:]]/was_remastered/g;
s/[[:<:]]geodesic equation[[:>:]]/geodesic_equation/g;
s/[[:<:]]Radioland Murders[[:>:]]/Radioland_Murders/g;
s/[[:<:]]Must Pass[[:>:]]/Must_Pass/g;
s/[[:<:]]500 m[[:>:]]/500_m/g;
s/[[:<:]]59 minutes[[:>:]]/59_minutes/g;
s/[[:<:]]ubiquitin-protein ligase[[:>:]]/ubiquitin-protein_ligase/g;
s/[[:<:]]rose above[[:>:]]/rose_above/g;
s/[[:<:]]Born on[[:>:]]/Born_on/g;
s/[[:<:]]the end she[[:>:]]/the_end_she/g;
s/[[:<:]]Roxbury Massachusetts[[:>:]]/Roxbury_Massachusetts/g;
s/[[:<:]]Faulkes Telescope[[:>:]]/Faulkes_Telescope/g;
s/[[:<:]]police procedural[[:>:]]/police_procedural/g;
s/[[:<:]]style dwelling[[:>:]]/style_dwelling/g;
s/[[:<:]]an amplifier[[:>:]]/an_amplifier/g;
s/[[:<:]]male counterpart[[:>:]]/male_counterpart/g;
s/[[:<:]]Ordnance Factories[[:>:]]/Ordnance_Factories/g;
s/[[:<:]]Nate Marquardt[[:>:]]/Nate_Marquardt/g;
s/[[:<:]]Pablo Milanés[[:>:]]/Pablo_Milanés/g;
s/[[:<:]]After one season[[:>:]]/After_one_season/g;
s/[[:<:]]the ordination of[[:>:]]/the_ordination_of/g;
s/[[:<:]]The Jeffersons[[:>:]]/The_Jeffersons/g;
s/[[:<:]]Ang Panday[[:>:]]/Ang_Panday/g;
s/[[:<:]]advantageous for[[:>:]]/advantageous_for/g;
s/[[:<:]]Jessica Chastain[[:>:]]/Jessica_Chastain/g;
s/[[:<:]]The Role of[[:>:]]/The_Role_of/g;
s/[[:<:]]refugee camps[[:>:]]/refugee_camps/g;
s/[[:<:]]his uncles[[:>:]]/his_uncles/g;
s/[[:<:]]overseas tour[[:>:]]/overseas_tour/g;
s/[[:<:]]telephone directories[[:>:]]/telephone_directories/g;
s/[[:<:]]and Palestine Campaign[[:>:]]/and_Palestine_Campaign/g;
s/[[:<:]]an oven[[:>:]]/an_oven/g;
s/[[:<:]]idiopathic hypersomnia[[:>:]]/idiopathic_hypersomnia/g;
s/[[:<:]]The Only Way[[:>:]]/The_Only_Way/g;
s/[[:<:]]less success[[:>:]]/less_success/g;
s/[[:<:]]sort that column[[:>:]]/sort_that_column/g;
s/[[:<:]]the organisers[[:>:]]/the_organisers/g;
s/[[:<:]]their sentences[[:>:]]/their_sentences/g;
s/[[:<:]]Rika Ishikawa[[:>:]]/Rika_Ishikawa/g;
s/[[:<:]]David C[[:>:]]/David_C/g;
s/[[:<:]]Mbit s[[:>:]]/Mbit_s/g;
s/[[:<:]]the immediate vicinity[[:>:]]/the_immediate_vicinity/g;
s/[[:<:]]in 1460[[:>:]]/in_1460/g;
s/[[:<:]]in the months[[:>:]]/in_the_months/g;
s/[[:<:]]Memory Lane[[:>:]]/Memory_Lane/g;
s/[[:<:]]volcanic tuff[[:>:]]/volcanic_tuff/g;
s/[[:<:]]A R Labs[[:>:]]/A_R_Labs/g;
s/[[:<:]]Holdings Berhad[[:>:]]/Holdings_Berhad/g;
s/[[:<:]]enzymatic reactions[[:>:]]/enzymatic_reactions/g;
s/[[:<:]]Crişul Alb[[:>:]]/Crişul_Alb/g;
s/[[:<:]]spin-off series[[:>:]]/spin-off_series/g;
s/[[:<:]]Gregorian Calendar[[:>:]]/Gregorian_Calendar/g;
s/[[:<:]]underwent another[[:>:]]/underwent_another/g;
s/[[:<:]]ബഹ ു.[[:>:]]/ബഹ_ു./g;
s/[[:<:]]could hear[[:>:]]/could_hear/g;
s/[[:<:]]charitable endeavors[[:>:]]/charitable_endeavors/g;
s/[[:<:]]Maraimalai Adigal[[:>:]]/Maraimalai_Adigal/g;
s/[[:<:]]travel guides[[:>:]]/travel_guides/g;
s/[[:<:]]Beitar Jerusalem[[:>:]]/Beitar_Jerusalem/g;
s/[[:<:]]Green Goblin[[:>:]]/Green_Goblin/g;
s/[[:<:]]cars and motorcycles[[:>:]]/cars_and_motorcycles/g;
s/[[:<:]]hostages were[[:>:]]/hostages_were/g;
s/[[:<:]]qualifying games[[:>:]]/qualifying_games/g;
s/[[:<:]]Kanyakumari district[[:>:]]/Kanyakumari_district/g;
s/[[:<:]]segmented into[[:>:]]/segmented_into/g;
s/[[:<:]]high-income countries[[:>:]]/high-income_countries/g;
s/[[:<:]]No 82[[:>:]]/No_82/g;
s/[[:<:]]€ 1[[:>:]]/€_1/g;
s/[[:<:]]detection range[[:>:]]/detection_range/g;
s/[[:<:]]an incompetent[[:>:]]/an_incompetent/g;
s/[[:<:]]contract expiring[[:>:]]/contract_expiring/g;
s/[[:<:]]Cajanus cajan[[:>:]]/Cajanus_cajan/g;
s/[[:<:]]felled by[[:>:]]/felled_by/g;
s/[[:<:]]in place to[[:>:]]/in_place_to/g;
s/[[:<:]]in Dnipropetrovsk[[:>:]]/in_Dnipropetrovsk/g;
s/[[:<:]]the intent of[[:>:]]/the_intent_of/g;
s/[[:<:]]Aras River[[:>:]]/Aras_River/g;
s/[[:<:]]Recording Arts[[:>:]]/Recording_Arts/g;
s/[[:<:]]Persona 4[[:>:]]/Persona_4/g;
s/[[:<:]]balance sheet[[:>:]]/balance_sheet/g;
s/[[:<:]]in 2006 it[[:>:]]/in_2006_it/g;
s/[[:<:]]expand rapidly[[:>:]]/expand_rapidly/g;
s/[[:<:]]this thing[[:>:]]/this_thing/g;
s/[[:<:]]She accepts[[:>:]]/She_accepts/g;
s/[[:<:]]Wang Jing[[:>:]]/Wang_Jing/g;
s/[[:<:]]neighboring municipality[[:>:]]/neighboring_municipality/g;
s/[[:<:]]pilgrimage route[[:>:]]/pilgrimage_route/g;
s/[[:<:]]Municipality Norrbotten[[:>:]]/Municipality_Norrbotten/g;
s/[[:<:]]Nguyen Thi[[:>:]]/Nguyen_Thi/g;
s/[[:<:]]an award-winning[[:>:]]/an_award-winning/g;
s/[[:<:]]km relay[[:>:]]/km_relay/g;
s/[[:<:]]financial meltdown[[:>:]]/financial_meltdown/g;
s/[[:<:]]and Staff Course[[:>:]]/and_Staff_Course/g;
s/[[:<:]]On 17[[:>:]]/On_17/g;
s/[[:<:]]cable system[[:>:]]/cable_system/g;
s/[[:<:]]La Cité[[:>:]]/La_Cité/g;
s/[[:<:]]Metropolitan School District[[:>:]]/Metropolitan_School_District/g;
s/[[:<:]]Mac computers[[:>:]]/Mac_computers/g;
s/[[:<:]]Lionel Barrymore[[:>:]]/Lionel_Barrymore/g;
s/[[:<:]]From 1983[[:>:]]/From_1983/g;
s/[[:<:]]de Sanctis[[:>:]]/de_Sanctis/g;
s/[[:<:]]domed roof[[:>:]]/domed_roof/g;
s/[[:<:]]a welfare state[[:>:]]/a_welfare_state/g;
s/[[:<:]]application developers[[:>:]]/application_developers/g;
s/[[:<:]]smeared with[[:>:]]/smeared_with/g;
s/[[:<:]]Charlie Crist[[:>:]]/Charlie_Crist/g;
s/[[:<:]]To establish[[:>:]]/To_establish/g;
s/[[:<:]]20 to 40[[:>:]]/20_to_40/g;
s/[[:<:]]jet fighters[[:>:]]/jet_fighters/g;
s/[[:<:]]manual labour[[:>:]]/manual_labour/g;
s/[[:<:]]subject to[[:>:]]/subject_to/g;
s/[[:<:]]consulting firm[[:>:]]/consulting_firm/g;
s/[[:<:]]Mirogoj Cemetery[[:>:]]/Mirogoj_Cemetery/g;
s/[[:<:]]Eulogy Recordings[[:>:]]/Eulogy_Recordings/g;
s/[[:<:]]was activated[[:>:]]/was_activated/g;
s/[[:<:]]Valentina Tereshkova[[:>:]]/Valentina_Tereshkova/g;
s/[[:<:]]These devices[[:>:]]/These_devices/g;
s/[[:<:]]the common name[[:>:]]/the_common_name/g;
s/[[:<:]]PlayStation Home[[:>:]]/PlayStation_Home/g;
s/[[:<:]]the upper[[:>:]]/the_upper/g;
s/[[:<:]]Information System[[:>:]]/Information_System/g;
s/[[:<:]]200-metre freestyle[[:>:]]/200-metre_freestyle/g;
s/[[:<:]]Golden Valley[[:>:]]/Golden_Valley/g;
s/[[:<:]]draws against[[:>:]]/draws_against/g;
s/[[:<:]]$4.4 billion[[:>:]]/$4.4_billion/g;
s/[[:<:]]Maharaja Sayajirao[[:>:]]/Maharaja_Sayajirao/g;
s/[[:<:]]singles released[[:>:]]/singles_released/g;
s/[[:<:]]Kanab Utah[[:>:]]/Kanab_Utah/g;
s/[[:<:]]fade into[[:>:]]/fade_into/g;
s/[[:<:]]the frontman of[[:>:]]/the_frontman_of/g;
s/[[:<:]]Preacher Man[[:>:]]/Preacher_Man/g;
s/[[:<:]]cervical vertebra[[:>:]]/cervical_vertebra/g;
s/[[:<:]]cardboard boxes[[:>:]]/cardboard_boxes/g;
s/[[:<:]]Božena Němcová[[:>:]]/Božena_Němcová/g;
s/[[:<:]]cyclic group[[:>:]]/cyclic_group/g;
s/[[:<:]]Ngāti Ruanui[[:>:]]/Ngāti_Ruanui/g;
s/[[:<:]]Cyborg 009[[:>:]]/Cyborg_009/g;
s/[[:<:]]Trumbull Connecticut[[:>:]]/Trumbull_Connecticut/g;
s/[[:<:]]Insensato Coração[[:>:]]/Insensato_Coração/g;
s/[[:<:]]surrogate mother[[:>:]]/surrogate_mother/g;
s/[[:<:]]Gjergj Arianiti[[:>:]]/Gjergj_Arianiti/g;
s/[[:<:]]Abdul Qader[[:>:]]/Abdul_Qader/g;
s/[[:<:]]laws that[[:>:]]/laws_that/g;
s/[[:<:]]real ales[[:>:]]/real_ales/g;
s/[[:<:]]Fighting Talk[[:>:]]/Fighting_Talk/g;
s/[[:<:]]Miloš Obrenović[[:>:]]/Miloš_Obrenović/g;
s/[[:<:]]Yarlung Tsangpo[[:>:]]/Yarlung_Tsangpo/g;
s/[[:<:]]high technology[[:>:]]/high_technology/g;
s/[[:<:]]this country[[:>:]]/this_country/g;
s/[[:<:]]Luft- und Raumfahrt[[:>:]]/Luft-_und_Raumfahrt/g;
s/[[:<:]]TV and film[[:>:]]/TV_and_film/g;
s/[[:<:]]fractured cheekbone[[:>:]]/fractured_cheekbone/g;
s/[[:<:]]portrait of[[:>:]]/portrait_of/g;
s/[[:<:]]either alone[[:>:]]/either_alone/g;
s/[[:<:]]Kellogg Company[[:>:]]/Kellogg_Company/g;
s/[[:<:]]16th Karmapa[[:>:]]/16th_Karmapa/g;
s/[[:<:]]my job[[:>:]]/my_job/g;
s/[[:<:]]without discrimination[[:>:]]/without_discrimination/g;
s/[[:<:]]de Borja[[:>:]]/de_Borja/g;
s/[[:<:]]public speech[[:>:]]/public_speech/g;
s/[[:<:]]rapid intensification[[:>:]]/rapid_intensification/g;
s/[[:<:]]kept alive[[:>:]]/kept_alive/g;
s/[[:<:]]TV programme[[:>:]]/TV_programme/g;
s/[[:<:]]Lukáš Dlouhý[[:>:]]/Lukáš_Dlouhý/g;
s/[[:<:]]the backup quarterback[[:>:]]/the_backup_quarterback/g;
s/[[:<:]]the third-best[[:>:]]/the_third-best/g;
s/[[:<:]]Chess Congress[[:>:]]/Chess_Congress/g;
s/[[:<:]]Adirondack Northway[[:>:]]/Adirondack_Northway/g;
s/[[:<:]]Trier-Saarburg district[[:>:]]/Trier-Saarburg_district/g;
s/[[:<:]]survey vessel[[:>:]]/survey_vessel/g;
s/[[:<:]]Journals Online[[:>:]]/Journals_Online/g;
s/[[:<:]]need special education[[:>:]]/need_special_education/g;
s/[[:<:]]Vijay Anand[[:>:]]/Vijay_Anand/g;
s/[[:<:]]may not[[:>:]]/may_not/g;
s/[[:<:]]Jin s[[:>:]]/Jin_s/g;
s/[[:<:]]SportsChannel America[[:>:]]/SportsChannel_America/g;
s/[[:<:]]Jim Steranko[[:>:]]/Jim_Steranko/g;
s/[[:<:]]Twenty-seventh Congress[[:>:]]/Twenty-seventh_Congress/g;
s/[[:<:]]maxillary barbels[[:>:]]/maxillary_barbels/g;
s/[[:<:]]Banco Mercantil[[:>:]]/Banco_Mercantil/g;
s/[[:<:]]Elysian Park[[:>:]]/Elysian_Park/g;
s/[[:<:]]the clitoris[[:>:]]/the_clitoris/g;
s/[[:<:]]distribution network[[:>:]]/distribution_network/g;
s/[[:<:]]prayed for[[:>:]]/prayed_for/g;
s/[[:<:]]This also allows[[:>:]]/This_also_allows/g;
s/[[:<:]]a prince[[:>:]]/a_prince/g;
s/[[:<:]]Appreciation Society[[:>:]]/Appreciation_Society/g;
s/[[:<:]]the fixed point[[:>:]]/the_fixed_point/g;
s/[[:<:]]Jagathi Sreekumar[[:>:]]/Jagathi_Sreekumar/g;
s/[[:<:]]two battleships[[:>:]]/two_battleships/g;
s/[[:<:]]Fiscal Responsibility[[:>:]]/Fiscal_Responsibility/g;
s/[[:<:]]Other languages[[:>:]]/Other_languages/g;
s/[[:<:]]in Laos[[:>:]]/in_Laos/g;
s/[[:<:]]provoked outrage[[:>:]]/provoked_outrage/g;
s/[[:<:]]30 7[[:>:]]/30_7/g;
s/[[:<:]]modeled using[[:>:]]/modeled_using/g;
s/[[:<:]]a nameless[[:>:]]/a_nameless/g;
s/[[:<:]]Airbus A320s[[:>:]]/Airbus_A320s/g;
s/[[:<:]]in Division 3[[:>:]]/in_Division_3/g;
s/[[:<:]]Metallurgical Engineering[[:>:]]/Metallurgical_Engineering/g;
s/[[:<:]]national sport[[:>:]]/national_sport/g;
s/[[:<:]]5th season[[:>:]]/5th_season/g;
s/[[:<:]]Alberto Sordi[[:>:]]/Alberto_Sordi/g;
s/[[:<:]]RNA-binding protein[[:>:]]/RNA-binding_protein/g;
s/[[:<:]]sodium hydroxide[[:>:]]/sodium_hydroxide/g;
s/[[:<:]]Antarctic krill[[:>:]]/Antarctic_krill/g;
s/[[:<:]]Rahat Fateh[[:>:]]/Rahat_Fateh/g;
s/[[:<:]]culmination of[[:>:]]/culmination_of/g;
s/[[:<:]]no Michi[[:>:]]/no_Michi/g;
s/[[:<:]]pursuant to[[:>:]]/pursuant_to/g;
s/[[:<:]]help me[[:>:]]/help_me/g;
s/[[:<:]]can sometimes[[:>:]]/can_sometimes/g;
s/[[:<:]]written in German[[:>:]]/written_in_German/g;
s/[[:<:]]the ECHL[[:>:]]/the_ECHL/g;
s/[[:<:]]Judas Priest[[:>:]]/Judas_Priest/g;
s/[[:<:]]Research Fellowship[[:>:]]/Research_Fellowship/g;
s/[[:<:]]family Clausiliidae[[:>:]]/family_Clausiliidae/g;
s/[[:<:]]would still be[[:>:]]/would_still_be/g;
s/[[:<:]]grade ranked[[:>:]]/grade_ranked/g;
s/[[:<:]]Primary Education[[:>:]]/Primary_Education/g;
s/[[:<:]]sonnō jōi[[:>:]]/sonnō_jōi/g;
s/[[:<:]]some 6 000[[:>:]]/some_6_000/g;
s/[[:<:]]slotted flaps[[:>:]]/slotted_flaps/g;
s/[[:<:]]Another name for[[:>:]]/Another_name_for/g;
s/[[:<:]]considered taboo[[:>:]]/considered_taboo/g;
s/[[:<:]]less stringent[[:>:]]/less_stringent/g;
s/[[:<:]]security officer[[:>:]]/security_officer/g;
s/[[:<:]]has not played[[:>:]]/has_not_played/g;
s/[[:<:]]Community Association[[:>:]]/Community_Association/g;
s/[[:<:]]tuberous sclerosis[[:>:]]/tuberous_sclerosis/g;
s/[[:<:]]180 kg[[:>:]]/180_kg/g;
s/[[:<:]]Bircham Newton[[:>:]]/Bircham_Newton/g;
s/[[:<:]]Molecule Man[[:>:]]/Molecule_Man/g;
s/[[:<:]]lush vegetation[[:>:]]/lush_vegetation/g;
s/[[:<:]]6th Viscount[[:>:]]/6th_Viscount/g;
s/[[:<:]]warns her that[[:>:]]/warns_her_that/g;
s/[[:<:]]our senses[[:>:]]/our_senses/g;
s/[[:<:]]Ó Ceallaigh[[:>:]]/Ó_Ceallaigh/g;
s/[[:<:]]solar photovoltaics[[:>:]]/solar_photovoltaics/g;
s/[[:<:]]finds herself[[:>:]]/finds_herself/g;
s/[[:<:]]45 minute[[:>:]]/45_minute/g;
s/[[:<:]]New Male Talent[[:>:]]/New_Male_Talent/g;
s/[[:<:]]bats are[[:>:]]/bats_are/g;
s/[[:<:]]paramilitary organisation[[:>:]]/paramilitary_organisation/g;
s/[[:<:]]Alan Smithee[[:>:]]/Alan_Smithee/g;
s/[[:<:]]Alan Shatter[[:>:]]/Alan_Shatter/g;
s/[[:<:]]Philadelphia Mint[[:>:]]/Philadelphia_Mint/g;
s/[[:<:]]kill herself[[:>:]]/kill_herself/g;
s/[[:<:]]Eddie s[[:>:]]/Eddie_s/g;
s/[[:<:]]They Came[[:>:]]/They_Came/g;
s/[[:<:]]biblical scholar[[:>:]]/biblical_scholar/g;
s/[[:<:]]owned it until[[:>:]]/owned_it_until/g;
s/[[:<:]]Wesley Morris[[:>:]]/Wesley_Morris/g;
s/[[:<:]]a three-year[[:>:]]/a_three-year/g;
s/[[:<:]]Green Team[[:>:]]/Green_Team/g;
s/[[:<:]]After examining[[:>:]]/After_examining/g;
s/[[:<:]]Arseny Semionov[[:>:]]/Arseny_Semionov/g;
s/[[:<:]]063 for females[[:>:]]/063_for_females/g;
s/[[:<:]]possessive suffix[[:>:]]/possessive_suffix/g;
s/[[:<:]]Wild Hunt[[:>:]]/Wild_Hunt/g;
s/[[:<:]]sees through[[:>:]]/sees_through/g;
s/[[:<:]]Tarxien Rainbows[[:>:]]/Tarxien_Rainbows/g;
s/[[:<:]]prevented from[[:>:]]/prevented_from/g;
s/[[:<:]]before election day[[:>:]]/before_election_day/g;
s/[[:<:]]in 47 games[[:>:]]/in_47_games/g;
s/[[:<:]]tax on[[:>:]]/tax_on/g;
s/[[:<:]]Business Process[[:>:]]/Business_Process/g;
s/[[:<:]]Banat of Temeschwar[[:>:]]/Banat_of_Temeschwar/g;
s/[[:<:]]Ozone Layer Protection[[:>:]]/Ozone_Layer_Protection/g;
s/[[:<:]]Torrie Wilson[[:>:]]/Torrie_Wilson/g;
s/[[:<:]]De Aar[[:>:]]/De_Aar/g;
s/[[:<:]]NASCAR Busch[[:>:]]/NASCAR_Busch/g;
s/[[:<:]]Production designer[[:>:]]/Production_designer/g;
s/[[:<:]]García born[[:>:]]/García_born/g;
s/[[:<:]]Lana Parrilla[[:>:]]/Lana_Parrilla/g;
s/[[:<:]]255 255[[:>:]]/255_255/g;
s/[[:<:]]devoted himself to[[:>:]]/devoted_himself_to/g;
s/[[:<:]]snippet of[[:>:]]/snippet_of/g;
s/[[:<:]]murex snails[[:>:]]/murex_snails/g;
s/[[:<:]]public transit[[:>:]]/public_transit/g;
s/[[:<:]]takes place[[:>:]]/takes_place/g;
s/[[:<:]]nearly circular[[:>:]]/nearly_circular/g;
s/[[:<:]]Diamond Jaxx[[:>:]]/Diamond_Jaxx/g;
s/[[:<:]]්‍ ර[[:>:]]/්‍_ර/g;
s/[[:<:]]acting skills[[:>:]]/acting_skills/g;
s/[[:<:]]the protagonist[[:>:]]/the_protagonist/g;
s/[[:<:]]voiced concern[[:>:]]/voiced_concern/g;
s/[[:<:]]closer inspection[[:>:]]/closer_inspection/g;
s/[[:<:]]is not normally[[:>:]]/is_not_normally/g;
s/[[:<:]]which 28 8[[:>:]]/which_28_8/g;
s/[[:<:]]gastropod mollusc[[:>:]]/gastropod_mollusc/g;
s/[[:<:]]Yeh Rishta[[:>:]]/Yeh_Rishta/g;
s/[[:<:]]David Ben-Gurion[[:>:]]/David_Ben-Gurion/g;
s/[[:<:]]ecclesiastical court[[:>:]]/ecclesiastical_court/g;
s/[[:<:]]Dirty Laundry[[:>:]]/Dirty_Laundry/g;
s/[[:<:]]Seven Cities[[:>:]]/Seven_Cities/g;
s/[[:<:]]comedy pilot[[:>:]]/comedy_pilot/g;
s/[[:<:]]send them[[:>:]]/send_them/g;
s/[[:<:]]logging road[[:>:]]/logging_road/g;
s/[[:<:]]Leon Schlesinger[[:>:]]/Leon_Schlesinger/g;
s/[[:<:]]Whaling Company[[:>:]]/Whaling_Company/g;
s/[[:<:]]Metropolitan Police[[:>:]]/Metropolitan_Police/g;
s/[[:<:]]at Georgetown[[:>:]]/at_Georgetown/g;
s/[[:<:]]Midi-Pyrénées France[[:>:]]/Midi-Pyrénées_France/g;
s/[[:<:]]Kokuritsu Kōen[[:>:]]/Kokuritsu_Kōen/g;
s/[[:<:]]Santosh Trophy[[:>:]]/Santosh_Trophy/g;
s/[[:<:]]distressed by[[:>:]]/distressed_by/g;
s/[[:<:]]Quatre Bornes[[:>:]]/Quatre_Bornes/g;
s/[[:<:]]similar in appearance[[:>:]]/similar_in_appearance/g;
s/[[:<:]]proton transfer[[:>:]]/proton_transfer/g;
s/[[:<:]]all-round performance[[:>:]]/all-round_performance/g;
s/[[:<:]]could provide[[:>:]]/could_provide/g;
s/[[:<:]]Paizo Publishing s[[:>:]]/Paizo_Publishing_s/g;
s/[[:<:]]DDR SDRAM[[:>:]]/DDR_SDRAM/g;
s/[[:<:]]NHRA Mello Yello[[:>:]]/NHRA_Mello_Yello/g;
s/[[:<:]]Alfred I duPont[[:>:]]/Alfred_I_duPont/g;
s/[[:<:]]Lubycza Królewska[[:>:]]/Lubycza_Królewska/g;
s/[[:<:]]athletic fields[[:>:]]/athletic_fields/g;
s/[[:<:]]fateful decision[[:>:]]/fateful_decision/g;
s/[[:<:]]gradually become[[:>:]]/gradually_become/g;
s/[[:<:]]sniper rifles[[:>:]]/sniper_rifles/g;
s/[[:<:]]NBA Live[[:>:]]/NBA_Live/g;
s/[[:<:]]Nature Sanctuary[[:>:]]/Nature_Sanctuary/g;
s/[[:<:]]musical artist[[:>:]]/musical_artist/g;
s/[[:<:]]before retiring[[:>:]]/before_retiring/g;
s/[[:<:]]relieve overcrowding[[:>:]]/relieve_overcrowding/g;
s/[[:<:]]Arkadelphia Arkansas[[:>:]]/Arkadelphia_Arkansas/g;
s/[[:<:]]vibrational energy[[:>:]]/vibrational_energy/g;
s/[[:<:]]Tylwyth Teg[[:>:]]/Tylwyth_Teg/g;
s/[[:<:]]Shaikh Hamad[[:>:]]/Shaikh_Hamad/g;
s/[[:<:]]় দ[[:>:]]/়_দ/g;
s/[[:<:]]Symbolic Logic[[:>:]]/Symbolic_Logic/g;
s/[[:<:]]Buckminster Fuller[[:>:]]/Buckminster_Fuller/g;
s/[[:<:]]all sources ranked[[:>:]]/all_sources_ranked/g;
s/[[:<:]]Marine Force[[:>:]]/Marine_Force/g;
s/[[:<:]]guest star[[:>:]]/guest_star/g;
s/[[:<:]]pilgrimage to[[:>:]]/pilgrimage_to/g;
s/[[:<:]]limiting or prohibiting[[:>:]]/limiting_or_prohibiting/g;
s/[[:<:]]Jalal Talabani[[:>:]]/Jalal_Talabani/g;
s/[[:<:]]Sheepshead Bay[[:>:]]/Sheepshead_Bay/g;
s/[[:<:]]34th season[[:>:]]/34th_season/g;
s/[[:<:]]broadcast tower[[:>:]]/broadcast_tower/g;
s/[[:<:]]at the 2012[[:>:]]/at_the_2012/g;
s/[[:<:]]DIY ethic[[:>:]]/DIY_ethic/g;
s/[[:<:]]Extended Mix[[:>:]]/Extended_Mix/g;
s/[[:<:]]buzzer beater[[:>:]]/buzzer_beater/g;
s/[[:<:]]Dheeran Chinnamalai[[:>:]]/Dheeran_Chinnamalai/g;
s/[[:<:]]neglected tropical diseases[[:>:]]/neglected_tropical_diseases/g;
s/[[:<:]]their decisions[[:>:]]/their_decisions/g;
s/[[:<:]]Société entomologique[[:>:]]/Société_entomologique/g;
s/[[:<:]]Freddie Hubbard[[:>:]]/Freddie_Hubbard/g;
s/[[:<:]]spangled grey plumage[[:>:]]/spangled_grey_plumage/g;
s/[[:<:]]Tom Thumb[[:>:]]/Tom_Thumb/g;
s/[[:<:]]during the 1972[[:>:]]/during_the_1972/g;
s/[[:<:]]The Town of[[:>:]]/The_Town_of/g;
s/[[:<:]]endangered animals[[:>:]]/endangered_animals/g;
s/[[:<:]]Bonnie Hunt[[:>:]]/Bonnie_Hunt/g;
s/[[:<:]]00 P M[[:>:]]/00_P_M/g;
s/[[:<:]]8th centuries[[:>:]]/8th_centuries/g;
s/[[:<:]]If these[[:>:]]/If_these/g;
s/[[:<:]]Special Effects[[:>:]]/Special_Effects/g;
s/[[:<:]]National Coalition[[:>:]]/National_Coalition/g;
s/[[:<:]]The constitution[[:>:]]/The_constitution/g;
s/[[:<:]]Awami League[[:>:]]/Awami_League/g;
s/[[:<:]]water buffalo[[:>:]]/water_buffalo/g;
s/[[:<:]]Esoteric Buddhism[[:>:]]/Esoteric_Buddhism/g;
s/[[:<:]]This increases[[:>:]]/This_increases/g;
s/[[:<:]]The Incredible[[:>:]]/The_Incredible/g;
s/[[:<:]]BGO Records[[:>:]]/BGO_Records/g;
s/[[:<:]]Aaronic priesthood[[:>:]]/Aaronic_priesthood/g;
s/[[:<:]]information visualization[[:>:]]/information_visualization/g;
s/[[:<:]]characters names[[:>:]]/characters_names/g;
s/[[:<:]]the name change[[:>:]]/the_name_change/g;
s/[[:<:]]– 91[[:>:]]/–_91/g;
s/[[:<:]]cardiac tamponade[[:>:]]/cardiac_tamponade/g;
s/[[:<:]]binomial name[[:>:]]/binomial_name/g;
s/[[:<:]]European Americans[[:>:]]/European_Americans/g;
s/[[:<:]]Gary Bettman[[:>:]]/Gary_Bettman/g;
s/[[:<:]]fall winter[[:>:]]/fall_winter/g;
s/[[:<:]]Aerolíneas Argentinas[[:>:]]/Aerolíneas_Argentinas/g;
s/[[:<:]]per 0 01[[:>:]]/per_0_01/g;
s/[[:<:]]Wissenschaft des Judentums[[:>:]]/Wissenschaft_des_Judentums/g;
s/[[:<:]]paid-up capital[[:>:]]/paid-up_capital/g;
s/[[:<:]]Marquee Club[[:>:]]/Marquee_Club/g;
s/[[:<:]]non-residential buildings[[:>:]]/non-residential_buildings/g;
s/[[:<:]]episode Recurring[[:>:]]/episode_Recurring/g;
s/[[:<:]]ecclesiastical discipline[[:>:]]/ecclesiastical_discipline/g;
s/[[:<:]]La Bouche[[:>:]]/La_Bouche/g;
s/[[:<:]]Joan Gamper[[:>:]]/Joan_Gamper/g;
s/[[:<:]]Tony Trabert[[:>:]]/Tony_Trabert/g;
s/[[:<:]]Main Range[[:>:]]/Main_Range/g;
s/[[:<:]]Eamonn Holmes[[:>:]]/Eamonn_Holmes/g;
s/[[:<:]]Forschungsanstalt für[[:>:]]/Forschungsanstalt_für/g;
s/[[:<:]]Cardiff Castle[[:>:]]/Cardiff_Castle/g;
s/[[:<:]]Theodor Mommsen[[:>:]]/Theodor_Mommsen/g;
s/[[:<:]]Chips Rafferty[[:>:]]/Chips_Rafferty/g;
s/[[:<:]]Li Keqiang[[:>:]]/Li_Keqiang/g;
s/[[:<:]]grunge movement[[:>:]]/grunge_movement/g;
s/[[:<:]]Orthodox Church[[:>:]]/Orthodox_Church/g;
s/[[:<:]]the caldera[[:>:]]/the_caldera/g;
s/[[:<:]]putting down[[:>:]]/putting_down/g;
s/[[:<:]]Frank Herbert s[[:>:]]/Frank_Herbert_s/g;
s/[[:<:]]Primer Impacto[[:>:]]/Primer_Impacto/g;
s/[[:<:]]Saratoga CV-3[[:>:]]/Saratoga_CV-3/g;
s/[[:<:]]several CDs[[:>:]]/several_CDs/g;
s/[[:<:]]Computer Society[[:>:]]/Computer_Society/g;
s/[[:<:]]Fast Forward[[:>:]]/Fast_Forward/g;
s/[[:<:]]Chris Eubank[[:>:]]/Chris_Eubank/g;
s/[[:<:]]He also taught[[:>:]]/He_also_taught/g;
s/[[:<:]]Diet of Worms[[:>:]]/Diet_of_Worms/g;
s/[[:<:]]drawn against[[:>:]]/drawn_against/g;
s/[[:<:]]an interesting[[:>:]]/an_interesting/g;
s/[[:<:]]free online[[:>:]]/free_online/g;
s/[[:<:]]and community organizations[[:>:]]/and_community_organizations/g;
s/[[:<:]]psychiatric conditions[[:>:]]/psychiatric_conditions/g;
s/[[:<:]]Montgomery C Meigs[[:>:]]/Montgomery_C_Meigs/g;
s/[[:<:]]Broome Street[[:>:]]/Broome_Street/g;
s/[[:<:]]Bachao Andolan[[:>:]]/Bachao_Andolan/g;
s/[[:<:]]Anna Politkovskaya[[:>:]]/Anna_Politkovskaya/g;
s/[[:<:]]She had been[[:>:]]/She_had_been/g;
s/[[:<:]]three-body problem[[:>:]]/three-body_problem/g;
s/[[:<:]]Morbid Angel[[:>:]]/Morbid_Angel/g;
s/[[:<:]]Harbin Heilongjiang[[:>:]]/Harbin_Heilongjiang/g;
s/[[:<:]]Keith Forsey[[:>:]]/Keith_Forsey/g;
s/[[:<:]]” and “[[:>:]]/”_and_“/g;
s/[[:<:]]Upper Peninsula[[:>:]]/Upper_Peninsula/g;
s/[[:<:]]characters are[[:>:]]/characters_are/g;
s/[[:<:]]Nawab Nazim[[:>:]]/Nawab_Nazim/g;
s/[[:<:]]the efforts of[[:>:]]/the_efforts_of/g;
s/[[:<:]]brought with it[[:>:]]/brought_with_it/g;
s/[[:<:]]Thái Tông[[:>:]]/Thái_Tông/g;
s/[[:<:]]domestic cats[[:>:]]/domestic_cats/g;
s/[[:<:]]Sino-Tibetan language[[:>:]]/Sino-Tibetan_language/g;
s/[[:<:]]symbols are[[:>:]]/symbols_are/g;
s/[[:<:]]du Capitole[[:>:]]/du_Capitole/g;
s/[[:<:]]Divinity School[[:>:]]/Divinity_School/g;
s/[[:<:]]hovered around[[:>:]]/hovered_around/g;
s/[[:<:]]া দ[[:>:]]/া_দ/g;
s/[[:<:]]charitable institution[[:>:]]/charitable_institution/g;
s/[[:<:]]Lotus corniculatus[[:>:]]/Lotus_corniculatus/g;
s/[[:<:]]Halit Refiğ[[:>:]]/Halit_Refiğ/g;
s/[[:<:]]license plates[[:>:]]/license_plates/g;
s/[[:<:]]a service SaaS[[:>:]]/a_service_SaaS/g;
s/[[:<:]]was positioned[[:>:]]/was_positioned/g;
s/[[:<:]]the hurricane[[:>:]]/the_hurricane/g;
s/[[:<:]]natural scenery[[:>:]]/natural_scenery/g;
s/[[:<:]]six-song EP[[:>:]]/six-song_EP/g;
s/[[:<:]]White Americans[[:>:]]/White_Americans/g;
s/[[:<:]]flowers are[[:>:]]/flowers_are/g;
s/[[:<:]]was self-released[[:>:]]/was_self-released/g;
s/[[:<:]]Zoran Janković[[:>:]]/Zoran_Janković/g;
s/[[:<:]]He enjoys[[:>:]]/He_enjoys/g;
s/[[:<:]]Cradley Heath[[:>:]]/Cradley_Heath/g;
s/[[:<:]]detected by[[:>:]]/detected_by/g;
s/[[:<:]]De Oro[[:>:]]/De_Oro/g;
s/[[:<:]]techniques are[[:>:]]/techniques_are/g;
s/[[:<:]]Russian Илья[[:>:]]/Russian_Илья/g;
s/[[:<:]]and elected to[[:>:]]/and_elected_to/g;
s/[[:<:]]million records[[:>:]]/million_records/g;
s/[[:<:]]Up and Down[[:>:]]/Up_and_Down/g;
s/[[:<:]]Bhupen Hazarika[[:>:]]/Bhupen_Hazarika/g;
s/[[:<:]]our economy[[:>:]]/our_economy/g;
s/[[:<:]]Conseco Fieldhouse[[:>:]]/Conseco_Fieldhouse/g;
s/[[:<:]]Transverse Ranges[[:>:]]/Transverse_Ranges/g;
s/[[:<:]]extradited to[[:>:]]/extradited_to/g;
s/[[:<:]]Cab Calloway[[:>:]]/Cab_Calloway/g;
s/[[:<:]]phage display[[:>:]]/phage_display/g;
s/[[:<:]]จ ั[[:>:]]/จ_ั/g;
s/[[:<:]]Strategic Wing[[:>:]]/Strategic_Wing/g;
s/[[:<:]]Idris Elba[[:>:]]/Idris_Elba/g;
s/[[:<:]]intended victim[[:>:]]/intended_victim/g;
s/[[:<:]]so rapidly[[:>:]]/so_rapidly/g;
s/[[:<:]]governed by[[:>:]]/governed_by/g;
s/[[:<:]]F91 Dudelange[[:>:]]/F91_Dudelange/g;
s/[[:<:]]her masts[[:>:]]/her_masts/g;
s/[[:<:]]Diamond Sutra[[:>:]]/Diamond_Sutra/g;
s/[[:<:]]cycled through[[:>:]]/cycled_through/g;
s/[[:<:]]GMA Telebabad[[:>:]]/GMA_Telebabad/g;
s/[[:<:]]advisor to[[:>:]]/advisor_to/g;
s/[[:<:]]would facilitate[[:>:]]/would_facilitate/g;
s/[[:<:]]– 1837[[:>:]]/–_1837/g;
s/[[:<:]]Jesse Pinkman[[:>:]]/Jesse_Pinkman/g;
s/[[:<:]]prayer beads[[:>:]]/prayer_beads/g;
s/[[:<:]]precipitated by[[:>:]]/precipitated_by/g;
s/[[:<:]]protest marches[[:>:]]/protest_marches/g;
s/[[:<:]]Marty McSorley[[:>:]]/Marty_McSorley/g;
s/[[:<:]]Dieterich Buxtehude[[:>:]]/Dieterich_Buxtehude/g;
s/[[:<:]]Mark Coleman[[:>:]]/Mark_Coleman/g;
s/[[:<:]]Leipziger Platz[[:>:]]/Leipziger_Platz/g;
s/[[:<:]]third-placed team[[:>:]]/third-placed_team/g;
s/[[:<:]]Hindu Brahmin[[:>:]]/Hindu_Brahmin/g;
s/[[:<:]]loved it[[:>:]]/loved_it/g;
s/[[:<:]]Dorje Shugden[[:>:]]/Dorje_Shugden/g;
s/[[:<:]]Sleeping Dogs[[:>:]]/Sleeping_Dogs/g;
s/[[:<:]]uniformity of[[:>:]]/uniformity_of/g;
s/[[:<:]]Humanae vitae[[:>:]]/Humanae_vitae/g;
s/[[:<:]]Mick McCarthy[[:>:]]/Mick_McCarthy/g;
s/[[:<:]]Aşk-ı Memnu[[:>:]]/Aşk-ı_Memnu/g;
s/[[:<:]]episcopi vagantes[[:>:]]/episcopi_vagantes/g;
s/[[:<:]]Quack Pack[[:>:]]/Quack_Pack/g;
s/[[:<:]]Illegal immigration[[:>:]]/Illegal_immigration/g;
s/[[:<:]]and index finger[[:>:]]/and_index_finger/g;
s/[[:<:]]the tagline[[:>:]]/the_tagline/g;
s/[[:<:]]Carbondale Area[[:>:]]/Carbondale_Area/g;
s/[[:<:]]Bow Street[[:>:]]/Bow_Street/g;
s/[[:<:]]take photos[[:>:]]/take_photos/g;
s/[[:<:]]a light-hearted[[:>:]]/a_light-hearted/g;
s/[[:<:]]Detective Story[[:>:]]/Detective_Story/g;
s/[[:<:]]Lord Derby[[:>:]]/Lord_Derby/g;
s/[[:<:]]cardboard cutouts[[:>:]]/cardboard_cutouts/g;
s/[[:<:]]saved from[[:>:]]/saved_from/g;
s/[[:<:]]an electorate[[:>:]]/an_electorate/g;
s/[[:<:]]Bruce Spizer[[:>:]]/Bruce_Spizer/g;
s/[[:<:]]walking tour[[:>:]]/walking_tour/g;
s/[[:<:]]bout with[[:>:]]/bout_with/g;
s/[[:<:]]corpora cavernosa[[:>:]]/corpora_cavernosa/g;
s/[[:<:]]jazz clarinetist[[:>:]]/jazz_clarinetist/g;
s/[[:<:]]Democratic primary with[[:>:]]/Democratic_primary_with/g;
s/[[:<:]]Order Restoration Council[[:>:]]/Order_Restoration_Council/g;
s/[[:<:]]umbilical cord[[:>:]]/umbilical_cord/g;
s/[[:<:]]Naval Officer[[:>:]]/Naval_Officer/g;
s/[[:<:]]Sin Salida[[:>:]]/Sin_Salida/g;
s/[[:<:]]field crops[[:>:]]/field_crops/g;
s/[[:<:]]Digital Economy[[:>:]]/Digital_Economy/g;
s/[[:<:]]the TTC[[:>:]]/the_TTC/g;
s/[[:<:]]limited-access freeway[[:>:]]/limited-access_freeway/g;
s/[[:<:]]ashlar masonry[[:>:]]/ashlar_masonry/g;
s/[[:<:]]occupied Europe[[:>:]]/occupied_Europe/g;
s/[[:<:]]the air with[[:>:]]/the_air_with/g;
s/[[:<:]]in the 1963[[:>:]]/in_the_1963/g;
s/[[:<:]]a plantation[[:>:]]/a_plantation/g;
s/[[:<:]]a Scottish former[[:>:]]/a_Scottish_former/g;
s/[[:<:]]Andy s[[:>:]]/Andy_s/g;
s/[[:<:]]competes against[[:>:]]/competes_against/g;
s/[[:<:]]its extensive[[:>:]]/its_extensive/g;
s/[[:<:]]Metropolis Records[[:>:]]/Metropolis_Records/g;
s/[[:<:]]SO4 2[[:>:]]/SO4_2/g;
s/[[:<:]]cover photograph[[:>:]]/cover_photograph/g;
s/[[:<:]]latissimus dorsi[[:>:]]/latissimus_dorsi/g;
s/[[:<:]]their daughters[[:>:]]/their_daughters/g;
s/[[:<:]]Anantnag district[[:>:]]/Anantnag_district/g;
s/[[:<:]]Tony Wilson[[:>:]]/Tony_Wilson/g;
s/[[:<:]]Leaving Cert[[:>:]]/Leaving_Cert/g;
s/[[:<:]]judicial commission[[:>:]]/judicial_commission/g;
s/[[:<:]]Nassau Inter-County Express[[:>:]]/Nassau_Inter-County_Express/g;
s/[[:<:]]passed on[[:>:]]/passed_on/g;
s/[[:<:]]cut from[[:>:]]/cut_from/g;
s/[[:<:]]Channeled Scablands[[:>:]]/Channeled_Scablands/g;
s/[[:<:]]Malcolm Bradbury[[:>:]]/Malcolm_Bradbury/g;
s/[[:<:]]respiratory muscles[[:>:]]/respiratory_muscles/g;
s/[[:<:]]World Group[[:>:]]/World_Group/g;
s/[[:<:]]Alexei Mikhailovich[[:>:]]/Alexei_Mikhailovich/g;
s/[[:<:]]Water Management[[:>:]]/Water_Management/g;
s/[[:<:]]bout via[[:>:]]/bout_via/g;
s/[[:<:]]drumming duties[[:>:]]/drumming_duties/g;
s/[[:<:]]support up to[[:>:]]/support_up_to/g;
s/[[:<:]]no substantial[[:>:]]/no_substantial/g;
s/[[:<:]]two extra[[:>:]]/two_extra/g;
s/[[:<:]]Adventure Gamers[[:>:]]/Adventure_Gamers/g;
s/[[:<:]]at hooker[[:>:]]/at_hooker/g;
s/[[:<:]]Notitia Episcopatuum[[:>:]]/Notitia_Episcopatuum/g;
s/[[:<:]]both genders[[:>:]]/both_genders/g;
s/[[:<:]]The first song[[:>:]]/The_first_song/g;
s/[[:<:]]evangelistic work[[:>:]]/evangelistic_work/g;
s/[[:<:]]Little Shop[[:>:]]/Little_Shop/g;
s/[[:<:]]learn to[[:>:]]/learn_to/g;
s/[[:<:]]the highlands[[:>:]]/the_highlands/g;
s/[[:<:]]predicated on[[:>:]]/predicated_on/g;
s/[[:<:]]Ladybower Reservoir[[:>:]]/Ladybower_Reservoir/g;
s/[[:<:]]Nick Lowe[[:>:]]/Nick_Lowe/g;
s/[[:<:]]Qualification Tournament[[:>:]]/Qualification_Tournament/g;
s/[[:<:]]households watching[[:>:]]/households_watching/g;
s/[[:<:]]Itzhak Perlman[[:>:]]/Itzhak_Perlman/g;
s/[[:<:]]Tous les[[:>:]]/Tous_les/g;
s/[[:<:]]Dhaulagiri Zone[[:>:]]/Dhaulagiri_Zone/g;
s/[[:<:]]The southernmost[[:>:]]/The_southernmost/g;
s/[[:<:]]Monoclonal antibodies[[:>:]]/Monoclonal_antibodies/g;
s/[[:<:]]Glitch Mob[[:>:]]/Glitch_Mob/g;
s/[[:<:]]what was happening[[:>:]]/what_was_happening/g;
s/[[:<:]]baal teshuva[[:>:]]/baal_teshuva/g;
s/[[:<:]]Multiple studies[[:>:]]/Multiple_studies/g;
s/[[:<:]]The Venetian[[:>:]]/The_Venetian/g;
s/[[:<:]]tidal waves[[:>:]]/tidal_waves/g;
s/[[:<:]]mastermind behind[[:>:]]/mastermind_behind/g;
s/[[:<:]]fossil footprints[[:>:]]/fossil_footprints/g;
s/[[:<:]]his murder[[:>:]]/his_murder/g;
s/[[:<:]]La Niña[[:>:]]/La_Niña/g;
s/[[:<:]]Mi irabawi[[:>:]]/Mi_irabawi/g;
s/[[:<:]]take time off[[:>:]]/take_time_off/g;
s/[[:<:]]Savonlinna Opera Festival[[:>:]]/Savonlinna_Opera_Festival/g;
s/[[:<:]]Nicolas Soult[[:>:]]/Nicolas_Soult/g;
s/[[:<:]]swath of[[:>:]]/swath_of/g;
s/[[:<:]]Sarath Kumar[[:>:]]/Sarath_Kumar/g;
s/[[:<:]]rising to[[:>:]]/rising_to/g;
s/[[:<:]]rotary converters[[:>:]]/rotary_converters/g;
s/[[:<:]]his innocence[[:>:]]/his_innocence/g;
s/[[:<:]]St Anselm[[:>:]]/St_Anselm/g;
s/[[:<:]]They subsequently[[:>:]]/They_subsequently/g;
s/[[:<:]]xeroderma pigmentosum[[:>:]]/xeroderma_pigmentosum/g;
s/[[:<:]]Pittsburgh Pipers[[:>:]]/Pittsburgh_Pipers/g;
s/[[:<:]]synthetic rubber[[:>:]]/synthetic_rubber/g;
s/[[:<:]]reacted negatively to[[:>:]]/reacted_negatively_to/g;
s/[[:<:]]Teen Vogue[[:>:]]/Teen_Vogue/g;
s/[[:<:]]Roast Beef[[:>:]]/Roast_Beef/g;
s/[[:<:]]Morgan who[[:>:]]/Morgan_who/g;
s/[[:<:]]Hebrew name[[:>:]]/Hebrew_name/g;
s/[[:<:]]apologizing for[[:>:]]/apologizing_for/g;
s/[[:<:]]Alma Ata[[:>:]]/Alma_Ata/g;
s/[[:<:]]All-Big East[[:>:]]/All-Big_East/g;
s/[[:<:]]R $297.00 respectively[[:>:]]/R_$297.00_respectively/g;
s/[[:<:]]Current Affairs[[:>:]]/Current_Affairs/g;
s/[[:<:]]the fields of[[:>:]]/the_fields_of/g;
s/[[:<:]]Head coach[[:>:]]/Head_coach/g;
s/[[:<:]]Fundamental Orders[[:>:]]/Fundamental_Orders/g;
s/[[:<:]]daughter Dorothy[[:>:]]/daughter_Dorothy/g;
s/[[:<:]]the two-year middle[[:>:]]/the_two-year_middle/g;
s/[[:<:]]Galleria Borghese[[:>:]]/Galleria_Borghese/g;
s/[[:<:]]how long[[:>:]]/how_long/g;
s/[[:<:]]Fabrizio Miccoli[[:>:]]/Fabrizio_Miccoli/g;
s/[[:<:]]Osteopathic Association[[:>:]]/Osteopathic_Association/g;
s/[[:<:]]drops to[[:>:]]/drops_to/g;
s/[[:<:]]Will Always[[:>:]]/Will_Always/g;
s/[[:<:]]State University OSU[[:>:]]/State_University_OSU/g;
s/[[:<:]]A Voyage[[:>:]]/A_Voyage/g;
s/[[:<:]]Public Integrity[[:>:]]/Public_Integrity/g;
s/[[:<:]]was a Croatian[[:>:]]/was_a_Croatian/g;
s/[[:<:]]Direct Democracy[[:>:]]/Direct_Democracy/g;
s/[[:<:]]Memorial Tollway[[:>:]]/Memorial_Tollway/g;
s/[[:<:]]Kenny Burrell[[:>:]]/Kenny_Burrell/g;
s/[[:<:]]two competitors[[:>:]]/two_competitors/g;
s/[[:<:]]Wound Badge[[:>:]]/Wound_Badge/g;
s/[[:<:]]a duel[[:>:]]/a_duel/g;
s/[[:<:]]Dante Alighieri[[:>:]]/Dante_Alighieri/g;
s/[[:<:]]World Summit[[:>:]]/World_Summit/g;
s/[[:<:]]and bassist[[:>:]]/and_bassist/g;
s/[[:<:]]Brees completed[[:>:]]/Brees_completed/g;
s/[[:<:]]Red Crow[[:>:]]/Red_Crow/g;
s/[[:<:]]tin miners[[:>:]]/tin_miners/g;
s/[[:<:]]Rookery Nook[[:>:]]/Rookery_Nook/g;
s/[[:<:]]signed for[[:>:]]/signed_for/g;
s/[[:<:]]State Hermitage[[:>:]]/State_Hermitage/g;
s/[[:<:]]the skies[[:>:]]/the_skies/g;
s/[[:<:]]Cambyses II[[:>:]]/Cambyses_II/g;
s/[[:<:]]े ट[[:>:]]/े_ट/g;
s/[[:<:]]decorations are[[:>:]]/decorations_are/g;
s/[[:<:]]Zhenguo Circuit 鎮國[[:>:]]/Zhenguo_Circuit_鎮國/g;
s/[[:<:]]MidAmerican Energy[[:>:]]/MidAmerican_Energy/g;
s/[[:<:]]smart TVs[[:>:]]/smart_TVs/g;
s/[[:<:]]the pitch[[:>:]]/the_pitch/g;
s/[[:<:]]Middleweight Champion[[:>:]]/Middleweight_Champion/g;
s/[[:<:]]Ap Lei Chau[[:>:]]/Ap_Lei_Chau/g;
s/[[:<:]]joint statement[[:>:]]/joint_statement/g;
s/[[:<:]]20th Street[[:>:]]/20th_Street/g;
s/[[:<:]]Attitude Era[[:>:]]/Attitude_Era/g;
s/[[:<:]]civil liberties[[:>:]]/civil_liberties/g;
s/[[:<:]]National Enquirer[[:>:]]/National_Enquirer/g;
s/[[:<:]]finish as runners-up[[:>:]]/finish_as_runners-up/g;
s/[[:<:]]any specific[[:>:]]/any_specific/g;
s/[[:<:]]coordination complexes[[:>:]]/coordination_complexes/g;
s/[[:<:]]the election with[[:>:]]/the_election_with/g;
s/[[:<:]]Satpura Range[[:>:]]/Satpura_Range/g;
s/[[:<:]]Bart and Lisa[[:>:]]/Bart_and_Lisa/g;
s/[[:<:]]Pompano Beach[[:>:]]/Pompano_Beach/g;
s/[[:<:]]the actual[[:>:]]/the_actual/g;
s/[[:<:]]Hittite Empire[[:>:]]/Hittite_Empire/g;
s/[[:<:]]Free Gaza Movement[[:>:]]/Free_Gaza_Movement/g;
s/[[:<:]]Fritz Kreisler[[:>:]]/Fritz_Kreisler/g;
s/[[:<:]]Great Heathen Army[[:>:]]/Great_Heathen_Army/g;
s/[[:<:]]Endre Ady[[:>:]]/Endre_Ady/g;
s/[[:<:]]Justyna Steczkowska[[:>:]]/Justyna_Steczkowska/g;
s/[[:<:]]keeping track[[:>:]]/keeping_track/g;
s/[[:<:]]a murderer[[:>:]]/a_murderer/g;
s/[[:<:]]is a Somali[[:>:]]/is_a_Somali/g;
s/[[:<:]]Atlantic Avenue[[:>:]]/Atlantic_Avenue/g;
s/[[:<:]]mortal world[[:>:]]/mortal_world/g;
s/[[:<:]]an industrial[[:>:]]/an_industrial/g;
s/[[:<:]]the Heritage Foundation[[:>:]]/the_Heritage_Foundation/g;
s/[[:<:]]Apopka Florida[[:>:]]/Apopka_Florida/g;
s/[[:<:]]would soon be[[:>:]]/would_soon_be/g;
s/[[:<:]]the murder scene[[:>:]]/the_murder_scene/g;
s/[[:<:]]Heltah Skeltah[[:>:]]/Heltah_Skeltah/g;
s/[[:<:]]wild mushrooms[[:>:]]/wild_mushrooms/g;
s/[[:<:]]du Pré[[:>:]]/du_Pré/g;
s/[[:<:]]Keke Palmer[[:>:]]/Keke_Palmer/g;
s/[[:<:]]broken nose[[:>:]]/broken_nose/g;
s/[[:<:]]Gianfranco Fini[[:>:]]/Gianfranco_Fini/g;
s/[[:<:]]Jim Keltner[[:>:]]/Jim_Keltner/g;
s/[[:<:]]Davey Richards[[:>:]]/Davey_Richards/g;
s/[[:<:]]mathematical equations[[:>:]]/mathematical_equations/g;
s/[[:<:]]Commonwealth Foundation[[:>:]]/Commonwealth_Foundation/g;
s/[[:<:]]family Scissurellidae[[:>:]]/family_Scissurellidae/g;
s/[[:<:]]lowland areas[[:>:]]/lowland_areas/g;
s/[[:<:]]Inducted into[[:>:]]/Inducted_into/g;
s/[[:<:]]administrative personnel[[:>:]]/administrative_personnel/g;
s/[[:<:]]would generally be[[:>:]]/would_generally_be/g;
s/[[:<:]]Borough Alaska[[:>:]]/Borough_Alaska/g;
s/[[:<:]]brine shrimp[[:>:]]/brine_shrimp/g;
s/[[:<:]]heated arguments[[:>:]]/heated_arguments/g;
s/[[:<:]]agricultural labourers[[:>:]]/agricultural_labourers/g;
s/[[:<:]]a vast[[:>:]]/a_vast/g;
s/[[:<:]]in the 1976[[:>:]]/in_the_1976/g;
s/[[:<:]]Flemington Racecourse[[:>:]]/Flemington_Racecourse/g;
s/[[:<:]]Baronetcy of[[:>:]]/Baronetcy_of/g;
s/[[:<:]]Lord Louis Mountbatten[[:>:]]/Lord_Louis_Mountbatten/g;
s/[[:<:]]distorted guitar[[:>:]]/distorted_guitar/g;
s/[[:<:]]Bricklayers Arms[[:>:]]/Bricklayers_Arms/g;
s/[[:<:]]Birkenfeld district[[:>:]]/Birkenfeld_district/g;
s/[[:<:]]grow vegetables[[:>:]]/grow_vegetables/g;
s/[[:<:]]Slate Magazine[[:>:]]/Slate_Magazine/g;
s/[[:<:]]trimethoprim sulfamethoxazole[[:>:]]/trimethoprim_sulfamethoxazole/g;
s/[[:<:]]a waiver[[:>:]]/a_waiver/g;
s/[[:<:]]Novi Beograd[[:>:]]/Novi_Beograd/g;
s/[[:<:]]reflecting on[[:>:]]/reflecting_on/g;
s/[[:<:]]Between 1968[[:>:]]/Between_1968/g;
s/[[:<:]]Hamilton Spectator[[:>:]]/Hamilton_Spectator/g;
s/[[:<:]]prepares to[[:>:]]/prepares_to/g;
s/[[:<:]]collections including[[:>:]]/collections_including/g;
s/[[:<:]]laid out for[[:>:]]/laid_out_for/g;
s/[[:<:]]moist forest[[:>:]]/moist_forest/g;
s/[[:<:]]fabulously wealthy[[:>:]]/fabulously_wealthy/g;
s/[[:<:]]Fourteen teams[[:>:]]/Fourteen_teams/g;
s/[[:<:]]was destroyed on[[:>:]]/was_destroyed_on/g;
s/[[:<:]]Hải Phòng[[:>:]]/Hải_Phòng/g;
s/[[:<:]]her right leg[[:>:]]/her_right_leg/g;
s/[[:<:]]a family of[[:>:]]/a_family_of/g;
s/[[:<:]]Countess Palatine[[:>:]]/Countess_Palatine/g;
s/[[:<:]]Ynys Môn[[:>:]]/Ynys_Môn/g;
s/[[:<:]]Westminster Choir[[:>:]]/Westminster_Choir/g;
s/[[:<:]]the Pleiades[[:>:]]/the_Pleiades/g;
s/[[:<:]]charging station[[:>:]]/charging_station/g;
s/[[:<:]]Attorneys General[[:>:]]/Attorneys_General/g;
s/[[:<:]]Saint James[[:>:]]/Saint_James/g;
s/[[:<:]]general anesthesia[[:>:]]/general_anesthesia/g;
s/[[:<:]]cold-blooded murder[[:>:]]/cold-blooded_murder/g;
s/[[:<:]]Adam Clayton[[:>:]]/Adam_Clayton/g;
s/[[:<:]]mentally impaired[[:>:]]/mentally_impaired/g;
s/[[:<:]]Research Lab[[:>:]]/Research_Lab/g;
s/[[:<:]]Mazhabi Sikhs[[:>:]]/Mazhabi_Sikhs/g;
s/[[:<:]]the reaction mixture[[:>:]]/the_reaction_mixture/g;
s/[[:<:]]the church[[:>:]]/the_church/g;
s/[[:<:]]Curb Your Enthusiasm[[:>:]]/Curb_Your_Enthusiasm/g;
s/[[:<:]]Dallas Mavericks[[:>:]]/Dallas_Mavericks/g;
s/[[:<:]]Heyting algebra[[:>:]]/Heyting_algebra/g;
s/[[:<:]]before later joining[[:>:]]/before_later_joining/g;
s/[[:<:]]acts on[[:>:]]/acts_on/g;
s/[[:<:]]CFDA Vogue[[:>:]]/CFDA_Vogue/g;
s/[[:<:]]polygamous marriages[[:>:]]/polygamous_marriages/g;
s/[[:<:]]Cindy Crawford[[:>:]]/Cindy_Crawford/g;
s/[[:<:]]འ ི་[[:>:]]/འ_ི་/g;
s/[[:<:]]report card[[:>:]]/report_card/g;
s/[[:<:]]Le roi[[:>:]]/Le_roi/g;
s/[[:<:]]599 GTB[[:>:]]/599_GTB/g;
s/[[:<:]]and research activities[[:>:]]/and_research_activities/g;
s/[[:<:]]Edna Krabappel[[:>:]]/Edna_Krabappel/g;
s/[[:<:]]biological weapon[[:>:]]/biological_weapon/g;
s/[[:<:]]Edith Sitwell[[:>:]]/Edith_Sitwell/g;
s/[[:<:]]Skinny Puppy[[:>:]]/Skinny_Puppy/g;
s/[[:<:]]leads into[[:>:]]/leads_into/g;
s/[[:<:]]Lindsey district[[:>:]]/Lindsey_district/g;
s/[[:<:]]we suppose[[:>:]]/we_suppose/g;
s/[[:<:]]60 minutes[[:>:]]/60_minutes/g;
s/[[:<:]]orders her to[[:>:]]/orders_her_to/g;
s/[[:<:]]comes into[[:>:]]/comes_into/g;
s/[[:<:]]the Colombo Plan[[:>:]]/the_Colombo_Plan/g;
s/[[:<:]]20H 20Lienhard[[:>:]]/20H_20Lienhard/g;
s/[[:<:]]In 1613[[:>:]]/In_1613/g;
s/[[:<:]]Ernst Lubitsch[[:>:]]/Ernst_Lubitsch/g;
s/[[:<:]]its tributary[[:>:]]/its_tributary/g;
s/[[:<:]]clips from[[:>:]]/clips_from/g;
s/[[:<:]]Seattle Mariners[[:>:]]/Seattle_Mariners/g;
s/[[:<:]]charitable causes[[:>:]]/charitable_causes/g;
s/[[:<:]]Confucianism Taoism[[:>:]]/Confucianism_Taoism/g;
s/[[:<:]]brought prosperity[[:>:]]/brought_prosperity/g;
s/[[:<:]]Air Express[[:>:]]/Air_Express/g;
s/[[:<:]]closeness to[[:>:]]/closeness_to/g;
s/[[:<:]]greater honeyguide[[:>:]]/greater_honeyguide/g;
s/[[:<:]]survived by[[:>:]]/survived_by/g;
s/[[:<:]]natural satellites[[:>:]]/natural_satellites/g;
s/[[:<:]]at Burnley[[:>:]]/at_Burnley/g;
s/[[:<:]]Del Mastro[[:>:]]/Del_Mastro/g;
s/[[:<:]]400 feet[[:>:]]/400_feet/g;
s/[[:<:]]Guest Conductor[[:>:]]/Guest_Conductor/g;
s/[[:<:]]The vehicle[[:>:]]/The_vehicle/g;
s/[[:<:]]Fazlul Haque[[:>:]]/Fazlul_Haque/g;
s/[[:<:]]Perfection of Wisdom[[:>:]]/Perfection_of_Wisdom/g;
s/[[:<:]]a platoon[[:>:]]/a_platoon/g;
s/[[:<:]]three gradings given[[:>:]]/three_gradings_given/g;
s/[[:<:]]Marawi City[[:>:]]/Marawi_City/g;
s/[[:<:]]Scott Pilgrim[[:>:]]/Scott_Pilgrim/g;
s/[[:<:]]scoring 13[[:>:]]/scoring_13/g;
s/[[:<:]]Adrian Willaert[[:>:]]/Adrian_Willaert/g;
s/[[:<:]]recruitment of[[:>:]]/recruitment_of/g;
s/[[:<:]]Dejan Lovren[[:>:]]/Dejan_Lovren/g;
s/[[:<:]]Walled Lake[[:>:]]/Walled_Lake/g;
s/[[:<:]]AAMI Park[[:>:]]/AAMI_Park/g;
s/[[:<:]]Mountstuart Elphinstone[[:>:]]/Mountstuart_Elphinstone/g;
s/[[:<:]]holding that[[:>:]]/holding_that/g;
s/[[:<:]]raising awareness[[:>:]]/raising_awareness/g;
s/[[:<:]]less skilled[[:>:]]/less_skilled/g;
s/[[:<:]]Charlie Chan[[:>:]]/Charlie_Chan/g;
s/[[:<:]]a front for[[:>:]]/a_front_for/g;
s/[[:<:]]RNA and DNA[[:>:]]/RNA_and_DNA/g;
s/[[:<:]]Stonewall Riots[[:>:]]/Stonewall_Riots/g;
s/[[:<:]]Bob Gainey[[:>:]]/Bob_Gainey/g;
s/[[:<:]]Mystic Seaport[[:>:]]/Mystic_Seaport/g;
s/[[:<:]]West Was[[:>:]]/West_Was/g;
s/[[:<:]]Earth s[[:>:]]/Earth_s/g;
s/[[:<:]]Ski jumping[[:>:]]/Ski_jumping/g;
s/[[:<:]]My Voice[[:>:]]/My_Voice/g;
s/[[:<:]]Helmut Zemo[[:>:]]/Helmut_Zemo/g;
s/[[:<:]]Strategic Missile[[:>:]]/Strategic_Missile/g;
s/[[:<:]]prepare him for[[:>:]]/prepare_him_for/g;
s/[[:<:]]Broadcast Center[[:>:]]/Broadcast_Center/g;
s/[[:<:]]and General Dynamics[[:>:]]/and_General_Dynamics/g;
s/[[:<:]]NFL season[[:>:]]/NFL_season/g;
s/[[:<:]]longtime collaborators[[:>:]]/longtime_collaborators/g;
s/[[:<:]]van Loo[[:>:]]/van_Loo/g;
s/[[:<:]]marginalized groups[[:>:]]/marginalized_groups/g;
s/[[:<:]]Art Direction[[:>:]]/Art_Direction/g;
s/[[:<:]]Most Popular Newcomer[[:>:]]/Most_Popular_Newcomer/g;
s/[[:<:]]Population 2013 est[[:>:]]/Population_2013_est/g;
s/[[:<:]]an editorial[[:>:]]/an_editorial/g;
s/[[:<:]]Philip Seymour Hoffman[[:>:]]/Philip_Seymour_Hoffman/g;
s/[[:<:]]Teenage Fanclub[[:>:]]/Teenage_Fanclub/g;
s/[[:<:]]Publisher M H[[:>:]]/Publisher_M_H/g;
s/[[:<:]]the butt of[[:>:]]/the_butt_of/g;
s/[[:<:]]the area that[[:>:]]/the_area_that/g;
s/[[:<:]]just aft[[:>:]]/just_aft/g;
s/[[:<:]]commercial vehicles[[:>:]]/commercial_vehicles/g;
s/[[:<:]]Blondie s[[:>:]]/Blondie_s/g;
s/[[:<:]]basketball competitions[[:>:]]/basketball_competitions/g;
s/[[:<:]]Parachrostiinae 1867 1-136[[:>:]]/Parachrostiinae_1867_1-136/g;
s/[[:<:]]Tonbridge and Malling[[:>:]]/Tonbridge_and_Malling/g;
s/[[:<:]]Usha Uthup[[:>:]]/Usha_Uthup/g;
s/[[:<:]]Daimler Fleetline[[:>:]]/Daimler_Fleetline/g;
s/[[:<:]]Sydney Sixers[[:>:]]/Sydney_Sixers/g;
s/[[:<:]]40th minute[[:>:]]/40th_minute/g;
s/[[:<:]]done via[[:>:]]/done_via/g;
s/[[:<:]]and engineered by[[:>:]]/and_engineered_by/g;
s/[[:<:]]thirteenth season[[:>:]]/thirteenth_season/g;
s/[[:<:]]Pharmaceutical Sciences[[:>:]]/Pharmaceutical_Sciences/g;
s/[[:<:]]contributions towards[[:>:]]/contributions_towards/g;
s/[[:<:]]an EF3[[:>:]]/an_EF3/g;
s/[[:<:]]hard line[[:>:]]/hard_line/g;
s/[[:<:]]Antonov An-24[[:>:]]/Antonov_An-24/g;
s/[[:<:]]Ship Island[[:>:]]/Ship_Island/g;
s/[[:<:]]trade unions[[:>:]]/trade_unions/g;
s/[[:<:]]Eddie Guerrero[[:>:]]/Eddie_Guerrero/g;
s/[[:<:]]A penumbral[[:>:]]/A_penumbral/g;
s/[[:<:]]a bribe[[:>:]]/a_bribe/g;
s/[[:<:]]South Waziristan[[:>:]]/South_Waziristan/g;
s/[[:<:]]portrait photography[[:>:]]/portrait_photography/g;
s/[[:<:]]Choral Festival[[:>:]]/Choral_Festival/g;
s/[[:<:]]Southern California[[:>:]]/Southern_California/g;
s/[[:<:]]Hockey East[[:>:]]/Hockey_East/g;
s/[[:<:]]No 51[[:>:]]/No_51/g;
s/[[:<:]]Sharni Vinson[[:>:]]/Sharni_Vinson/g;
s/[[:<:]]trium liberorum[[:>:]]/trium_liberorum/g;
s/[[:<:]]will probably[[:>:]]/will_probably/g;
s/[[:<:]]prelate who[[:>:]]/prelate_who/g;
s/[[:<:]]north London[[:>:]]/north_London/g;
s/[[:<:]]The relationship of[[:>:]]/The_relationship_of/g;
s/[[:<:]]would write[[:>:]]/would_write/g;
s/[[:<:]]Eventually he[[:>:]]/Eventually_he/g;
s/[[:<:]]indigenous groups[[:>:]]/indigenous_groups/g;
s/[[:<:]]Indian classical[[:>:]]/Indian_classical/g;
s/[[:<:]]constitutional amendment[[:>:]]/constitutional_amendment/g;
s/[[:<:]]physical abuse[[:>:]]/physical_abuse/g;
s/[[:<:]]bombing missions[[:>:]]/bombing_missions/g;
s/[[:<:]]In 1776[[:>:]]/In_1776/g;
s/[[:<:]]Saturday night[[:>:]]/Saturday_night/g;
s/[[:<:]]Vajrayana Buddhism[[:>:]]/Vajrayana_Buddhism/g;
s/[[:<:]]Glastonbury Festival[[:>:]]/Glastonbury_Festival/g;
s/[[:<:]]Galena Illinois[[:>:]]/Galena_Illinois/g;
s/[[:<:]]astroturf pitch[[:>:]]/astroturf_pitch/g;
s/[[:<:]]Mount Barker[[:>:]]/Mount_Barker/g;
s/[[:<:]]Machine Readable[[:>:]]/Machine_Readable/g;
s/[[:<:]]Dąbrowa Biskupia[[:>:]]/Dąbrowa_Biskupia/g;
s/[[:<:]]central Poland[[:>:]]/central_Poland/g;
s/[[:<:]]Small Craft[[:>:]]/Small_Craft/g;
s/[[:<:]]Yoo Jae-suk[[:>:]]/Yoo_Jae-suk/g;
s/[[:<:]]Paradise Garage[[:>:]]/Paradise_Garage/g;
s/[[:<:]]two towns[[:>:]]/two_towns/g;
s/[[:<:]]laser diodes[[:>:]]/laser_diodes/g;
s/[[:<:]]The release of[[:>:]]/The_release_of/g;
s/[[:<:]]Krisztián Sárneczky[[:>:]]/Krisztián_Sárneczky/g;
s/[[:<:]]Hrvatske ceste[[:>:]]/Hrvatske_ceste/g;
s/[[:<:]]classify it as[[:>:]]/classify_it_as/g;
s/[[:<:]]Ancrene Wisse[[:>:]]/Ancrene_Wisse/g;
s/[[:<:]]et de sculpture[[:>:]]/et_de_sculpture/g;
s/[[:<:]]is a 1978[[:>:]]/is_a_1978/g;
s/[[:<:]]evaluated as[[:>:]]/evaluated_as/g;
s/[[:<:]]Pharmaceutical Benefits[[:>:]]/Pharmaceutical_Benefits/g;
s/[[:<:]]a massacre of[[:>:]]/a_massacre_of/g;
s/[[:<:]]Special Areas[[:>:]]/Special_Areas/g;
s/[[:<:]]Gaozong s[[:>:]]/Gaozong_s/g;
s/[[:<:]]burden on[[:>:]]/burden_on/g;
s/[[:<:]]instructions are[[:>:]]/instructions_are/g;
s/[[:<:]]Long Depression[[:>:]]/Long_Depression/g;
s/[[:<:]]the Dniester[[:>:]]/the_Dniester/g;
s/[[:<:]]highly symbolic[[:>:]]/highly_symbolic/g;
s/[[:<:]]Rassemblement Démocratique[[:>:]]/Rassemblement_Démocratique/g;
s/[[:<:]]a three-piece[[:>:]]/a_three-piece/g;
s/[[:<:]]Unborn Child[[:>:]]/Unborn_Child/g;
s/[[:<:]]their ninth[[:>:]]/their_ninth/g;
s/[[:<:]]Dash 7[[:>:]]/Dash_7/g;
s/[[:<:]]Falaise Gap[[:>:]]/Falaise_Gap/g;
s/[[:<:]]local traffic[[:>:]]/local_traffic/g;
s/[[:<:]]In 1739[[:>:]]/In_1739/g;
s/[[:<:]]an action for[[:>:]]/an_action_for/g;
s/[[:<:]]vocal trio[[:>:]]/vocal_trio/g;
s/[[:<:]]cult classics[[:>:]]/cult_classics/g;
s/[[:<:]]Jolly Boys[[:>:]]/Jolly_Boys/g;
s/[[:<:]]Iraqi officials[[:>:]]/Iraqi_officials/g;
s/[[:<:]]Navigation Company[[:>:]]/Navigation_Company/g;
s/[[:<:]]Les Contes[[:>:]]/Les_Contes/g;
s/[[:<:]]an Italian[[:>:]]/an_Italian/g;
s/[[:<:]]tetrastyle portico[[:>:]]/tetrastyle_portico/g;
s/[[:<:]]Mink Stole[[:>:]]/Mink_Stole/g;
s/[[:<:]]Parañaque City[[:>:]]/Parañaque_City/g;
s/[[:<:]]neutrophil elastase[[:>:]]/neutrophil_elastase/g;
s/[[:<:]]at Bangalore[[:>:]]/at_Bangalore/g;
s/[[:<:]]Debby Boone[[:>:]]/Debby_Boone/g;
s/[[:<:]]Fra Angelico[[:>:]]/Fra_Angelico/g;
s/[[:<:]]Alicante Spain[[:>:]]/Alicante_Spain/g;
s/[[:<:]]was opened[[:>:]]/was_opened/g;
s/[[:<:]]Mike Holmgren[[:>:]]/Mike_Holmgren/g;
s/[[:<:]]Nationalist Movement[[:>:]]/Nationalist_Movement/g;
s/[[:<:]]wicker baskets[[:>:]]/wicker_baskets/g;
s/[[:<:]]59 88[[:>:]]/59_88/g;
s/[[:<:]]Chief Government Whip[[:>:]]/Chief_Government_Whip/g;
s/[[:<:]]Vowel Shift[[:>:]]/Vowel_Shift/g;
s/[[:<:]]nearly completed[[:>:]]/nearly_completed/g;
s/[[:<:]]battles including[[:>:]]/battles_including/g;
s/[[:<:]]welded steel[[:>:]]/welded_steel/g;
s/[[:<:]]sports society[[:>:]]/sports_society/g;
s/[[:<:]]contributed substantially to[[:>:]]/contributed_substantially_to/g;
s/[[:<:]]secondary alcohols[[:>:]]/secondary_alcohols/g;
s/[[:<:]]Megaptera novaeangliae[[:>:]]/Megaptera_novaeangliae/g;
s/[[:<:]]his short life[[:>:]]/his_short_life/g;
s/[[:<:]]in the Nord[[:>:]]/in_the_Nord/g;
s/[[:<:]]Sufian District Shabestar[[:>:]]/Sufian_District_Shabestar/g;
s/[[:<:]]nothing new[[:>:]]/nothing_new/g;
s/[[:<:]]the banner of[[:>:]]/the_banner_of/g;
s/[[:<:]]Red Planet[[:>:]]/Red_Planet/g;
s/[[:<:]]Somaly Mam[[:>:]]/Somaly_Mam/g;
s/[[:<:]]By 1989[[:>:]]/By_1989/g;
s/[[:<:]]Mikhail Saakashvili[[:>:]]/Mikhail_Saakashvili/g;
s/[[:<:]]Graduate School[[:>:]]/Graduate_School/g;
s/[[:<:]]All-Academic Team[[:>:]]/All-Academic_Team/g;
s/[[:<:]]relative importance[[:>:]]/relative_importance/g;
s/[[:<:]]She authored[[:>:]]/She_authored/g;
s/[[:<:]]an intermediary[[:>:]]/an_intermediary/g;
s/[[:<:]]SV Elversberg[[:>:]]/SV_Elversberg/g;
s/[[:<:]]imitations of[[:>:]]/imitations_of/g;
s/[[:<:]]Stephen Baxter[[:>:]]/Stephen_Baxter/g;
s/[[:<:]]peppercorn rent[[:>:]]/peppercorn_rent/g;
s/[[:<:]]vertical shaft[[:>:]]/vertical_shaft/g;
s/[[:<:]]which dominates[[:>:]]/which_dominates/g;
s/[[:<:]]took a turn[[:>:]]/took_a_turn/g;
s/[[:<:]]Nuremberg trials[[:>:]]/Nuremberg_trials/g;
s/[[:<:]]Amélie Mauresmo[[:>:]]/Amélie_Mauresmo/g;
s/[[:<:]]G Karachkina[[:>:]]/G_Karachkina/g;
s/[[:<:]]the bridge s[[:>:]]/the_bridge_s/g;
s/[[:<:]]moved elsewhere[[:>:]]/moved_elsewhere/g;
s/[[:<:]]in this war[[:>:]]/in_this_war/g;
s/[[:<:]]Francesca Annis[[:>:]]/Francesca_Annis/g;
s/[[:<:]]Le Verrier[[:>:]]/Le_Verrier/g;
s/[[:<:]]was overhauled[[:>:]]/was_overhauled/g;
s/[[:<:]]would start[[:>:]]/would_start/g;
s/[[:<:]]the Rock Island[[:>:]]/the_Rock_Island/g;
s/[[:<:]]an affordable[[:>:]]/an_affordable/g;
s/[[:<:]]breakfast and lunch[[:>:]]/breakfast_and_lunch/g;
s/[[:<:]]a two hour[[:>:]]/a_two_hour/g;
s/[[:<:]]Gröbner bases[[:>:]]/Gröbner_bases/g;
s/[[:<:]]Dave Simpson[[:>:]]/Dave_Simpson/g;
s/[[:<:]]Thutmose IV[[:>:]]/Thutmose_IV/g;
s/[[:<:]]Democratic parties[[:>:]]/Democratic_parties/g;
s/[[:<:]]Burning Pestle[[:>:]]/Burning_Pestle/g;
s/[[:<:]]black tie[[:>:]]/black_tie/g;
s/[[:<:]]Miss Texas[[:>:]]/Miss_Texas/g;
s/[[:<:]]Landscape Architecture[[:>:]]/Landscape_Architecture/g;
s/[[:<:]]Tennis Club[[:>:]]/Tennis_Club/g;
s/[[:<:]]Quintin Hogg[[:>:]]/Quintin_Hogg/g;
s/[[:<:]]Northern Bullants[[:>:]]/Northern_Bullants/g;
s/[[:<:]]leading run-scorer[[:>:]]/leading_run-scorer/g;
s/[[:<:]]politicization of[[:>:]]/politicization_of/g;
s/[[:<:]]Valmiki Ramayana[[:>:]]/Valmiki_Ramayana/g;
s/[[:<:]]Frederick Law Olmsted[[:>:]]/Frederick_Law_Olmsted/g;
s/[[:<:]]David M[[:>:]]/David_M/g;
s/[[:<:]]million facility[[:>:]]/million_facility/g;
s/[[:<:]]Dungeons and Dragons[[:>:]]/Dungeons_and_Dragons/g;
s/[[:<:]]professional careers[[:>:]]/professional_careers/g;
s/[[:<:]]ভল ি উম[[:>:]]/ভল_ি_উম/g;
s/[[:<:]]Rafik Hariri[[:>:]]/Rafik_Hariri/g;
s/[[:<:]]geographic location[[:>:]]/geographic_location/g;
s/[[:<:]]Jan Hus[[:>:]]/Jan_Hus/g;
s/[[:<:]]From 1909[[:>:]]/From_1909/g;
s/[[:<:]]Dick Vermeil[[:>:]]/Dick_Vermeil/g;
s/[[:<:]]Howard Beach[[:>:]]/Howard_Beach/g;
s/[[:<:]]invaded Egypt[[:>:]]/invaded_Egypt/g;
s/[[:<:]]Captain EO[[:>:]]/Captain_EO/g;
s/[[:<:]]the young artist[[:>:]]/the_young_artist/g;
s/[[:<:]]Your Daddy[[:>:]]/Your_Daddy/g;
s/[[:<:]]attract females[[:>:]]/attract_females/g;
s/[[:<:]]3600 m[[:>:]]/3600_m/g;
s/[[:<:]]and hand grenades[[:>:]]/and_hand_grenades/g;
s/[[:<:]]Koo Wee Rup[[:>:]]/Koo_Wee_Rup/g;
s/[[:<:]]Moringa oleifera[[:>:]]/Moringa_oleifera/g;
s/[[:<:]]written and storyboarded[[:>:]]/written_and_storyboarded/g;
s/[[:<:]]Carbon nanotubes[[:>:]]/Carbon_nanotubes/g;
s/[[:<:]]represented Italy[[:>:]]/represented_Italy/g;
s/[[:<:]]methods are[[:>:]]/methods_are/g;
s/[[:<:]]Richard Dreyfuss[[:>:]]/Richard_Dreyfuss/g;
s/[[:<:]]Sterling Cooper[[:>:]]/Sterling_Cooper/g;
s/[[:<:]]colors are[[:>:]]/colors_are/g;
s/[[:<:]]Township is one[[:>:]]/Township_is_one/g;
s/[[:<:]]the Kansas River[[:>:]]/the_Kansas_River/g;
s/[[:<:]]described to be[[:>:]]/described_to_be/g;
s/[[:<:]]chooses one[[:>:]]/chooses_one/g;
s/[[:<:]]38 sqmi[[:>:]]/38_sqmi/g;
s/[[:<:]]a European species[[:>:]]/a_European_species/g;
s/[[:<:]]Färjestads BK[[:>:]]/Färjestads_BK/g;
s/[[:<:]]adrenaline rush[[:>:]]/adrenaline_rush/g;
s/[[:<:]]shed light on[[:>:]]/shed_light_on/g;
s/[[:<:]]advertising company[[:>:]]/advertising_company/g;
s/[[:<:]]Sweeney s[[:>:]]/Sweeney_s/g;
s/[[:<:]]Expeditionary Force[[:>:]]/Expeditionary_Force/g;
s/[[:<:]]Chris Willman[[:>:]]/Chris_Willman/g;
s/[[:<:]]co-operates with[[:>:]]/co-operates_with/g;
s/[[:<:]]a bit[[:>:]]/a_bit/g;
s/[[:<:]]has been repeatedly[[:>:]]/has_been_repeatedly/g;
s/[[:<:]]Wrestle Kingdom[[:>:]]/Wrestle_Kingdom/g;
s/[[:<:]]Megan Mullally[[:>:]]/Megan_Mullally/g;
s/[[:<:]]Eddie Redmayne[[:>:]]/Eddie_Redmayne/g;
s/[[:<:]]designed by[[:>:]]/designed_by/g;
s/[[:<:]]beta decay[[:>:]]/beta_decay/g;
s/[[:<:]]Michelle Visage[[:>:]]/Michelle_Visage/g;
s/[[:<:]]Anoop Menon[[:>:]]/Anoop_Menon/g;
s/[[:<:]]Henry A Wise[[:>:]]/Henry_A_Wise/g;
s/[[:<:]]responding to[[:>:]]/responding_to/g;
s/[[:<:]]suffices to[[:>:]]/suffices_to/g;
s/[[:<:]]malignant melanoma[[:>:]]/malignant_melanoma/g;
s/[[:<:]]chancel with[[:>:]]/chancel_with/g;
s/[[:<:]]Leinster Senior[[:>:]]/Leinster_Senior/g;
s/[[:<:]]Asbury Jukes[[:>:]]/Asbury_Jukes/g;
s/[[:<:]]Artemis Entreri[[:>:]]/Artemis_Entreri/g;
s/[[:<:]]In 1898[[:>:]]/In_1898/g;
s/[[:<:]]orbitofrontal cortex[[:>:]]/orbitofrontal_cortex/g;
s/[[:<:]]square root[[:>:]]/square_root/g;
s/[[:<:]]Kennet and Avon[[:>:]]/Kennet_and_Avon/g;
s/[[:<:]]Scott s[[:>:]]/Scott_s/g;
s/[[:<:]]α helices[[:>:]]/α_helices/g;
s/[[:<:]]Gower Champion[[:>:]]/Gower_Champion/g;
s/[[:<:]]wary of[[:>:]]/wary_of/g;
s/[[:<:]]spokesman for[[:>:]]/spokesman_for/g;
s/[[:<:]]ISO 26262[[:>:]]/ISO_26262/g;
s/[[:<:]]during peak hours[[:>:]]/during_peak_hours/g;
s/[[:<:]]in several fields[[:>:]]/in_several_fields/g;
s/[[:<:]]could resume[[:>:]]/could_resume/g;
s/[[:<:]]Twin Otters[[:>:]]/Twin_Otters/g;
s/[[:<:]]San Justo[[:>:]]/San_Justo/g;
s/[[:<:]]poet translator[[:>:]]/poet_translator/g;
s/[[:<:]]Salvadore Cammarano[[:>:]]/Salvadore_Cammarano/g;
s/[[:<:]]high casualties[[:>:]]/high_casualties/g;
s/[[:<:]]Air Assault[[:>:]]/Air_Assault/g;
s/[[:<:]]Professor of[[:>:]]/Professor_of/g;
s/[[:<:]]Bobby Tench[[:>:]]/Bobby_Tench/g;
s/[[:<:]]but never[[:>:]]/but_never/g;
s/[[:<:]]at this level[[:>:]]/at_this_level/g;
s/[[:<:]]Tamil Nadu[[:>:]]/Tamil_Nadu/g;
s/[[:<:]]known to infect[[:>:]]/known_to_infect/g;
s/[[:<:]]a mountain of[[:>:]]/a_mountain_of/g;
s/[[:<:]]Damien Dempsey[[:>:]]/Damien_Dempsey/g;
s/[[:<:]]in Dunedin[[:>:]]/in_Dunedin/g;
s/[[:<:]]Ancient Greek[[:>:]]/Ancient_Greek/g;
s/[[:<:]]Professor John[[:>:]]/Professor_John/g;
s/[[:<:]]kabuki actors[[:>:]]/kabuki_actors/g;
s/[[:<:]]Hürrem Sultan[[:>:]]/Hürrem_Sultan/g;
s/[[:<:]]in the category[[:>:]]/in_the_category/g;
s/[[:<:]]The first election[[:>:]]/The_first_election/g;
s/[[:<:]]Tu Bishvat[[:>:]]/Tu_Bishvat/g;
s/[[:<:]]de Uruguay[[:>:]]/de_Uruguay/g;
s/[[:<:]]Never Knew[[:>:]]/Never_Knew/g;
s/[[:<:]]salad bar[[:>:]]/salad_bar/g;
s/[[:<:]]Since May[[:>:]]/Since_May/g;
s/[[:<:]]Forbes magazine[[:>:]]/Forbes_magazine/g;
s/[[:<:]]a backbencher[[:>:]]/a_backbencher/g;
s/[[:<:]]20 mph[[:>:]]/20_mph/g;
s/[[:<:]]parallel bars[[:>:]]/parallel_bars/g;
s/[[:<:]]would offend[[:>:]]/would_offend/g;
s/[[:<:]]fantasizing about[[:>:]]/fantasizing_about/g;
s/[[:<:]]harmed by[[:>:]]/harmed_by/g;
s/[[:<:]]commensurate with[[:>:]]/commensurate_with/g;
s/[[:<:]]Nobel prize-winning[[:>:]]/Nobel_prize-winning/g;
s/[[:<:]]Riverside California[[:>:]]/Riverside_California/g;
s/[[:<:]]Teófilo Braga[[:>:]]/Teófilo_Braga/g;
s/[[:<:]]Dramatists Guild[[:>:]]/Dramatists_Guild/g;
s/[[:<:]]advocated that[[:>:]]/advocated_that/g;
s/[[:<:]]ி ம[[:>:]]/ி_ம/g;
s/[[:<:]]Orontes River[[:>:]]/Orontes_River/g;
s/[[:<:]]Sarah Miles[[:>:]]/Sarah_Miles/g;
s/[[:<:]]Youngstown Ohio[[:>:]]/Youngstown_Ohio/g;
s/[[:<:]]Rowan Williams[[:>:]]/Rowan_Williams/g;
s/[[:<:]]representative of[[:>:]]/representative_of/g;
s/[[:<:]]Fas Alzamora[[:>:]]/Fas_Alzamora/g;
s/[[:<:]]Clwydian Range[[:>:]]/Clwydian_Range/g;
s/[[:<:]]Brad Ausmus[[:>:]]/Brad_Ausmus/g;
s/[[:<:]]iridescent blue[[:>:]]/iridescent_blue/g;
s/[[:<:]]summer school[[:>:]]/summer_school/g;
s/[[:<:]]culled from[[:>:]]/culled_from/g;
s/[[:<:]]São Toméan[[:>:]]/São_Toméan/g;
s/[[:<:]]a twin-engined[[:>:]]/a_twin-engined/g;
s/[[:<:]]Henrik Wergeland[[:>:]]/Henrik_Wergeland/g;
s/[[:<:]]Ming court[[:>:]]/Ming_court/g;
s/[[:<:]]Frederick Gibberd[[:>:]]/Frederick_Gibberd/g;
s/[[:<:]]Shortly after[[:>:]]/Shortly_after/g;
s/[[:<:]]Worcestershire Canal[[:>:]]/Worcestershire_Canal/g;
s/[[:<:]]Soulcalibur IV[[:>:]]/Soulcalibur_IV/g;
s/[[:<:]]And you[[:>:]]/And_you/g;
s/[[:<:]]By 1850[[:>:]]/By_1850/g;
s/[[:<:]]an end-to-end[[:>:]]/an_end-to-end/g;
s/[[:<:]]geological strata[[:>:]]/geological_strata/g;
s/[[:<:]]is taken[[:>:]]/is_taken/g;
s/[[:<:]]purchased a house[[:>:]]/purchased_a_house/g;
s/[[:<:]]Dr med[[:>:]]/Dr_med/g;
s/[[:<:]]Donald Rumsfeld[[:>:]]/Donald_Rumsfeld/g;
s/[[:<:]]Verwaltungsgemeinschaft Administrative[[:>:]]/Verwaltungsgemeinschaft_Administrative/g;
s/[[:<:]]Toledo Walleye[[:>:]]/Toledo_Walleye/g;
s/[[:<:]]Mel Lastman[[:>:]]/Mel_Lastman/g;
s/[[:<:]]but died[[:>:]]/but_died/g;
s/[[:<:]]Guitar Slim[[:>:]]/Guitar_Slim/g;
s/[[:<:]]Kryvyi Rih[[:>:]]/Kryvyi_Rih/g;
s/[[:<:]]Asian records were[[:>:]]/Asian_records_were/g;
s/[[:<:]]music duo[[:>:]]/music_duo/g;
s/[[:<:]]survey work[[:>:]]/survey_work/g;
s/[[:<:]]a death penalty[[:>:]]/a_death_penalty/g;
s/[[:<:]]In 1729[[:>:]]/In_1729/g;
s/[[:<:]]public – private[[:>:]]/public_–_private/g;
s/[[:<:]]Airedale Terrier[[:>:]]/Airedale_Terrier/g;
s/[[:<:]]flowing waters[[:>:]]/flowing_waters/g;
s/[[:<:]]ethical conduct[[:>:]]/ethical_conduct/g;
s/[[:<:]]hot and often[[:>:]]/hot_and_often/g;
s/[[:<:]]County East Azerbaijan[[:>:]]/County_East_Azerbaijan/g;
s/[[:<:]]Derek Sherinian[[:>:]]/Derek_Sherinian/g;
s/[[:<:]]Léon Theremin[[:>:]]/Léon_Theremin/g;
s/[[:<:]]plays guitar[[:>:]]/plays_guitar/g;
s/[[:<:]]known popularly as[[:>:]]/known_popularly_as/g;
s/[[:<:]]Sangam period[[:>:]]/Sangam_period/g;
s/[[:<:]]Primary Care[[:>:]]/Primary_Care/g;
s/[[:<:]]Martin Rushent[[:>:]]/Martin_Rushent/g;
s/[[:<:]]regulatory issues[[:>:]]/regulatory_issues/g;
s/[[:<:]]at various[[:>:]]/at_various/g;
s/[[:<:]]Operation Barbarossa[[:>:]]/Operation_Barbarossa/g;
s/[[:<:]]Bouncing Souls[[:>:]]/Bouncing_Souls/g;
s/[[:<:]]a helicopter[[:>:]]/a_helicopter/g;
s/[[:<:]]cardiac surgery[[:>:]]/cardiac_surgery/g;
s/[[:<:]]greatly simplifies[[:>:]]/greatly_simplifies/g;
s/[[:<:]]the Decatur Staleys[[:>:]]/the_Decatur_Staleys/g;
s/[[:<:]]pro bono[[:>:]]/pro_bono/g;
s/[[:<:]]MITOS Novocherkassk[[:>:]]/MITOS_Novocherkassk/g;
s/[[:<:]]Steam Packet[[:>:]]/Steam_Packet/g;
s/[[:<:]]Land Grant[[:>:]]/Land_Grant/g;
s/[[:<:]]Bhopal Habibganj[[:>:]]/Bhopal_Habibganj/g;
s/[[:<:]]attracted over[[:>:]]/attracted_over/g;
s/[[:<:]]Single Action[[:>:]]/Single_Action/g;
s/[[:<:]]Gifted Talented[[:>:]]/Gifted_Talented/g;
s/[[:<:]]Pruszcz Gdański[[:>:]]/Pruszcz_Gdański/g;
s/[[:<:]]Capitoline Hill[[:>:]]/Capitoline_Hill/g;
s/[[:<:]]Torneo Cibernetico[[:>:]]/Torneo_Cibernetico/g;
s/[[:<:]]would ordinarily[[:>:]]/would_ordinarily/g;
s/[[:<:]]Koine Greek[[:>:]]/Koine_Greek/g;
s/[[:<:]]naval gunfire[[:>:]]/naval_gunfire/g;
s/[[:<:]]Arjen Robben[[:>:]]/Arjen_Robben/g;
s/[[:<:]]in Katowice[[:>:]]/in_Katowice/g;
s/[[:<:]]domestic helpers[[:>:]]/domestic_helpers/g;
s/[[:<:]]Ke Phool[[:>:]]/Ke_Phool/g;
s/[[:<:]]Ophichthidae worm snake[[:>:]]/Ophichthidae_worm_snake/g;
s/[[:<:]]corpore sano[[:>:]]/corpore_sano/g;
s/[[:<:]]Jacques Tati[[:>:]]/Jacques_Tati/g;
s/[[:<:]]Animal Rescue[[:>:]]/Animal_Rescue/g;
s/[[:<:]]distinct entities[[:>:]]/distinct_entities/g;
s/[[:<:]]coconut palms[[:>:]]/coconut_palms/g;
s/[[:<:]]Mille Lacs[[:>:]]/Mille_Lacs/g;
s/[[:<:]]St Moritz[[:>:]]/St_Moritz/g;
s/[[:<:]]dorsal fins[[:>:]]/dorsal_fins/g;
s/[[:<:]]two villages[[:>:]]/two_villages/g;
s/[[:<:]]area code[[:>:]]/area_code/g;
s/[[:<:]]tool and die[[:>:]]/tool_and_die/g;
s/[[:<:]]Thutmose III[[:>:]]/Thutmose_III/g;
s/[[:<:]]2400 m[[:>:]]/2400_m/g;
s/[[:<:]]Arcelor Mittal[[:>:]]/Arcelor_Mittal/g;
s/[[:<:]]a dead person[[:>:]]/a_dead_person/g;
s/[[:<:]]သ ူ[[:>:]]/သ_ူ/g;
s/[[:<:]]vanishing point[[:>:]]/vanishing_point/g;
s/[[:<:]]László Rajk[[:>:]]/László_Rajk/g;
s/[[:<:]]SpVgg Fürth[[:>:]]/SpVgg_Fürth/g;
s/[[:<:]]Thousand Faces[[:>:]]/Thousand_Faces/g;
s/[[:<:]]ပည ာ[[:>:]]/ပည_ာ/g;
s/[[:<:]]Monday morning[[:>:]]/Monday_morning/g;
s/[[:<:]]close season[[:>:]]/close_season/g;
s/[[:<:]]Caravan Park[[:>:]]/Caravan_Park/g;
s/[[:<:]]nursing care[[:>:]]/nursing_care/g;
s/[[:<:]]an admixture[[:>:]]/an_admixture/g;
s/[[:<:]]brings her to[[:>:]]/brings_her_to/g;
s/[[:<:]]In 1932[[:>:]]/In_1932/g;
s/[[:<:]]Volume 5[[:>:]]/Volume_5/g;
s/[[:<:]]exchanges between[[:>:]]/exchanges_between/g;
s/[[:<:]]Phil Collen[[:>:]]/Phil_Collen/g;
s/[[:<:]]high ratings[[:>:]]/high_ratings/g;
s/[[:<:]]only open to[[:>:]]/only_open_to/g;
s/[[:<:]]Red Electoral Alliance[[:>:]]/Red_Electoral_Alliance/g;
s/[[:<:]]In 1960[[:>:]]/In_1960/g;
s/[[:<:]]Ricky Butcher[[:>:]]/Ricky_Butcher/g;
s/[[:<:]]2013-14 season[[:>:]]/2013-14_season/g;
s/[[:<:]]Figure 2[[:>:]]/Figure_2/g;
s/[[:<:]]annexed to[[:>:]]/annexed_to/g;
s/[[:<:]]Imperial Japan[[:>:]]/Imperial_Japan/g;
s/[[:<:]]Darley Stud[[:>:]]/Darley_Stud/g;
s/[[:<:]]Slavko Kvaternik[[:>:]]/Slavko_Kvaternik/g;
s/[[:<:]]coupling rods[[:>:]]/coupling_rods/g;
s/[[:<:]]Doug Pinnick[[:>:]]/Doug_Pinnick/g;
s/[[:<:]]Steven Klein[[:>:]]/Steven_Klein/g;
s/[[:<:]]Binaca Geetmala[[:>:]]/Binaca_Geetmala/g;
s/[[:<:]]Wladimir Klitschko[[:>:]]/Wladimir_Klitschko/g;
s/[[:<:]]her then-husband[[:>:]]/her_then-husband/g;
s/[[:<:]]histone acetyltransferase[[:>:]]/histone_acetyltransferase/g;
s/[[:<:]]insertions and deletions[[:>:]]/insertions_and_deletions/g;
s/[[:<:]]ศ ู นย[[:>:]]/ศ_ู_นย/g;
s/[[:<:]]Len Cariou[[:>:]]/Len_Cariou/g;
s/[[:<:]]Recovery Program[[:>:]]/Recovery_Program/g;
s/[[:<:]]militant groups[[:>:]]/militant_groups/g;
s/[[:<:]]Real Maryland Monarchs[[:>:]]/Real_Maryland_Monarchs/g;
s/[[:<:]]Adam Dutkiewicz[[:>:]]/Adam_Dutkiewicz/g;
s/[[:<:]]meters long[[:>:]]/meters_long/g;
s/[[:<:]]Ken Doherty[[:>:]]/Ken_Doherty/g;
s/[[:<:]]Sammi Cheng[[:>:]]/Sammi_Cheng/g;
s/[[:<:]]Valentina Matviyenko[[:>:]]/Valentina_Matviyenko/g;
s/[[:<:]]Westminster Assembly[[:>:]]/Westminster_Assembly/g;
s/[[:<:]]Ficus religiosa[[:>:]]/Ficus_religiosa/g;
s/[[:<:]]metallic tints[[:>:]]/metallic_tints/g;
s/[[:<:]]high importance[[:>:]]/high_importance/g;
s/[[:<:]]Dandie Dinmont[[:>:]]/Dandie_Dinmont/g;
s/[[:<:]]mesic forests[[:>:]]/mesic_forests/g;
s/[[:<:]]These locomotives[[:>:]]/These_locomotives/g;
s/[[:<:]]By studying[[:>:]]/By_studying/g;
s/[[:<:]]stay together[[:>:]]/stay_together/g;
s/[[:<:]]pornographic content[[:>:]]/pornographic_content/g;
s/[[:<:]]happy couple[[:>:]]/happy_couple/g;
s/[[:<:]]at about 2[[:>:]]/at_about_2/g;
s/[[:<:]]in the Orne[[:>:]]/in_the_Orne/g;
s/[[:<:]]practical applications of[[:>:]]/practical_applications_of/g;
s/[[:<:]]coordinating committee[[:>:]]/coordinating_committee/g;
s/[[:<:]]boxing referee[[:>:]]/boxing_referee/g;
s/[[:<:]]freshwater lake[[:>:]]/freshwater_lake/g;
s/[[:<:]]Buffy Sainte-Marie[[:>:]]/Buffy_Sainte-Marie/g;
s/[[:<:]]Scritti Politti[[:>:]]/Scritti_Politti/g;
s/[[:<:]]voice communications[[:>:]]/voice_communications/g;
s/[[:<:]]archaeological work[[:>:]]/archaeological_work/g;
s/[[:<:]]in Wilmington[[:>:]]/in_Wilmington/g;
s/[[:<:]]zinc chloride[[:>:]]/zinc_chloride/g;
s/[[:<:]]Sluggy Freelance[[:>:]]/Sluggy_Freelance/g;
s/[[:<:]]ֹ ה[[:>:]]/ֹ_ה/g;
s/[[:<:]]Hindu deities[[:>:]]/Hindu_deities/g;
s/[[:<:]]Mircea Geoană[[:>:]]/Mircea_Geoană/g;
s/[[:<:]]Estoril Praia[[:>:]]/Estoril_Praia/g;
s/[[:<:]]El Brazo[[:>:]]/El_Brazo/g;
s/[[:<:]]Otaqvar District Langarud[[:>:]]/Otaqvar_District_Langarud/g;
s/[[:<:]]Annabella Sciorra[[:>:]]/Annabella_Sciorra/g;
s/[[:<:]]Tim LaHaye[[:>:]]/Tim_LaHaye/g;
s/[[:<:]]Captain James[[:>:]]/Captain_James/g;
s/[[:<:]]Daily Inquirer[[:>:]]/Daily_Inquirer/g;
s/[[:<:]]pelvic pain[[:>:]]/pelvic_pain/g;
s/[[:<:]]≠ 0[[:>:]]/≠_0/g;
s/[[:<:]]François Bayrou[[:>:]]/François_Bayrou/g;
s/[[:<:]]cabaret artist[[:>:]]/cabaret_artist/g;
s/[[:<:]]Konstantin Nikolayevich[[:>:]]/Konstantin_Nikolayevich/g;
s/[[:<:]]Funding School[[:>:]]/Funding_School/g;
s/[[:<:]]the destiny of[[:>:]]/the_destiny_of/g;
s/[[:<:]]silky sifaka[[:>:]]/silky_sifaka/g;
s/[[:<:]]memory bandwidth[[:>:]]/memory_bandwidth/g;
s/[[:<:]]lower level[[:>:]]/lower_level/g;
s/[[:<:]]Pine Brook[[:>:]]/Pine_Brook/g;
s/[[:<:]]18th hole[[:>:]]/18th_hole/g;
s/[[:<:]]the first pitch[[:>:]]/the_first_pitch/g;
s/[[:<:]]preventing her from[[:>:]]/preventing_her_from/g;
s/[[:<:]]negative stereotypes[[:>:]]/negative_stereotypes/g;
s/[[:<:]]Bif Naked[[:>:]]/Bif_Naked/g;
s/[[:<:]]Hold It Against[[:>:]]/Hold_It_Against/g;
s/[[:<:]]Business Insider[[:>:]]/Business_Insider/g;
s/[[:<:]]has now been[[:>:]]/has_now_been/g;
s/[[:<:]]Oak Grove[[:>:]]/Oak_Grove/g;
s/[[:<:]]Livery Companies[[:>:]]/Livery_Companies/g;
s/[[:<:]]first conceived[[:>:]]/first_conceived/g;
s/[[:<:]]financial disaster[[:>:]]/financial_disaster/g;
s/[[:<:]]Mira Mesa[[:>:]]/Mira_Mesa/g;
s/[[:<:]]metric spaces[[:>:]]/metric_spaces/g;
s/[[:<:]]takes up[[:>:]]/takes_up/g;
s/[[:<:]]the Medellín Cartel[[:>:]]/the_Medellín_Cartel/g;
s/[[:<:]]hexagonal crystal[[:>:]]/hexagonal_crystal/g;
s/[[:<:]]straight-line winds[[:>:]]/straight-line_winds/g;
s/[[:<:]]negotiation process[[:>:]]/negotiation_process/g;
s/[[:<:]]and features programing[[:>:]]/and_features_programing/g;
s/[[:<:]]Anwar Maqsood[[:>:]]/Anwar_Maqsood/g;
s/[[:<:]]Detroit Michigan[[:>:]]/Detroit_Michigan/g;
s/[[:<:]]crushed stone[[:>:]]/crushed_stone/g;
s/[[:<:]]backlog of[[:>:]]/backlog_of/g;
s/[[:<:]]the Opposition[[:>:]]/the_Opposition/g;
s/[[:<:]]cell biology[[:>:]]/cell_biology/g;
s/[[:<:]]Lucien Bouchard[[:>:]]/Lucien_Bouchard/g;
s/[[:<:]]In 1648[[:>:]]/In_1648/g;
s/[[:<:]]bus stop[[:>:]]/bus_stop/g;
s/[[:<:]]local councillor[[:>:]]/local_councillor/g;
s/[[:<:]]He remained[[:>:]]/He_remained/g;
s/[[:<:]]Anton Reicha[[:>:]]/Anton_Reicha/g;
s/[[:<:]]electric instruments[[:>:]]/electric_instruments/g;
s/[[:<:]]defined to be[[:>:]]/defined_to_be/g;
s/[[:<:]]population increase[[:>:]]/population_increase/g;
s/[[:<:]]Progressive Architecture[[:>:]]/Progressive_Architecture/g;
s/[[:<:]]Northumberland and Durham[[:>:]]/Northumberland_and_Durham/g;
s/[[:<:]]Rohit Ramachandran[[:>:]]/Rohit_Ramachandran/g;
s/[[:<:]]NSCAA adidas[[:>:]]/NSCAA_adidas/g;
s/[[:<:]]Allied war effort[[:>:]]/Allied_war_effort/g;
s/[[:<:]]non-profit group[[:>:]]/non-profit_group/g;
s/[[:<:]]requested by[[:>:]]/requested_by/g;
s/[[:<:]]Māori culture[[:>:]]/Māori_culture/g;
s/[[:<:]]the Future[[:>:]]/the_Future/g;
s/[[:<:]]in 1694[[:>:]]/in_1694/g;
s/[[:<:]]Delmarva Shorebirds[[:>:]]/Delmarva_Shorebirds/g;
s/[[:<:]]Tai Tokerau[[:>:]]/Tai_Tokerau/g;
s/[[:<:]]satellite technology[[:>:]]/satellite_technology/g;
s/[[:<:]]Hod HaSharon[[:>:]]/Hod_HaSharon/g;
s/[[:<:]]bridge builder[[:>:]]/bridge_builder/g;
s/[[:<:]]Kenneth Slessor[[:>:]]/Kenneth_Slessor/g;
s/[[:<:]]tarot card[[:>:]]/tarot_card/g;
s/[[:<:]]art and culture[[:>:]]/art_and_culture/g;
s/[[:<:]]comply with[[:>:]]/comply_with/g;
s/[[:<:]]construction worker[[:>:]]/construction_worker/g;
s/[[:<:]]and Police Leader[[:>:]]/and_Police_Leader/g;
s/[[:<:]]In 1857[[:>:]]/In_1857/g;
s/[[:<:]]Henri Pescarolo[[:>:]]/Henri_Pescarolo/g;
s/[[:<:]]mind-altering drugs[[:>:]]/mind-altering_drugs/g;
s/[[:<:]]font-size 85[[:>:]]/font-size_85/g;
s/[[:<:]]without adequate[[:>:]]/without_adequate/g;
s/[[:<:]]contributing author to[[:>:]]/contributing_author_to/g;
s/[[:<:]]Air Chief Marshal[[:>:]]/Air_Chief_Marshal/g;
s/[[:<:]]Governors Association[[:>:]]/Governors_Association/g;
s/[[:<:]]Political Commissar[[:>:]]/Political_Commissar/g;
s/[[:<:]]analog channel[[:>:]]/analog_channel/g;
s/[[:<:]]Kuk Sool[[:>:]]/Kuk_Sool/g;
s/[[:<:]]Master Mason[[:>:]]/Master_Mason/g;
s/[[:<:]]Copper Cliff[[:>:]]/Copper_Cliff/g;
s/[[:<:]]the Ashanti[[:>:]]/the_Ashanti/g;
s/[[:<:]]a kiss[[:>:]]/a_kiss/g;
s/[[:<:]]appeals to[[:>:]]/appeals_to/g;
s/[[:<:]]Lucchese crime[[:>:]]/Lucchese_crime/g;
s/[[:<:]]the assistant manager[[:>:]]/the_assistant_manager/g;
s/[[:<:]]N astirh[[:>:]]/N_astirh/g;
s/[[:<:]]was sighted[[:>:]]/was_sighted/g;
s/[[:<:]]ֵ ל[[:>:]]/ֵ_ל/g;
s/[[:<:]]capacity factor[[:>:]]/capacity_factor/g;
s/[[:<:]]Military Command[[:>:]]/Military_Command/g;
s/[[:<:]]sacrificed to[[:>:]]/sacrificed_to/g;
s/[[:<:]]Daniela Hantuchová[[:>:]]/Daniela_Hantuchová/g;
s/[[:<:]]sporting career[[:>:]]/sporting_career/g;
s/[[:<:]]Recipients AKCR[[:>:]]/Recipients_AKCR/g;
s/[[:<:]]Debre Tabor[[:>:]]/Debre_Tabor/g;
s/[[:<:]]settle voluntarily[[:>:]]/settle_voluntarily/g;
s/[[:<:]]div Scale[[:>:]]/div_Scale/g;
s/[[:<:]]antisubmarine exercises[[:>:]]/antisubmarine_exercises/g;
s/[[:<:]]Navy Fleet[[:>:]]/Navy_Fleet/g;
s/[[:<:]]102 JAMZ[[:>:]]/102_JAMZ/g;
s/[[:<:]]Hold on Me[[:>:]]/Hold_on_Me/g;
s/[[:<:]]points were scored[[:>:]]/points_were_scored/g;
s/[[:<:]]artists and groups[[:>:]]/artists_and_groups/g;
s/[[:<:]]has been under[[:>:]]/has_been_under/g;
s/[[:<:]]at all costs[[:>:]]/at_all_costs/g;
s/[[:<:]]a ship s[[:>:]]/a_ship_s/g;
s/[[:<:]]TriStar Pictures[[:>:]]/TriStar_Pictures/g;
s/[[:<:]]a clear day[[:>:]]/a_clear_day/g;
s/[[:<:]]may appoint[[:>:]]/may_appoint/g;
s/[[:<:]]pattern of[[:>:]]/pattern_of/g;
s/[[:<:]]her early childhood[[:>:]]/her_early_childhood/g;
s/[[:<:]]red and white[[:>:]]/red_and_white/g;
s/[[:<:]]· edit[[:>:]]/·_edit/g;
s/[[:<:]]her young[[:>:]]/her_young/g;
s/[[:<:]]professional debut for[[:>:]]/professional_debut_for/g;
s/[[:<:]]Minister-President of[[:>:]]/Minister-President_of/g;
s/[[:<:]]Litt D[[:>:]]/Litt_D/g;
s/[[:<:]]drained soils[[:>:]]/drained_soils/g;
s/[[:<:]]Justin Allgaier[[:>:]]/Justin_Allgaier/g;
s/[[:<:]]Lectures on[[:>:]]/Lectures_on/g;
s/[[:<:]]tablet PCs[[:>:]]/tablet_PCs/g;
s/[[:<:]]Macchi M[[:>:]]/Macchi_M/g;
s/[[:<:]]an acceleration[[:>:]]/an_acceleration/g;
s/[[:<:]]Himachal Pradesh[[:>:]]/Himachal_Pradesh/g;
s/[[:<:]]9 hours[[:>:]]/9_hours/g;
s/[[:<:]]saline soils[[:>:]]/saline_soils/g;
s/[[:<:]]in orbit around[[:>:]]/in_orbit_around/g;
s/[[:<:]]Critically acclaimed[[:>:]]/Critically_acclaimed/g;
s/[[:<:]]Erta Ale[[:>:]]/Erta_Ale/g;
s/[[:<:]]budget shortfall[[:>:]]/budget_shortfall/g;
s/[[:<:]]Carolingian dynasty[[:>:]]/Carolingian_dynasty/g;
s/[[:<:]]10th round[[:>:]]/10th_round/g;
s/[[:<:]]Queen Regent[[:>:]]/Queen_Regent/g;
s/[[:<:]]Tanzania Togo[[:>:]]/Tanzania_Togo/g;
s/[[:<:]]playing football with[[:>:]]/playing_football_with/g;
s/[[:<:]]revolving around[[:>:]]/revolving_around/g;
s/[[:<:]]sedimentary strata[[:>:]]/sedimentary_strata/g;
s/[[:<:]]Ramon Fernandez[[:>:]]/Ramon_Fernandez/g;
s/[[:<:]]do whatever[[:>:]]/do_whatever/g;
s/[[:<:]]75 0[[:>:]]/75_0/g;
s/[[:<:]]spherical symmetry[[:>:]]/spherical_symmetry/g;
s/[[:<:]]TV roles[[:>:]]/TV_roles/g;
s/[[:<:]]Downey Jr[[:>:]]/Downey_Jr/g;
s/[[:<:]]extra-marital affairs[[:>:]]/extra-marital_affairs/g;
s/[[:<:]]All Day[[:>:]]/All_Day/g;
s/[[:<:]]abdominal aorta[[:>:]]/abdominal_aorta/g;
s/[[:<:]]is a 1965[[:>:]]/is_a_1965/g;
s/[[:<:]]Mount Tamalpais[[:>:]]/Mount_Tamalpais/g;
s/[[:<:]]Queensboro Bridge[[:>:]]/Queensboro_Bridge/g;
s/[[:<:]]his prison sentence[[:>:]]/his_prison_sentence/g;
s/[[:<:]]Magda Olivero[[:>:]]/Magda_Olivero/g;
s/[[:<:]]giallo film[[:>:]]/giallo_film/g;
s/[[:<:]]many cases[[:>:]]/many_cases/g;
s/[[:<:]]recording songs[[:>:]]/recording_songs/g;
s/[[:<:]]relief panels[[:>:]]/relief_panels/g;
s/[[:<:]]refresher course[[:>:]]/refresher_course/g;
s/[[:<:]]All-Star Futures Game[[:>:]]/All-Star_Futures_Game/g;
s/[[:<:]]adrenal gland[[:>:]]/adrenal_gland/g;
s/[[:<:]]the 107th[[:>:]]/the_107th/g;
s/[[:<:]]The tour[[:>:]]/The_tour/g;
s/[[:<:]]an 11-point[[:>:]]/an_11-point/g;
s/[[:<:]]National Committeewoman[[:>:]]/National_Committeewoman/g;
s/[[:<:]]financial distress[[:>:]]/financial_distress/g;
s/[[:<:]]ਾ ਲ[[:>:]]/ਾ_ਲ/g;
s/[[:<:]]Tokyo Metropolitan Government[[:>:]]/Tokyo_Metropolitan_Government/g;
s/[[:<:]]focuses heavily on[[:>:]]/focuses_heavily_on/g;
s/[[:<:]]Ba Cụt[[:>:]]/Ba_Cụt/g;
s/[[:<:]]more powerful[[:>:]]/more_powerful/g;
s/[[:<:]]The Classroom for[[:>:]]/The_Classroom_for/g;
s/[[:<:]]Toby Whithouse[[:>:]]/Toby_Whithouse/g;
s/[[:<:]]Zürcher Oberland[[:>:]]/Zürcher_Oberland/g;
s/[[:<:]]Annual General Meeting[[:>:]]/Annual_General_Meeting/g;
s/[[:<:]]Umeå Sweden[[:>:]]/Umeå_Sweden/g;
s/[[:<:]]Blue Note label[[:>:]]/Blue_Note_label/g;
s/[[:<:]]Comparative Anatomy[[:>:]]/Comparative_Anatomy/g;
s/[[:<:]]Korać Cup[[:>:]]/Korać_Cup/g;
s/[[:<:]]days until[[:>:]]/days_until/g;
s/[[:<:]]hydrogen sulphide[[:>:]]/hydrogen_sulphide/g;
s/[[:<:]]Madras India[[:>:]]/Madras_India/g;
s/[[:<:]]Error rider[[:>:]]/Error_rider/g;
s/[[:<:]]ties to[[:>:]]/ties_to/g;
s/[[:<:]]was renumbered[[:>:]]/was_renumbered/g;
s/[[:<:]]Tuesdays and Fridays[[:>:]]/Tuesdays_and_Fridays/g;
s/[[:<:]]Choctaw Nation[[:>:]]/Choctaw_Nation/g;
s/[[:<:]]Société Française[[:>:]]/Société_Française/g;
s/[[:<:]]Montgomery Blair[[:>:]]/Montgomery_Blair/g;
s/[[:<:]]pale golden[[:>:]]/pale_golden/g;
s/[[:<:]]is a Ugandan[[:>:]]/is_a_Ugandan/g;
s/[[:<:]]an adept[[:>:]]/an_adept/g;
s/[[:<:]]Katholieke Universiteit[[:>:]]/Katholieke_Universiteit/g;
s/[[:<:]]British explorer[[:>:]]/British_explorer/g;
s/[[:<:]]prehistoric period[[:>:]]/prehistoric_period/g;
s/[[:<:]]jazz saxophonist[[:>:]]/jazz_saxophonist/g;
s/[[:<:]]twelve feet[[:>:]]/twelve_feet/g;
s/[[:<:]]re-branded as[[:>:]]/re-branded_as/g;
s/[[:<:]]gender discrimination[[:>:]]/gender_discrimination/g;
s/[[:<:]]changed hands[[:>:]]/changed_hands/g;
s/[[:<:]]screech owls[[:>:]]/screech_owls/g;
s/[[:<:]]Avram Iancu[[:>:]]/Avram_Iancu/g;
s/[[:<:]]community-acquired pneumonia[[:>:]]/community-acquired_pneumonia/g;
s/[[:<:]]traveled to[[:>:]]/traveled_to/g;
s/[[:<:]]County Wisconsin[[:>:]]/County_Wisconsin/g;
s/[[:<:]]From that date[[:>:]]/From_that_date/g;
s/[[:<:]]Bishop of[[:>:]]/Bishop_of/g;
s/[[:<:]]ी ह[[:>:]]/ी_ह/g;
s/[[:<:]]a foreigner[[:>:]]/a_foreigner/g;
s/[[:<:]]Saif al-Islam[[:>:]]/Saif_al-Islam/g;
s/[[:<:]]Late Triassic[[:>:]]/Late_Triassic/g;
s/[[:<:]]law and medicine[[:>:]]/law_and_medicine/g;
s/[[:<:]]eventual champions[[:>:]]/eventual_champions/g;
s/[[:<:]]two bays[[:>:]]/two_bays/g;
s/[[:<:]]Kamieniec Ząbkowicki[[:>:]]/Kamieniec_Ząbkowicki/g;
s/[[:<:]]$50 billion[[:>:]]/$50_billion/g;
s/[[:<:]]175 m[[:>:]]/175_m/g;
s/[[:<:]]Empress Theodora[[:>:]]/Empress_Theodora/g;
s/[[:<:]]nervous system[[:>:]]/nervous_system/g;
s/[[:<:]]van Beuningen[[:>:]]/van_Beuningen/g;
