s/\bDance Troupe\b/Dance_Troupe/g;
s/\bMaha Bandula\b/Maha_Bandula/g;
s/\bdrawings are\b/drawings_are/g;
s/\bOrphan Asylum\b/Orphan_Asylum/g;
s/\bnamed “\b/named_“/g;
s/\bmoderate success\b/moderate_success/g;
s/\bfeatured artist\b/featured_artist/g;
s/\bIn 1848\b/In_1848/g;
s/\bresidential districts\b/residential_districts/g;
s/\bRupert Penry-Jones\b/Rupert_Penry-Jones/g;
s/\bbut they divorced\b/but_they_divorced/g;
s/\bAl Shabaab\b/Al_Shabaab/g;
s/\bcubic lattice\b/cubic_lattice/g;
s/\bHal Blaine\b/Hal_Blaine/g;
s/\bA champion seed\b/A_champion_seed/g;
s/\bSuddenly Last\b/Suddenly_Last/g;
s/\bKwai Fong\b/Kwai_Fong/g;
s/\bpublic defenders\b/public_defenders/g;
s/\bTP Mazembe\b/TP_Mazembe/g;
s/\bMilorad Dodik\b/Milorad_Dodik/g;
s/\bHenry John\b/Henry_John/g;
s/\bHarry Saltzman\b/Harry_Saltzman/g;
s/\bFall 2014\b/Fall_2014/g;
s/\brecord and perform\b/record_and_perform/g;
s/\bsteam engines\b/steam_engines/g;
s/\brushing for\b/rushing_for/g;
s/\bBayburt Bayburt\b/Bayburt_Bayburt/g;
s/\bcar accident\b/car_accident/g;
s/\bpromised them\b/promised_them/g;
s/\bmany fields\b/many_fields/g;
s/\bTech Prep\b/Tech_Prep/g;
s/\bSub-Aqua Club\b/Sub-Aqua_Club/g;
s/\bThe incident\b/The_incident/g;
s/\bSucker Punch\b/Sucker_Punch/g;
s/\bAct amended\b/Act_amended/g;
s/\bVerein zur\b/Verein_zur/g;
s/\bprofessor emeritus\b/professor_emeritus/g;
s/\bStacia Proefrock\b/Stacia_Proefrock/g;
s/\bson Arthur\b/son_Arthur/g;
s/\bfile contains\b/file_contains/g;
s/\b$225 000\b/$225_000/g;
s/\bThales Alenia\b/Thales_Alenia/g;
s/\bin Kosovo\b/in_Kosovo/g;
s/\bsubjecting them\b/subjecting_them/g;
s/\btin mines\b/tin_mines/g;
s/\bside-by-side rowing\b/side-by-side_rowing/g;
s/\bDoug Wright\b/Doug_Wright/g;
s/\bwidows and widowers\b/widows_and_widowers/g;
s/\btroubled times\b/troubled_times/g;
s/\bEmployers Confederation\b/Employers_Confederation/g;
s/\bSuresh Wadkar\b/Suresh_Wadkar/g;
s/\bSalinas Valley\b/Salinas_Valley/g;
s/\bAtlantic seaboard\b/Atlantic_seaboard/g;
s/\bcar salesman\b/car_salesman/g;
s/\bindentured servants\b/indentured_servants/g;
s/\bseven-game series\b/seven-game_series/g;
s/\bwarms up\b/warms_up/g;
s/\bJudy Greer\b/Judy_Greer/g;
s/\bNachke Dikha\b/Nachke_Dikha/g;
s/\bε 0\b/ε_0/g;
s/\bLisson Gallery\b/Lisson_Gallery/g;
s/\bGrupo Televisa\b/Grupo_Televisa/g;
s/\bde Mendoza\b/de_Mendoza/g;
s/\bthe temple\b/the_temple/g;
s/\bQueen Rania\b/Queen_Rania/g;
s/\bAustralasian Championships\b/Australasian_Championships/g;
s/\bthe Qin Dynasty\b/the_Qin_Dynasty/g;
s/\bpolitical upheavals\b/political_upheavals/g;
s/\b40-man roster\b/40-man_roster/g;
s/\bUnfunded Mandates\b/Unfunded_Mandates/g;
s/\bhis main interest\b/his_main_interest/g;
s/\bIslamic sciences\b/Islamic_sciences/g;
s/\bDuke Ellington\b/Duke_Ellington/g;
s/\bmiscarriage of justice\b/miscarriage_of_justice/g;
s/\bBiblioteca Marciana\b/Biblioteca_Marciana/g;
s/\bKjell Magne Bondevik\b/Kjell_Magne_Bondevik/g;
s/\bAFL Draft\b/AFL_Draft/g;
s/\bsent representatives to\b/sent_representatives_to/g;
s/\bVan Nistelrooy\b/Van_Nistelrooy/g;
s/\bwas leaked\b/was_leaked/g;
s/\bthe 27th\b/the_27th/g;
s/\band runs into\b/and_runs_into/g;
s/\bPropionibacterium acnes\b/Propionibacterium_acnes/g;
s/\bHelikopter Service\b/Helikopter_Service/g;
s/\ba blockade\b/a_blockade/g;
s/\bDownload Festival\b/Download_Festival/g;
s/\bcure for\b/cure_for/g;
s/\battract tourists\b/attract_tourists/g;
s/\bshade tree\b/shade_tree/g;
s/\bconsists largely of\b/consists_largely_of/g;
s/\bDef Leppard\b/Def_Leppard/g;
s/\bsimulation video game\b/simulation_video_game/g;
s/\bLokomotiv Plovdiv\b/Lokomotiv_Plovdiv/g;
s/\bKent Hrbek\b/Kent_Hrbek/g;
s/\bShe transited\b/She_transited/g;
s/\bPoison the Well\b/Poison_the_Well/g;
s/\brequests from\b/requests_from/g;
s/\bSeattle Metropolitans\b/Seattle_Metropolitans/g;
s/\bShortly thereafter\b/Shortly_thereafter/g;
s/\bMiami-Fort Lauderdale\b/Miami-Fort_Lauderdale/g;
s/\bMake You Mine\b/Make_You_Mine/g;
s/\bmountain rescue\b/mountain_rescue/g;
s/\b$9 billion\b/$9_billion/g;
s/\bTopics covered include\b/Topics_covered_include/g;
s/\bCindy Sheehan\b/Cindy_Sheehan/g;
s/\bdescending from\b/descending_from/g;
s/\bwas re-created\b/was_re-created/g;
s/\bdo Amaral\b/do_Amaral/g;
s/\bFranz Nopcsa\b/Franz_Nopcsa/g;
s/\bMusic Inc\b/Music_Inc/g;
s/\bEl Texano\b/El_Texano/g;
s/\bMissouri Senate\b/Missouri_Senate/g;
s/\bconstitutional right\b/constitutional_right/g;
s/\bin 1817\b/in_1817/g;
s/\bcollided with\b/collided_with/g;
s/\bPersian خرم\b/Persian_خرم/g;
s/\bRichard Seddon\b/Richard_Seddon/g;
s/\bher last\b/her_last/g;
s/\bTessa Jowell\b/Tessa_Jowell/g;
s/\bhis request\b/his_request/g;
s/\ba novelist\b/a_novelist/g;
s/\bcoastal cliffs\b/coastal_cliffs/g;
s/\bGood Practice\b/Good_Practice/g;
s/\badoptive mother\b/adoptive_mother/g;
s/\bclassified under\b/classified_under/g;
s/\bIn Praise of\b/In_Praise_of/g;
s/\bKopparbergs Göteborg\b/Kopparbergs_Göteborg/g;
s/\bMiikka Kiprusoff\b/Miikka_Kiprusoff/g;
s/\bDelle Donne\b/Delle_Donne/g;
s/\bSheikh Mohammed\b/Sheikh_Mohammed/g;
s/\bAllied governments\b/Allied_governments/g;
s/\bBade Ghulam\b/Bade_Ghulam/g;
s/\bRené Auberjonois\b/René_Auberjonois/g;
s/\bequivalent to\b/equivalent_to/g;
s/\bLinux OS\b/Linux_OS/g;
s/\bheroes and villains\b/heroes_and_villains/g;
s/\belementary school\b/elementary_school/g;
s/\bContracting Parties\b/Contracting_Parties/g;
s/\bat Pride Park\b/at_Pride_Park/g;
s/\bIND Concourse\b/IND_Concourse/g;
s/\bmeditation on\b/meditation_on/g;
s/\btheir concerts\b/their_concerts/g;
s/\bUrban Districts\b/Urban_Districts/g;
s/\bin shaping\b/in_shaping/g;
s/\bGmina Goleniów within\b/Gmina_Goleniów_within/g;
s/\ba confession\b/a_confession/g;
s/\breed organ\b/reed_organ/g;
s/\bInstitute for\b/Institute_for/g;
s/\bshopping malls\b/shopping_malls/g;
s/\bpolitical crises\b/political_crises/g;
s/\bAnnual Conferences\b/Annual_Conferences/g;
s/\bPET bottles\b/PET_bottles/g;
s/\bPhilip Rivers\b/Philip_Rivers/g;
s/\bBaptist church\b/Baptist_church/g;
s/\btold by\b/told_by/g;
s/\bhopes to\b/hopes_to/g;
s/\bdestined to\b/destined_to/g;
s/\bSouth African international\b/South_African_international/g;
s/\bKevin Sumlin\b/Kevin_Sumlin/g;
s/\bHarold Laski\b/Harold_Laski/g;
s/\btells about\b/tells_about/g;
s/\bJoan Fontaine\b/Joan_Fontaine/g;
s/\bprovided through\b/provided_through/g;
s/\bSakha Republic\b/Sakha_Republic/g;
s/\bBedtime Stories\b/Bedtime_Stories/g;
s/\bAct II\b/Act_II/g;
s/\bLe Jeune\b/Le_Jeune/g;
s/\bcasting doubt\b/casting_doubt/g;
s/\bhigh frequencies\b/high_frequencies/g;
s/\baided and abetted\b/aided_and_abetted/g;
s/\bNorthern Ostrobothnia\b/Northern_Ostrobothnia/g;
s/\bforced marriages\b/forced_marriages/g;
s/\bwants to\b/wants_to/g;
s/\bat Bellator\b/at_Bellator/g;
s/\bsports anchor\b/sports_anchor/g;
s/\bThe 2013 season\b/The_2013_season/g;
s/\bSuper Bowls\b/Super_Bowls/g;
s/\bNeotropical ecozone\b/Neotropical_ecozone/g;
s/\bHsieh Su-wei\b/Hsieh_Su-wei/g;
s/\bwas really\b/was_really/g;
s/\breligious ceremonies\b/religious_ceremonies/g;
s/\bOperational squadrons\b/Operational_squadrons/g;
s/\bAshford Simpson\b/Ashford_Simpson/g;
s/\bTazeh Kand-e\b/Tazeh_Kand-e/g;
s/\bNational Flag\b/National_Flag/g;
s/\banti-money laundering\b/anti-money_laundering/g;
s/\bRoker Park\b/Roker_Park/g;
s/\bTony Gonzalez\b/Tony_Gonzalez/g;
s/\blandfalls extratropical transitions\b/landfalls_extratropical_transitions/g;
s/\bManchester Cathedral\b/Manchester_Cathedral/g;
s/\bKarst topography\b/Karst_topography/g;
s/\ban uneventful\b/an_uneventful/g;
s/\bclothing designer\b/clothing_designer/g;
s/\bBob Clampett\b/Bob_Clampett/g;
s/\bLori McNeil\b/Lori_McNeil/g;
s/\brural school districts\b/rural_school_districts/g;
s/\bShanghai Beijing\b/Shanghai_Beijing/g;
s/\bProto-Indo-European PIE\b/Proto-Indo-European_PIE/g;
s/\bKūkō IATA\b/Kūkō_IATA/g;
s/\bin order that\b/in_order_that/g;
s/\blower elevation\b/lower_elevation/g;
s/\bhis fellows\b/his_fellows/g;
s/\bGurbanguly Berdimuhamedov\b/Gurbanguly_Berdimuhamedov/g;
s/\ban entire\b/an_entire/g;
s/\belectrical outlet\b/electrical_outlet/g;
s/\ban Associate\b/an_Associate/g;
s/\bGrowling Tigers\b/Growling_Tigers/g;
s/\bartillery batteries\b/artillery_batteries/g;
s/\bFort Gordon\b/Fort_Gordon/g;
s/\bSerban Ghenea\b/Serban_Ghenea/g;
s/\bthe field he\b/the_field_he/g;
s/\bGary Russell\b/Gary_Russell/g;
s/\bInterview magazine\b/Interview_magazine/g;
s/\bOur Last\b/Our_Last/g;
s/\bhas been capped\b/has_been_capped/g;
s/\bJezreel Valley\b/Jezreel_Valley/g;
s/\band enlarged\b/and_enlarged/g;
s/\bhuman emotions\b/human_emotions/g;
s/\bthe Regent s\b/the_Regent_s/g;
s/\bJoint Distribution\b/Joint_Distribution/g;
s/\bcompete together\b/compete_together/g;
s/\bpanned by critics\b/panned_by_critics/g;
s/\bSeveral scholars\b/Several_scholars/g;
s/\bRed Line\b/Red_Line/g;
s/\bDeportivo Español\b/Deportivo_Español/g;
s/\bmillion items\b/million_items/g;
s/\bmentally incompetent\b/mentally_incompetent/g;
s/\bfunded by\b/funded_by/g;
s/\bexecutive bureau\b/executive_bureau/g;
s/\bhas rarely been\b/has_rarely_been/g;
s/\bEl Roumi\b/El_Roumi/g;
s/\bdelimited by\b/delimited_by/g;
s/\bIchikawa Danjūrō\b/Ichikawa_Danjūrō/g;
s/\bNeuberger Berman\b/Neuberger_Berman/g;
s/\birreparably damaged\b/irreparably_damaged/g;
s/\bproduct liability\b/product_liability/g;
s/\ball life on\b/all_life_on/g;
s/\bDehaj District\b/Dehaj_District/g;
s/\bensued with\b/ensued_with/g;
s/\bAmr Diab\b/Amr_Diab/g;
s/\bTechnical Staff\b/Technical_Staff/g;
s/\bduring the brief\b/during_the_brief/g;
s/\bHoubraken he\b/Houbraken_he/g;
s/\bNational Stud\b/National_Stud/g;
s/\bPolitical Cesspool\b/Political_Cesspool/g;
s/\bSealab 2021\b/Sealab_2021/g;
s/\bVisiting Fellow\b/Visiting_Fellow/g;
s/\bhigh energy\b/high_energy/g;
s/\bCyril Washbrook\b/Cyril_Washbrook/g;
s/\bUtagawa Kunisada\b/Utagawa_Kunisada/g;
s/\bInterbank Offered\b/Interbank_Offered/g;
s/\bher grave\b/her_grave/g;
s/\bin 1831\b/in_1831/g;
s/\bBoswell s\b/Boswell_s/g;
s/\bhandheld devices\b/handheld_devices/g;
s/\bin the leg\b/in_the_leg/g;
s/\bBiblical Seminary\b/Biblical_Seminary/g;
s/\bALGOL 68\b/ALGOL_68/g;
s/\bdo not\b/do_not/g;
s/\bSông Lam Nghệ\b/Sông_Lam_Nghệ/g;
s/\bAtlanta July 22-August\b/Atlanta_July_22-August/g;
s/\bس ُ\b/س_ُ/g;
s/\b10 a m\b/10_a_m/g;
s/\bJermaine Dupri\b/Jermaine_Dupri/g;
s/\bBritish protectorate\b/British_protectorate/g;
s/\b59 8\b/59_8/g;
s/\bFC Groningen\b/FC_Groningen/g;
s/\bmuch effort\b/much_effort/g;
s/\bBBC 6\b/BBC_6/g;
s/\bevery 4 years\b/every_4_years/g;
s/\bslumber party\b/slumber_party/g;
s/\bpresumed lost\b/presumed_lost/g;
s/\bNguyen Ngoc\b/Nguyen_Ngoc/g;
s/\bwould employ\b/would_employ/g;
s/\bCampeonato Brasileiro\b/Campeonato_Brasileiro/g;
s/\bOverClocked ReMix\b/OverClocked_ReMix/g;
s/\bcoping skills\b/coping_skills/g;
s/\bLubbock Texas\b/Lubbock_Texas/g;
s/\bBlind Guardian\b/Blind_Guardian/g;
s/\bwithdrawn from\b/withdrawn_from/g;
s/\bdivided four-lane\b/divided_four-lane/g;
s/\bresting place\b/resting_place/g;
s/\bmillion in sales\b/million_in_sales/g;
s/\bThankful Villages\b/Thankful_Villages/g;
s/\bNeon Trees\b/Neon_Trees/g;
s/\bArrive Alive\b/Arrive_Alive/g;
s/\bresolves to\b/resolves_to/g;
s/\bPran Nath\b/Pran_Nath/g;
s/\bcopper oxide\b/copper_oxide/g;
s/\btestify that\b/testify_that/g;
s/\bthe Baskervilles\b/the_Baskervilles/g;
s/\bAverell Harriman\b/Averell_Harriman/g;
s/\bmetal frame\b/metal_frame/g;
s/\bOrszágos Bajnokság\b/Országos_Bajnokság/g;
s/\bMonday November\b/Monday_November/g;
s/\bthe Ohio Senate\b/the_Ohio_Senate/g;
s/\bCurling Association\b/Curling_Association/g;
s/\bis not visible\b/is_not_visible/g;
s/\bMister Terrific\b/Mister_Terrific/g;
s/\bevacuation of\b/evacuation_of/g;
s/\bNagorno-Karabakh Republic\b/Nagorno-Karabakh_Republic/g;
s/\bthe oceans\b/the_oceans/g;
s/\bstrengthened into\b/strengthened_into/g;
s/\briders from\b/riders_from/g;
s/\bJavier Saviola\b/Javier_Saviola/g;
s/\bIndianapolis Raceway Park\b/Indianapolis_Raceway_Park/g;
s/\bField Hospital\b/Field_Hospital/g;
s/\bwas $34\b/was_$34/g;
s/\blit year name\b/lit_year_name/g;
s/\bda Vida\b/da_Vida/g;
s/\baged 14\b/aged_14/g;
s/\blikeness of\b/likeness_of/g;
s/\brelative frequency\b/relative_frequency/g;
s/\baerial warfare\b/aerial_warfare/g;
s/\bISO 3166\b/ISO_3166/g;
s/\btheir destination\b/their_destination/g;
s/\ba thirty-year\b/a_thirty-year/g;
s/\bis famous as\b/is_famous_as/g;
s/\bMilwaukee Braves\b/Milwaukee_Braves/g;
s/\bJean-Baptiste Mondino\b/Jean-Baptiste_Mondino/g;
s/\b– 1979\b/–_1979/g;
s/\bfirst published on\b/first_published_on/g;
s/\bSola Scriptura\b/Sola_Scriptura/g;
s/\bTreat Me\b/Treat_Me/g;
s/\b40-yard dash\b/40-yard_dash/g;
s/\bSociété Anonyme\b/Société_Anonyme/g;
s/\bFantasy Science Fiction\b/Fantasy_Science_Fiction/g;
s/\bFencing Federation\b/Fencing_Federation/g;
s/\bpiano organ\b/piano_organ/g;
s/\bexpressed their concern\b/expressed_their_concern/g;
s/\bwas played against\b/was_played_against/g;
s/\bmarket index\b/market_index/g;
s/\bWhite Cliffs\b/White_Cliffs/g;
s/\bUpland School District\b/Upland_School_District/g;
s/\bState Senator\b/State_Senator/g;
s/\bBenigno Aquino\b/Benigno_Aquino/g;
s/\b110 meter hurdles\b/110_meter_hurdles/g;
s/\bgenetic loci\b/genetic_loci/g;
s/\bStanley William Hayter\b/Stanley_William_Hayter/g;
s/\bfarther than\b/farther_than/g;
s/\bthe team from\b/the_team_from/g;
s/\bAFL Premiership\b/AFL_Premiership/g;
s/\bgirl friend\b/girl_friend/g;
s/\bSkate Park\b/Skate_Park/g;
s/\bdevoted most of\b/devoted_most_of/g;
s/\bis a 1971\b/is_a_1971/g;
s/\bAbd al-Qādir\b/Abd_al-Qādir/g;
s/\bmiraculous healing\b/miraculous_healing/g;
s/\bRhineland-Palatinate Germany\b/Rhineland-Palatinate_Germany/g;
s/\bopéras comiques\b/opéras_comiques/g;
s/\bGonçalves Zarco\b/Gonçalves_Zarco/g;
s/\bneutron stars\b/neutron_stars/g;
s/\bat sunrise\b/at_sunrise/g;
s/\bbonded to\b/bonded_to/g;
s/\bin 1507\b/in_1507/g;
s/\bis gone\b/is_gone/g;
s/\btectonic activity\b/tectonic_activity/g;
s/\bthe harbour\b/the_harbour/g;
s/\bhighly automated\b/highly_automated/g;
s/\ba briefing\b/a_briefing/g;
s/\b् वत\b/्_वत/g;
s/\bbasketball game\b/basketball_game/g;
s/\bFourier transform\b/Fourier_transform/g;
s/\bstatistical compilation by\b/statistical_compilation_by/g;
s/\bthousand rupees\b/thousand_rupees/g;
s/\bProgressive Party\b/Progressive_Party/g;
s/\bliving conditions\b/living_conditions/g;
s/\btort liability\b/tort_liability/g;
s/\bin the south-west\b/in_the_south-west/g;
s/\byounger siblings\b/younger_siblings/g;
s/\bBritish consul\b/British_consul/g;
s/\bSouthern Conference\b/Southern_Conference/g;
s/\bsurrounding waters\b/surrounding_waters/g;
s/\bThe insignia\b/The_insignia/g;
s/\ba Democrat\b/a_Democrat/g;
s/\bThe US Army\b/The_US_Army/g;
s/\bJack McDuff\b/Jack_McDuff/g;
s/\bOrange Revolution\b/Orange_Revolution/g;
s/\bis murdered by\b/is_murdered_by/g;
s/\bmetal halides\b/metal_halides/g;
s/\bState Guard\b/State_Guard/g;
s/\bHighly Qualified\b/Highly_Qualified/g;
s/\bhealth resort\b/health_resort/g;
s/\bIdentity Cards\b/Identity_Cards/g;
s/\bconsider to be\b/consider_to_be/g;
s/\bwikitable succession-box\b/wikitable_succession-box/g;
s/\bKeeper of\b/Keeper_of/g;
s/\bunstressed syllables\b/unstressed_syllables/g;
s/\bArticles of Confederation\b/Articles_of_Confederation/g;
s/\bin a season\b/in_a_season/g;
s/\bway of doing\b/way_of_doing/g;
s/\bendeared himself to\b/endeared_himself_to/g;
s/\bWest Kirby\b/West_Kirby/g;
s/\bRedondo Beach\b/Redondo_Beach/g;
s/\bturned over\b/turned_over/g;
s/\btorrential downpour\b/torrential_downpour/g;
s/\bRillington Place\b/Rillington_Place/g;
s/\bZaporizhian Host\b/Zaporizhian_Host/g;
s/\bBetween 1994\b/Between_1994/g;
s/\bprovoked by\b/provoked_by/g;
s/\bHitman Reborn\b/Hitman_Reborn/g;
s/\bhis arm\b/his_arm/g;
s/\bescaped capture\b/escaped_capture/g;
s/\bShari ah\b/Shari_ah/g;
s/\brectus femoris\b/rectus_femoris/g;
s/\bassurance that\b/assurance_that/g;
s/\bBlur s\b/Blur_s/g;
s/\bbefore heading\b/before_heading/g;
s/\bRussian SFSR\b/Russian_SFSR/g;
s/\bM40 motorway\b/M40_motorway/g;
s/\bBy 1956\b/By_1956/g;
s/\bSoviet intelligence\b/Soviet_intelligence/g;
s/\bButterfield Overland\b/Butterfield_Overland/g;
s/\bWeather Forecast\b/Weather_Forecast/g;
s/\bBest Books\b/Best_Books/g;
s/\bFilm critic\b/Film_critic/g;
s/\bat sea with\b/at_sea_with/g;
s/\bTension between\b/Tension_between/g;
s/\bCommunications Network\b/Communications_Network/g;
s/\bcompatible computers\b/compatible_computers/g;
s/\btou dromou\b/tou_dromou/g;
s/\bFight Like Apes\b/Fight_Like_Apes/g;
s/\bmilitary service\b/military_service/g;
s/\bgave recitals\b/gave_recitals/g;
s/\bhunting ground\b/hunting_ground/g;
s/\bJens Lekman\b/Jens_Lekman/g;
s/\bZyuden Sentai Kyoryuger\b/Zyuden_Sentai_Kyoryuger/g;
s/\bdialect continuum\b/dialect_continuum/g;
s/\bHedo Türkoğlu\b/Hedo_Türkoğlu/g;
s/\bclaims against\b/claims_against/g;
s/\bSheung Shui\b/Sheung_Shui/g;
s/\bMetropolitan Stadium\b/Metropolitan_Stadium/g;
s/\bJosé Maria\b/José_Maria/g;
s/\b– 1936\b/–_1936/g;
s/\bWarriston Cemetery\b/Warriston_Cemetery/g;
s/\bDeanna Troi\b/Deanna_Troi/g;
s/\bDavie Florida\b/Davie_Florida/g;
s/\bSuper Soaker\b/Super_Soaker/g;
s/\bat up to\b/at_up_to/g;
s/\bRepublican nominee\b/Republican_nominee/g;
s/\bmelting glaciers\b/melting_glaciers/g;
s/\bMonte Bello\b/Monte_Bello/g;
s/\bOakland A s\b/Oakland_A_s/g;
s/\bpituitary adenoma\b/pituitary_adenoma/g;
s/\bsmaller firms\b/smaller_firms/g;
s/\bSeattle Storm\b/Seattle_Storm/g;
s/\bOrange California\b/Orange_California/g;
s/\bIn 1567\b/In_1567/g;
s/\bunwed mother\b/unwed_mother/g;
s/\bRichard T\b/Richard_T/g;
s/\bcustoms officers\b/customs_officers/g;
s/\bprefrontal cortex\b/prefrontal_cortex/g;
s/\bComedy Club\b/Comedy_Club/g;
s/\bdocument containing\b/document_containing/g;
s/\bheated up\b/heated_up/g;
s/\bHuntsville AL\b/Huntsville_AL/g;
s/\bSinéad Cusack\b/Sinéad_Cusack/g;
s/\btransitional justice\b/transitional_justice/g;
s/\bBorn Sinner\b/Born_Sinner/g;
s/\bthe Valiants\b/the_Valiants/g;
s/\bwould survive\b/would_survive/g;
s/\bDiane Cilento\b/Diane_Cilento/g;
s/\bCape Farewell\b/Cape_Farewell/g;
s/\bathletics events\b/athletics_events/g;
s/\bRookwood Cemetery\b/Rookwood_Cemetery/g;
s/\blieutenant governors\b/lieutenant_governors/g;
s/\bKatalog Film Indonesia\b/Katalog_Film_Indonesia/g;
s/\bthe shaping of\b/the_shaping_of/g;
s/\bat 28 August\b/at_28_August/g;
s/\bJimmie Foxx\b/Jimmie_Foxx/g;
s/\bexplanatory variable\b/explanatory_variable/g;
s/\ba motion of\b/a_motion_of/g;
s/\bis grown\b/is_grown/g;
s/\bwireless network\b/wireless_network/g;
s/\ban article from\b/an_article_from/g;
s/\band video recordings\b/and_video_recordings/g;
s/\brampant corruption\b/rampant_corruption/g;
s/\bcountless other\b/countless_other/g;
s/\b24 2\b/24_2/g;
s/\bIgA nephropathy\b/IgA_nephropathy/g;
s/\bNorthern Beaches\b/Northern_Beaches/g;
s/\bKansas Legislature\b/Kansas_Legislature/g;
s/\bpolitical appointments\b/political_appointments/g;
s/\bZhongshu Shilang 中書侍郎\b/Zhongshu_Shilang_中書侍郎/g;
s/\bStu Hart\b/Stu_Hart/g;
s/\bthe team for\b/the_team_for/g;
s/\bMcAllen Texas\b/McAllen_Texas/g;
s/\bOlimpia Milano\b/Olimpia_Milano/g;
s/\btempered glass\b/tempered_glass/g;
s/\bgeneral manager\b/general_manager/g;
s/\bJim Stynes\b/Jim_Stynes/g;
s/\bElm Yellows\b/Elm_Yellows/g;
s/\bat Mosport\b/at_Mosport/g;
s/\bunseeded teams\b/unseeded_teams/g;
s/\bthe 18th season\b/the_18th_season/g;
s/\balluding to\b/alluding_to/g;
s/\bfamily Rutaceae\b/family_Rutaceae/g;
s/\brole-playing games\b/role-playing_games/g;
s/\bOld Colony\b/Old_Colony/g;
s/\bpremeditated murder\b/premeditated_murder/g;
s/\bMister Mind\b/Mister_Mind/g;
s/\bEach participant\b/Each_participant/g;
s/\bTracie Thoms\b/Tracie_Thoms/g;
s/\bRamya Krishna\b/Ramya_Krishna/g;
s/\bUSL PDL\b/USL_PDL/g;
s/\bmotivating force\b/motivating_force/g;
s/\bShaka Hislop\b/Shaka_Hislop/g;
s/\bBrock s\b/Brock_s/g;
s/\bfertile valley\b/fertile_valley/g;
s/\bSlate Meagher Flom\b/Slate_Meagher_Flom/g;
s/\ba shelter for\b/a_shelter_for/g;
s/\bwas remastered\b/was_remastered/g;
s/\bgeodesic equation\b/geodesic_equation/g;
s/\bRadioland Murders\b/Radioland_Murders/g;
s/\bMust Pass\b/Must_Pass/g;
s/\b500 m\b/500_m/g;
s/\b59 minutes\b/59_minutes/g;
s/\bubiquitin-protein ligase\b/ubiquitin-protein_ligase/g;
s/\brose above\b/rose_above/g;
s/\bBorn on\b/Born_on/g;
s/\bthe end she\b/the_end_she/g;
s/\bRoxbury Massachusetts\b/Roxbury_Massachusetts/g;
s/\bFaulkes Telescope\b/Faulkes_Telescope/g;
s/\bpolice procedural\b/police_procedural/g;
s/\bstyle dwelling\b/style_dwelling/g;
s/\ban amplifier\b/an_amplifier/g;
s/\bmale counterpart\b/male_counterpart/g;
s/\bOrdnance Factories\b/Ordnance_Factories/g;
s/\bNate Marquardt\b/Nate_Marquardt/g;
s/\bPablo Milanés\b/Pablo_Milanés/g;
s/\bAfter one season\b/After_one_season/g;
s/\bthe ordination of\b/the_ordination_of/g;
s/\bThe Jeffersons\b/The_Jeffersons/g;
s/\bAng Panday\b/Ang_Panday/g;
s/\badvantageous for\b/advantageous_for/g;
s/\bJessica Chastain\b/Jessica_Chastain/g;
s/\bThe Role of\b/The_Role_of/g;
s/\brefugee camps\b/refugee_camps/g;
s/\bhis uncles\b/his_uncles/g;
s/\boverseas tour\b/overseas_tour/g;
s/\btelephone directories\b/telephone_directories/g;
s/\band Palestine Campaign\b/and_Palestine_Campaign/g;
s/\ban oven\b/an_oven/g;
s/\bidiopathic hypersomnia\b/idiopathic_hypersomnia/g;
s/\bThe Only Way\b/The_Only_Way/g;
s/\bless success\b/less_success/g;
s/\bsort that column\b/sort_that_column/g;
s/\bthe organisers\b/the_organisers/g;
s/\btheir sentences\b/their_sentences/g;
s/\bRika Ishikawa\b/Rika_Ishikawa/g;
s/\bDavid C\b/David_C/g;
s/\bMbit s\b/Mbit_s/g;
s/\bthe immediate vicinity\b/the_immediate_vicinity/g;
s/\bin 1460\b/in_1460/g;
s/\bin the months\b/in_the_months/g;
s/\bMemory Lane\b/Memory_Lane/g;
s/\bvolcanic tuff\b/volcanic_tuff/g;
s/\bA R Labs\b/A_R_Labs/g;
s/\bHoldings Berhad\b/Holdings_Berhad/g;
s/\benzymatic reactions\b/enzymatic_reactions/g;
s/\bCrişul Alb\b/Crişul_Alb/g;
s/\bspin-off series\b/spin-off_series/g;
s/\bGregorian Calendar\b/Gregorian_Calendar/g;
s/\bunderwent another\b/underwent_another/g;
s/\bബഹ ു.\b/ബഹ_ു./g;
s/\bcould hear\b/could_hear/g;
s/\bcharitable endeavors\b/charitable_endeavors/g;
s/\bMaraimalai Adigal\b/Maraimalai_Adigal/g;
s/\btravel guides\b/travel_guides/g;
s/\bBeitar Jerusalem\b/Beitar_Jerusalem/g;
s/\bGreen Goblin\b/Green_Goblin/g;
s/\bcars and motorcycles\b/cars_and_motorcycles/g;
s/\bhostages were\b/hostages_were/g;
s/\bqualifying games\b/qualifying_games/g;
s/\bKanyakumari district\b/Kanyakumari_district/g;
s/\bsegmented into\b/segmented_into/g;
s/\bhigh-income countries\b/high-income_countries/g;
s/\bNo 82\b/No_82/g;
s/\b€ 1\b/€_1/g;
s/\bdetection range\b/detection_range/g;
s/\ban incompetent\b/an_incompetent/g;
s/\bcontract expiring\b/contract_expiring/g;
s/\bCajanus cajan\b/Cajanus_cajan/g;
s/\bfelled by\b/felled_by/g;
s/\bin place to\b/in_place_to/g;
s/\bin Dnipropetrovsk\b/in_Dnipropetrovsk/g;
s/\bthe intent of\b/the_intent_of/g;
s/\bAras River\b/Aras_River/g;
s/\bRecording Arts\b/Recording_Arts/g;
s/\bPersona 4\b/Persona_4/g;
s/\bbalance sheet\b/balance_sheet/g;
s/\bin 2006 it\b/in_2006_it/g;
s/\bexpand rapidly\b/expand_rapidly/g;
s/\bthis thing\b/this_thing/g;
s/\bShe accepts\b/She_accepts/g;
s/\bWang Jing\b/Wang_Jing/g;
s/\bneighboring municipality\b/neighboring_municipality/g;
s/\bpilgrimage route\b/pilgrimage_route/g;
s/\bMunicipality Norrbotten\b/Municipality_Norrbotten/g;
s/\bNguyen Thi\b/Nguyen_Thi/g;
s/\ban award-winning\b/an_award-winning/g;
s/\bkm relay\b/km_relay/g;
s/\bfinancial meltdown\b/financial_meltdown/g;
s/\band Staff Course\b/and_Staff_Course/g;
s/\bOn 17\b/On_17/g;
s/\bcable system\b/cable_system/g;
s/\bLa Cité\b/La_Cité/g;
s/\bMetropolitan School District\b/Metropolitan_School_District/g;
s/\bMac computers\b/Mac_computers/g;
s/\bLionel Barrymore\b/Lionel_Barrymore/g;
s/\bFrom 1983\b/From_1983/g;
s/\bde Sanctis\b/de_Sanctis/g;
s/\bdomed roof\b/domed_roof/g;
s/\ba welfare state\b/a_welfare_state/g;
s/\bapplication developers\b/application_developers/g;
s/\bsmeared with\b/smeared_with/g;
s/\bCharlie Crist\b/Charlie_Crist/g;
s/\bTo establish\b/To_establish/g;
s/\b20 to 40\b/20_to_40/g;
s/\bjet fighters\b/jet_fighters/g;
s/\bmanual labour\b/manual_labour/g;
s/\bsubject to\b/subject_to/g;
s/\bconsulting firm\b/consulting_firm/g;
s/\bMirogoj Cemetery\b/Mirogoj_Cemetery/g;
s/\bEulogy Recordings\b/Eulogy_Recordings/g;
s/\bwas activated\b/was_activated/g;
s/\bValentina Tereshkova\b/Valentina_Tereshkova/g;
s/\bThese devices\b/These_devices/g;
s/\bthe common name\b/the_common_name/g;
s/\bPlayStation Home\b/PlayStation_Home/g;
s/\bthe upper\b/the_upper/g;
s/\bInformation System\b/Information_System/g;
s/\b200-metre freestyle\b/200-metre_freestyle/g;
s/\bGolden Valley\b/Golden_Valley/g;
s/\bdraws against\b/draws_against/g;
s/\b$4.4 billion\b/$4.4_billion/g;
s/\bMaharaja Sayajirao\b/Maharaja_Sayajirao/g;
s/\bsingles released\b/singles_released/g;
s/\bKanab Utah\b/Kanab_Utah/g;
s/\bfade into\b/fade_into/g;
s/\bthe frontman of\b/the_frontman_of/g;
s/\bPreacher Man\b/Preacher_Man/g;
s/\bcervical vertebra\b/cervical_vertebra/g;
s/\bcardboard boxes\b/cardboard_boxes/g;
s/\bBožena Němcová\b/Božena_Němcová/g;
s/\bcyclic group\b/cyclic_group/g;
s/\bNgāti Ruanui\b/Ngāti_Ruanui/g;
s/\bCyborg 009\b/Cyborg_009/g;
s/\bTrumbull Connecticut\b/Trumbull_Connecticut/g;
s/\bInsensato Coração\b/Insensato_Coração/g;
s/\bsurrogate mother\b/surrogate_mother/g;
s/\bGjergj Arianiti\b/Gjergj_Arianiti/g;
s/\bAbdul Qader\b/Abdul_Qader/g;
s/\blaws that\b/laws_that/g;
s/\breal ales\b/real_ales/g;
s/\bFighting Talk\b/Fighting_Talk/g;
s/\bMiloš Obrenović\b/Miloš_Obrenović/g;
s/\bYarlung Tsangpo\b/Yarlung_Tsangpo/g;
s/\bhigh technology\b/high_technology/g;
s/\bthis country\b/this_country/g;
s/\bLuft- und Raumfahrt\b/Luft-_und_Raumfahrt/g;
s/\bTV and film\b/TV_and_film/g;
s/\bfractured cheekbone\b/fractured_cheekbone/g;
s/\bportrait of\b/portrait_of/g;
s/\beither alone\b/either_alone/g;
s/\bKellogg Company\b/Kellogg_Company/g;
s/\b16th Karmapa\b/16th_Karmapa/g;
s/\bmy job\b/my_job/g;
s/\bwithout discrimination\b/without_discrimination/g;
s/\bde Borja\b/de_Borja/g;
s/\bpublic speech\b/public_speech/g;
s/\brapid intensification\b/rapid_intensification/g;
s/\bkept alive\b/kept_alive/g;
s/\bTV programme\b/TV_programme/g;
s/\bLukáš Dlouhý\b/Lukáš_Dlouhý/g;
s/\bthe backup quarterback\b/the_backup_quarterback/g;
s/\bthe third-best\b/the_third-best/g;
s/\bChess Congress\b/Chess_Congress/g;
s/\bAdirondack Northway\b/Adirondack_Northway/g;
s/\bTrier-Saarburg district\b/Trier-Saarburg_district/g;
s/\bsurvey vessel\b/survey_vessel/g;
s/\bJournals Online\b/Journals_Online/g;
s/\bneed special education\b/need_special_education/g;
s/\bVijay Anand\b/Vijay_Anand/g;
s/\bmay not\b/may_not/g;
s/\bJin s\b/Jin_s/g;
s/\bSportsChannel America\b/SportsChannel_America/g;
s/\bJim Steranko\b/Jim_Steranko/g;
s/\bTwenty-seventh Congress\b/Twenty-seventh_Congress/g;
s/\bmaxillary barbels\b/maxillary_barbels/g;
s/\bBanco Mercantil\b/Banco_Mercantil/g;
s/\bElysian Park\b/Elysian_Park/g;
s/\bthe clitoris\b/the_clitoris/g;
s/\bdistribution network\b/distribution_network/g;
s/\bprayed for\b/prayed_for/g;
s/\bThis also allows\b/This_also_allows/g;
s/\ba prince\b/a_prince/g;
s/\bAppreciation Society\b/Appreciation_Society/g;
s/\bthe fixed point\b/the_fixed_point/g;
s/\bJagathi Sreekumar\b/Jagathi_Sreekumar/g;
s/\btwo battleships\b/two_battleships/g;
s/\bFiscal Responsibility\b/Fiscal_Responsibility/g;
s/\bOther languages\b/Other_languages/g;
s/\bin Laos\b/in_Laos/g;
s/\bprovoked outrage\b/provoked_outrage/g;
s/\b30 7\b/30_7/g;
s/\bmodeled using\b/modeled_using/g;
s/\ba nameless\b/a_nameless/g;
s/\bAirbus A320s\b/Airbus_A320s/g;
s/\bin Division 3\b/in_Division_3/g;
s/\bMetallurgical Engineering\b/Metallurgical_Engineering/g;
s/\bnational sport\b/national_sport/g;
s/\b5th season\b/5th_season/g;
s/\bAlberto Sordi\b/Alberto_Sordi/g;
s/\bRNA-binding protein\b/RNA-binding_protein/g;
s/\bsodium hydroxide\b/sodium_hydroxide/g;
s/\bAntarctic krill\b/Antarctic_krill/g;
s/\bRahat Fateh\b/Rahat_Fateh/g;
s/\bculmination of\b/culmination_of/g;
s/\bno Michi\b/no_Michi/g;
s/\bpursuant to\b/pursuant_to/g;
s/\bhelp me\b/help_me/g;
s/\bcan sometimes\b/can_sometimes/g;
s/\bwritten in German\b/written_in_German/g;
s/\bthe ECHL\b/the_ECHL/g;
s/\bJudas Priest\b/Judas_Priest/g;
s/\bResearch Fellowship\b/Research_Fellowship/g;
s/\bfamily Clausiliidae\b/family_Clausiliidae/g;
s/\bwould still be\b/would_still_be/g;
s/\bgrade ranked\b/grade_ranked/g;
s/\bPrimary Education\b/Primary_Education/g;
s/\bsonnō jōi\b/sonnō_jōi/g;
s/\bsome 6 000\b/some_6_000/g;
s/\bslotted flaps\b/slotted_flaps/g;
s/\bAnother name for\b/Another_name_for/g;
s/\bconsidered taboo\b/considered_taboo/g;
s/\bless stringent\b/less_stringent/g;
s/\bsecurity officer\b/security_officer/g;
s/\bhas not played\b/has_not_played/g;
s/\bCommunity Association\b/Community_Association/g;
s/\btuberous sclerosis\b/tuberous_sclerosis/g;
s/\b180 kg\b/180_kg/g;
s/\bBircham Newton\b/Bircham_Newton/g;
s/\bMolecule Man\b/Molecule_Man/g;
s/\blush vegetation\b/lush_vegetation/g;
s/\b6th Viscount\b/6th_Viscount/g;
s/\bwarns her that\b/warns_her_that/g;
s/\bour senses\b/our_senses/g;
s/\bÓ Ceallaigh\b/Ó_Ceallaigh/g;
s/\bsolar photovoltaics\b/solar_photovoltaics/g;
s/\bfinds herself\b/finds_herself/g;
s/\b45 minute\b/45_minute/g;
s/\bNew Male Talent\b/New_Male_Talent/g;
s/\bbats are\b/bats_are/g;
s/\bparamilitary organisation\b/paramilitary_organisation/g;
s/\bAlan Smithee\b/Alan_Smithee/g;
s/\bAlan Shatter\b/Alan_Shatter/g;
s/\bPhiladelphia Mint\b/Philadelphia_Mint/g;
s/\bkill herself\b/kill_herself/g;
s/\bEddie s\b/Eddie_s/g;
s/\bThey Came\b/They_Came/g;
s/\bbiblical scholar\b/biblical_scholar/g;
s/\bowned it until\b/owned_it_until/g;
s/\bWesley Morris\b/Wesley_Morris/g;
s/\ba three-year\b/a_three-year/g;
s/\bGreen Team\b/Green_Team/g;
s/\bAfter examining\b/After_examining/g;
s/\bArseny Semionov\b/Arseny_Semionov/g;
s/\b063 for females\b/063_for_females/g;
s/\bpossessive suffix\b/possessive_suffix/g;
s/\bWild Hunt\b/Wild_Hunt/g;
s/\bsees through\b/sees_through/g;
s/\bTarxien Rainbows\b/Tarxien_Rainbows/g;
s/\bprevented from\b/prevented_from/g;
s/\bbefore election day\b/before_election_day/g;
s/\bin 47 games\b/in_47_games/g;
s/\btax on\b/tax_on/g;
s/\bBusiness Process\b/Business_Process/g;
s/\bBanat of Temeschwar\b/Banat_of_Temeschwar/g;
s/\bOzone Layer Protection\b/Ozone_Layer_Protection/g;
s/\bTorrie Wilson\b/Torrie_Wilson/g;
s/\bDe Aar\b/De_Aar/g;
s/\bNASCAR Busch\b/NASCAR_Busch/g;
s/\bProduction designer\b/Production_designer/g;
s/\bGarcía born\b/García_born/g;
s/\bLana Parrilla\b/Lana_Parrilla/g;
s/\b255 255\b/255_255/g;
s/\bdevoted himself to\b/devoted_himself_to/g;
s/\bsnippet of\b/snippet_of/g;
s/\bmurex snails\b/murex_snails/g;
s/\bpublic transit\b/public_transit/g;
s/\btakes place\b/takes_place/g;
s/\bnearly circular\b/nearly_circular/g;
s/\bDiamond Jaxx\b/Diamond_Jaxx/g;
s/\b්‍ ර\b/්‍_ර/g;
s/\bacting skills\b/acting_skills/g;
s/\bthe protagonist\b/the_protagonist/g;
s/\bvoiced concern\b/voiced_concern/g;
s/\bcloser inspection\b/closer_inspection/g;
s/\bis not normally\b/is_not_normally/g;
s/\bwhich 28 8\b/which_28_8/g;
s/\bgastropod mollusc\b/gastropod_mollusc/g;
s/\bYeh Rishta\b/Yeh_Rishta/g;
s/\bDavid Ben-Gurion\b/David_Ben-Gurion/g;
s/\becclesiastical court\b/ecclesiastical_court/g;
s/\bDirty Laundry\b/Dirty_Laundry/g;
s/\bSeven Cities\b/Seven_Cities/g;
s/\bcomedy pilot\b/comedy_pilot/g;
s/\bsend them\b/send_them/g;
s/\blogging road\b/logging_road/g;
s/\bLeon Schlesinger\b/Leon_Schlesinger/g;
s/\bWhaling Company\b/Whaling_Company/g;
s/\bMetropolitan Police\b/Metropolitan_Police/g;
s/\bat Georgetown\b/at_Georgetown/g;
s/\bMidi-Pyrénées France\b/Midi-Pyrénées_France/g;
s/\bKokuritsu Kōen\b/Kokuritsu_Kōen/g;
s/\bSantosh Trophy\b/Santosh_Trophy/g;
s/\bdistressed by\b/distressed_by/g;
s/\bQuatre Bornes\b/Quatre_Bornes/g;
s/\bsimilar in appearance\b/similar_in_appearance/g;
s/\bproton transfer\b/proton_transfer/g;
s/\ball-round performance\b/all-round_performance/g;
s/\bcould provide\b/could_provide/g;
s/\bPaizo Publishing s\b/Paizo_Publishing_s/g;
s/\bDDR SDRAM\b/DDR_SDRAM/g;
s/\bNHRA Mello Yello\b/NHRA_Mello_Yello/g;
s/\bAlfred I duPont\b/Alfred_I_duPont/g;
s/\bLubycza Królewska\b/Lubycza_Królewska/g;
s/\bathletic fields\b/athletic_fields/g;
s/\bfateful decision\b/fateful_decision/g;
s/\bgradually become\b/gradually_become/g;
s/\bsniper rifles\b/sniper_rifles/g;
s/\bNBA Live\b/NBA_Live/g;
s/\bNature Sanctuary\b/Nature_Sanctuary/g;
s/\bmusical artist\b/musical_artist/g;
s/\bbefore retiring\b/before_retiring/g;
s/\brelieve overcrowding\b/relieve_overcrowding/g;
s/\bArkadelphia Arkansas\b/Arkadelphia_Arkansas/g;
s/\bvibrational energy\b/vibrational_energy/g;
s/\bTylwyth Teg\b/Tylwyth_Teg/g;
s/\bShaikh Hamad\b/Shaikh_Hamad/g;
s/\b় দ\b/়_দ/g;
s/\bSymbolic Logic\b/Symbolic_Logic/g;
s/\bBuckminster Fuller\b/Buckminster_Fuller/g;
s/\ball sources ranked\b/all_sources_ranked/g;
s/\bMarine Force\b/Marine_Force/g;
s/\bguest star\b/guest_star/g;
s/\bpilgrimage to\b/pilgrimage_to/g;
s/\blimiting or prohibiting\b/limiting_or_prohibiting/g;
s/\bJalal Talabani\b/Jalal_Talabani/g;
s/\bSheepshead Bay\b/Sheepshead_Bay/g;
s/\b34th season\b/34th_season/g;
s/\bbroadcast tower\b/broadcast_tower/g;
s/\bat the 2012\b/at_the_2012/g;
s/\bDIY ethic\b/DIY_ethic/g;
s/\bExtended Mix\b/Extended_Mix/g;
s/\bbuzzer beater\b/buzzer_beater/g;
s/\bDheeran Chinnamalai\b/Dheeran_Chinnamalai/g;
s/\bneglected tropical diseases\b/neglected_tropical_diseases/g;
s/\btheir decisions\b/their_decisions/g;
s/\bSociété entomologique\b/Société_entomologique/g;
s/\bFreddie Hubbard\b/Freddie_Hubbard/g;
s/\bspangled grey plumage\b/spangled_grey_plumage/g;
s/\bTom Thumb\b/Tom_Thumb/g;
s/\bduring the 1972\b/during_the_1972/g;
s/\bThe Town of\b/The_Town_of/g;
s/\bendangered animals\b/endangered_animals/g;
s/\bBonnie Hunt\b/Bonnie_Hunt/g;
s/\b00 P M\b/00_P_M/g;
s/\b8th centuries\b/8th_centuries/g;
s/\bIf these\b/If_these/g;
s/\bSpecial Effects\b/Special_Effects/g;
s/\bNational Coalition\b/National_Coalition/g;
s/\bThe constitution\b/The_constitution/g;
s/\bAwami League\b/Awami_League/g;
s/\bwater buffalo\b/water_buffalo/g;
s/\bEsoteric Buddhism\b/Esoteric_Buddhism/g;
s/\bThis increases\b/This_increases/g;
s/\bThe Incredible\b/The_Incredible/g;
s/\bBGO Records\b/BGO_Records/g;
s/\bAaronic priesthood\b/Aaronic_priesthood/g;
s/\binformation visualization\b/information_visualization/g;
s/\bcharacters names\b/characters_names/g;
s/\bthe name change\b/the_name_change/g;
s/\b– 91\b/–_91/g;
s/\bcardiac tamponade\b/cardiac_tamponade/g;
s/\bbinomial name\b/binomial_name/g;
s/\bEuropean Americans\b/European_Americans/g;
s/\bGary Bettman\b/Gary_Bettman/g;
s/\bfall winter\b/fall_winter/g;
s/\bAerolíneas Argentinas\b/Aerolíneas_Argentinas/g;
s/\bper 0 01\b/per_0_01/g;
s/\bWissenschaft des Judentums\b/Wissenschaft_des_Judentums/g;
s/\bpaid-up capital\b/paid-up_capital/g;
s/\bMarquee Club\b/Marquee_Club/g;
s/\bnon-residential buildings\b/non-residential_buildings/g;
s/\bepisode Recurring\b/episode_Recurring/g;
s/\becclesiastical discipline\b/ecclesiastical_discipline/g;
s/\bLa Bouche\b/La_Bouche/g;
s/\bJoan Gamper\b/Joan_Gamper/g;
s/\bTony Trabert\b/Tony_Trabert/g;
s/\bMain Range\b/Main_Range/g;
s/\bEamonn Holmes\b/Eamonn_Holmes/g;
s/\bForschungsanstalt für\b/Forschungsanstalt_für/g;
s/\bCardiff Castle\b/Cardiff_Castle/g;
s/\bTheodor Mommsen\b/Theodor_Mommsen/g;
s/\bChips Rafferty\b/Chips_Rafferty/g;
s/\bLi Keqiang\b/Li_Keqiang/g;
s/\bgrunge movement\b/grunge_movement/g;
s/\bOrthodox Church\b/Orthodox_Church/g;
s/\bthe caldera\b/the_caldera/g;
s/\bputting down\b/putting_down/g;
s/\bFrank Herbert s\b/Frank_Herbert_s/g;
s/\bPrimer Impacto\b/Primer_Impacto/g;
s/\bSaratoga CV-3\b/Saratoga_CV-3/g;
s/\bseveral CDs\b/several_CDs/g;
s/\bComputer Society\b/Computer_Society/g;
s/\bFast Forward\b/Fast_Forward/g;
s/\bChris Eubank\b/Chris_Eubank/g;
s/\bHe also taught\b/He_also_taught/g;
s/\bDiet of Worms\b/Diet_of_Worms/g;
s/\bdrawn against\b/drawn_against/g;
s/\ban interesting\b/an_interesting/g;
s/\bfree online\b/free_online/g;
s/\band community organizations\b/and_community_organizations/g;
s/\bpsychiatric conditions\b/psychiatric_conditions/g;
s/\bMontgomery C Meigs\b/Montgomery_C_Meigs/g;
s/\bBroome Street\b/Broome_Street/g;
s/\bBachao Andolan\b/Bachao_Andolan/g;
s/\bAnna Politkovskaya\b/Anna_Politkovskaya/g;
s/\bShe had been\b/She_had_been/g;
s/\bthree-body problem\b/three-body_problem/g;
s/\bMorbid Angel\b/Morbid_Angel/g;
s/\bHarbin Heilongjiang\b/Harbin_Heilongjiang/g;
s/\bKeith Forsey\b/Keith_Forsey/g;
s/\b” and “\b/”_and_“/g;
s/\bUpper Peninsula\b/Upper_Peninsula/g;
s/\bcharacters are\b/characters_are/g;
s/\bNawab Nazim\b/Nawab_Nazim/g;
s/\bthe efforts of\b/the_efforts_of/g;
s/\bbrought with it\b/brought_with_it/g;
s/\bThái Tông\b/Thái_Tông/g;
s/\bdomestic cats\b/domestic_cats/g;
s/\bSino-Tibetan language\b/Sino-Tibetan_language/g;
s/\bsymbols are\b/symbols_are/g;
s/\bdu Capitole\b/du_Capitole/g;
s/\bDivinity School\b/Divinity_School/g;
s/\bhovered around\b/hovered_around/g;
s/\bা দ\b/া_দ/g;
s/\bcharitable institution\b/charitable_institution/g;
s/\bLotus corniculatus\b/Lotus_corniculatus/g;
s/\bHalit Refiğ\b/Halit_Refiğ/g;
s/\blicense plates\b/license_plates/g;
s/\ba service SaaS\b/a_service_SaaS/g;
s/\bwas positioned\b/was_positioned/g;
s/\bthe hurricane\b/the_hurricane/g;
s/\bnatural scenery\b/natural_scenery/g;
s/\bsix-song EP\b/six-song_EP/g;
s/\bWhite Americans\b/White_Americans/g;
s/\bflowers are\b/flowers_are/g;
s/\bwas self-released\b/was_self-released/g;
s/\bZoran Janković\b/Zoran_Janković/g;
s/\bHe enjoys\b/He_enjoys/g;
s/\bCradley Heath\b/Cradley_Heath/g;
s/\bdetected by\b/detected_by/g;
s/\bDe Oro\b/De_Oro/g;
s/\btechniques are\b/techniques_are/g;
s/\bRussian Илья\b/Russian_Илья/g;
s/\band elected to\b/and_elected_to/g;
s/\bmillion records\b/million_records/g;
s/\bUp and Down\b/Up_and_Down/g;
s/\bBhupen Hazarika\b/Bhupen_Hazarika/g;
s/\bour economy\b/our_economy/g;
s/\bConseco Fieldhouse\b/Conseco_Fieldhouse/g;
s/\bTransverse Ranges\b/Transverse_Ranges/g;
s/\bextradited to\b/extradited_to/g;
s/\bCab Calloway\b/Cab_Calloway/g;
s/\bphage display\b/phage_display/g;
s/\bจ ั\b/จ_ั/g;
s/\bStrategic Wing\b/Strategic_Wing/g;
s/\bIdris Elba\b/Idris_Elba/g;
s/\bintended victim\b/intended_victim/g;
s/\bso rapidly\b/so_rapidly/g;
s/\bgoverned by\b/governed_by/g;
s/\bF91 Dudelange\b/F91_Dudelange/g;
s/\bher masts\b/her_masts/g;
s/\bDiamond Sutra\b/Diamond_Sutra/g;
s/\bcycled through\b/cycled_through/g;
s/\bGMA Telebabad\b/GMA_Telebabad/g;
s/\badvisor to\b/advisor_to/g;
s/\bwould facilitate\b/would_facilitate/g;
s/\b– 1837\b/–_1837/g;
s/\bJesse Pinkman\b/Jesse_Pinkman/g;
s/\bprayer beads\b/prayer_beads/g;
s/\bprecipitated by\b/precipitated_by/g;
s/\bprotest marches\b/protest_marches/g;
s/\bMarty McSorley\b/Marty_McSorley/g;
s/\bDieterich Buxtehude\b/Dieterich_Buxtehude/g;
s/\bMark Coleman\b/Mark_Coleman/g;
s/\bLeipziger Platz\b/Leipziger_Platz/g;
s/\bthird-placed team\b/third-placed_team/g;
s/\bHindu Brahmin\b/Hindu_Brahmin/g;
s/\bloved it\b/loved_it/g;
s/\bDorje Shugden\b/Dorje_Shugden/g;
s/\bSleeping Dogs\b/Sleeping_Dogs/g;
s/\buniformity of\b/uniformity_of/g;
s/\bHumanae vitae\b/Humanae_vitae/g;
s/\bMick McCarthy\b/Mick_McCarthy/g;
s/\bAşk-ı Memnu\b/Aşk-ı_Memnu/g;
s/\bepiscopi vagantes\b/episcopi_vagantes/g;
s/\bQuack Pack\b/Quack_Pack/g;
s/\bIllegal immigration\b/Illegal_immigration/g;
s/\band index finger\b/and_index_finger/g;
s/\bthe tagline\b/the_tagline/g;
s/\bCarbondale Area\b/Carbondale_Area/g;
s/\bBow Street\b/Bow_Street/g;
s/\btake photos\b/take_photos/g;
s/\ba light-hearted\b/a_light-hearted/g;
s/\bDetective Story\b/Detective_Story/g;
s/\bLord Derby\b/Lord_Derby/g;
s/\bcardboard cutouts\b/cardboard_cutouts/g;
s/\bsaved from\b/saved_from/g;
s/\ban electorate\b/an_electorate/g;
s/\bBruce Spizer\b/Bruce_Spizer/g;
s/\bwalking tour\b/walking_tour/g;
s/\bbout with\b/bout_with/g;
s/\bcorpora cavernosa\b/corpora_cavernosa/g;
s/\bjazz clarinetist\b/jazz_clarinetist/g;
s/\bDemocratic primary with\b/Democratic_primary_with/g;
s/\bOrder Restoration Council\b/Order_Restoration_Council/g;
s/\bumbilical cord\b/umbilical_cord/g;
s/\bNaval Officer\b/Naval_Officer/g;
s/\bSin Salida\b/Sin_Salida/g;
s/\bfield crops\b/field_crops/g;
s/\bDigital Economy\b/Digital_Economy/g;
s/\bthe TTC\b/the_TTC/g;
s/\blimited-access freeway\b/limited-access_freeway/g;
s/\bashlar masonry\b/ashlar_masonry/g;
s/\boccupied Europe\b/occupied_Europe/g;
s/\bthe air with\b/the_air_with/g;
s/\bin the 1963\b/in_the_1963/g;
s/\ba plantation\b/a_plantation/g;
s/\ba Scottish former\b/a_Scottish_former/g;
s/\bAndy s\b/Andy_s/g;
s/\bcompetes against\b/competes_against/g;
s/\bits extensive\b/its_extensive/g;
s/\bMetropolis Records\b/Metropolis_Records/g;
s/\bSO4 2\b/SO4_2/g;
s/\bcover photograph\b/cover_photograph/g;
s/\blatissimus dorsi\b/latissimus_dorsi/g;
s/\btheir daughters\b/their_daughters/g;
s/\bAnantnag district\b/Anantnag_district/g;
s/\bTony Wilson\b/Tony_Wilson/g;
s/\bLeaving Cert\b/Leaving_Cert/g;
s/\bjudicial commission\b/judicial_commission/g;
s/\bNassau Inter-County Express\b/Nassau_Inter-County_Express/g;
s/\bpassed on\b/passed_on/g;
s/\bcut from\b/cut_from/g;
s/\bChanneled Scablands\b/Channeled_Scablands/g;
s/\bMalcolm Bradbury\b/Malcolm_Bradbury/g;
s/\brespiratory muscles\b/respiratory_muscles/g;
s/\bWorld Group\b/World_Group/g;
s/\bAlexei Mikhailovich\b/Alexei_Mikhailovich/g;
s/\bWater Management\b/Water_Management/g;
s/\bbout via\b/bout_via/g;
s/\bdrumming duties\b/drumming_duties/g;
s/\bsupport up to\b/support_up_to/g;
s/\bno substantial\b/no_substantial/g;
s/\btwo extra\b/two_extra/g;
s/\bAdventure Gamers\b/Adventure_Gamers/g;
s/\bat hooker\b/at_hooker/g;
s/\bNotitia Episcopatuum\b/Notitia_Episcopatuum/g;
s/\bboth genders\b/both_genders/g;
s/\bThe first song\b/The_first_song/g;
s/\bevangelistic work\b/evangelistic_work/g;
s/\bLittle Shop\b/Little_Shop/g;
s/\blearn to\b/learn_to/g;
s/\bthe highlands\b/the_highlands/g;
s/\bpredicated on\b/predicated_on/g;
s/\bLadybower Reservoir\b/Ladybower_Reservoir/g;
s/\bNick Lowe\b/Nick_Lowe/g;
s/\bQualification Tournament\b/Qualification_Tournament/g;
s/\bhouseholds watching\b/households_watching/g;
s/\bItzhak Perlman\b/Itzhak_Perlman/g;
s/\bTous les\b/Tous_les/g;
s/\bDhaulagiri Zone\b/Dhaulagiri_Zone/g;
s/\bThe southernmost\b/The_southernmost/g;
s/\bMonoclonal antibodies\b/Monoclonal_antibodies/g;
s/\bGlitch Mob\b/Glitch_Mob/g;
s/\bwhat was happening\b/what_was_happening/g;
s/\bbaal teshuva\b/baal_teshuva/g;
s/\bMultiple studies\b/Multiple_studies/g;
s/\bThe Venetian\b/The_Venetian/g;
s/\btidal waves\b/tidal_waves/g;
s/\bmastermind behind\b/mastermind_behind/g;
s/\bfossil footprints\b/fossil_footprints/g;
s/\bhis murder\b/his_murder/g;
s/\bLa Niña\b/La_Niña/g;
s/\bMi irabawi\b/Mi_irabawi/g;
s/\btake time off\b/take_time_off/g;
s/\bSavonlinna Opera Festival\b/Savonlinna_Opera_Festival/g;
s/\bNicolas Soult\b/Nicolas_Soult/g;
s/\bswath of\b/swath_of/g;
s/\bSarath Kumar\b/Sarath_Kumar/g;
s/\brising to\b/rising_to/g;
s/\brotary converters\b/rotary_converters/g;
s/\bhis innocence\b/his_innocence/g;
s/\bSt Anselm\b/St_Anselm/g;
s/\bThey subsequently\b/They_subsequently/g;
s/\bxeroderma pigmentosum\b/xeroderma_pigmentosum/g;
s/\bPittsburgh Pipers\b/Pittsburgh_Pipers/g;
s/\bsynthetic rubber\b/synthetic_rubber/g;
s/\breacted negatively to\b/reacted_negatively_to/g;
s/\bTeen Vogue\b/Teen_Vogue/g;
s/\bRoast Beef\b/Roast_Beef/g;
s/\bMorgan who\b/Morgan_who/g;
s/\bHebrew name\b/Hebrew_name/g;
s/\bapologizing for\b/apologizing_for/g;
s/\bAlma Ata\b/Alma_Ata/g;
s/\bAll-Big East\b/All-Big_East/g;
s/\bR $297.00 respectively\b/R_$297.00_respectively/g;
s/\bCurrent Affairs\b/Current_Affairs/g;
s/\bthe fields of\b/the_fields_of/g;
s/\bHead coach\b/Head_coach/g;
s/\bFundamental Orders\b/Fundamental_Orders/g;
s/\bdaughter Dorothy\b/daughter_Dorothy/g;
s/\bthe two-year middle\b/the_two-year_middle/g;
s/\bGalleria Borghese\b/Galleria_Borghese/g;
s/\bhow long\b/how_long/g;
s/\bFabrizio Miccoli\b/Fabrizio_Miccoli/g;
s/\bOsteopathic Association\b/Osteopathic_Association/g;
s/\bdrops to\b/drops_to/g;
s/\bWill Always\b/Will_Always/g;
s/\bState University OSU\b/State_University_OSU/g;
s/\bA Voyage\b/A_Voyage/g;
s/\bPublic Integrity\b/Public_Integrity/g;
s/\bwas a Croatian\b/was_a_Croatian/g;
s/\bDirect Democracy\b/Direct_Democracy/g;
s/\bMemorial Tollway\b/Memorial_Tollway/g;
s/\bKenny Burrell\b/Kenny_Burrell/g;
s/\btwo competitors\b/two_competitors/g;
s/\bWound Badge\b/Wound_Badge/g;
s/\ba duel\b/a_duel/g;
s/\bDante Alighieri\b/Dante_Alighieri/g;
s/\bWorld Summit\b/World_Summit/g;
s/\band bassist\b/and_bassist/g;
s/\bBrees completed\b/Brees_completed/g;
s/\bRed Crow\b/Red_Crow/g;
s/\btin miners\b/tin_miners/g;
s/\bRookery Nook\b/Rookery_Nook/g;
s/\bsigned for\b/signed_for/g;
s/\bState Hermitage\b/State_Hermitage/g;
s/\bthe skies\b/the_skies/g;
s/\bCambyses II\b/Cambyses_II/g;
s/\bे ट\b/े_ट/g;
s/\bdecorations are\b/decorations_are/g;
s/\bZhenguo Circuit 鎮國\b/Zhenguo_Circuit_鎮國/g;
s/\bMidAmerican Energy\b/MidAmerican_Energy/g;
s/\bsmart TVs\b/smart_TVs/g;
s/\bthe pitch\b/the_pitch/g;
s/\bMiddleweight Champion\b/Middleweight_Champion/g;
s/\bAp Lei Chau\b/Ap_Lei_Chau/g;
s/\bjoint statement\b/joint_statement/g;
s/\b20th Street\b/20th_Street/g;
s/\bAttitude Era\b/Attitude_Era/g;
s/\bcivil liberties\b/civil_liberties/g;
s/\bNational Enquirer\b/National_Enquirer/g;
s/\bfinish as runners-up\b/finish_as_runners-up/g;
s/\bany specific\b/any_specific/g;
s/\bcoordination complexes\b/coordination_complexes/g;
s/\bthe election with\b/the_election_with/g;
s/\bSatpura Range\b/Satpura_Range/g;
s/\bBart and Lisa\b/Bart_and_Lisa/g;
s/\bPompano Beach\b/Pompano_Beach/g;
s/\bthe actual\b/the_actual/g;
s/\bHittite Empire\b/Hittite_Empire/g;
s/\bFree Gaza Movement\b/Free_Gaza_Movement/g;
s/\bFritz Kreisler\b/Fritz_Kreisler/g;
s/\bGreat Heathen Army\b/Great_Heathen_Army/g;
s/\bEndre Ady\b/Endre_Ady/g;
s/\bJustyna Steczkowska\b/Justyna_Steczkowska/g;
s/\bkeeping track\b/keeping_track/g;
s/\ba murderer\b/a_murderer/g;
s/\bis a Somali\b/is_a_Somali/g;
s/\bAtlantic Avenue\b/Atlantic_Avenue/g;
s/\bmortal world\b/mortal_world/g;
s/\ban industrial\b/an_industrial/g;
s/\bthe Heritage Foundation\b/the_Heritage_Foundation/g;
s/\bApopka Florida\b/Apopka_Florida/g;
s/\bwould soon be\b/would_soon_be/g;
s/\bthe murder scene\b/the_murder_scene/g;
s/\bHeltah Skeltah\b/Heltah_Skeltah/g;
s/\bwild mushrooms\b/wild_mushrooms/g;
s/\bdu Pré\b/du_Pré/g;
s/\bKeke Palmer\b/Keke_Palmer/g;
s/\bbroken nose\b/broken_nose/g;
s/\bGianfranco Fini\b/Gianfranco_Fini/g;
s/\bJim Keltner\b/Jim_Keltner/g;
s/\bDavey Richards\b/Davey_Richards/g;
s/\bmathematical equations\b/mathematical_equations/g;
s/\bCommonwealth Foundation\b/Commonwealth_Foundation/g;
s/\bfamily Scissurellidae\b/family_Scissurellidae/g;
s/\blowland areas\b/lowland_areas/g;
s/\bInducted into\b/Inducted_into/g;
s/\badministrative personnel\b/administrative_personnel/g;
s/\bwould generally be\b/would_generally_be/g;
s/\bBorough Alaska\b/Borough_Alaska/g;
s/\bbrine shrimp\b/brine_shrimp/g;
s/\bheated arguments\b/heated_arguments/g;
s/\bagricultural labourers\b/agricultural_labourers/g;
s/\ba vast\b/a_vast/g;
s/\bin the 1976\b/in_the_1976/g;
s/\bFlemington Racecourse\b/Flemington_Racecourse/g;
s/\bBaronetcy of\b/Baronetcy_of/g;
s/\bLord Louis Mountbatten\b/Lord_Louis_Mountbatten/g;
s/\bdistorted guitar\b/distorted_guitar/g;
s/\bBricklayers Arms\b/Bricklayers_Arms/g;
s/\bBirkenfeld district\b/Birkenfeld_district/g;
s/\bgrow vegetables\b/grow_vegetables/g;
s/\bSlate Magazine\b/Slate_Magazine/g;
s/\btrimethoprim sulfamethoxazole\b/trimethoprim_sulfamethoxazole/g;
s/\ba waiver\b/a_waiver/g;
s/\bNovi Beograd\b/Novi_Beograd/g;
s/\breflecting on\b/reflecting_on/g;
s/\bBetween 1968\b/Between_1968/g;
s/\bHamilton Spectator\b/Hamilton_Spectator/g;
s/\bprepares to\b/prepares_to/g;
s/\bcollections including\b/collections_including/g;
s/\blaid out for\b/laid_out_for/g;
s/\bmoist forest\b/moist_forest/g;
s/\bfabulously wealthy\b/fabulously_wealthy/g;
s/\bFourteen teams\b/Fourteen_teams/g;
s/\bwas destroyed on\b/was_destroyed_on/g;
s/\bHải Phòng\b/Hải_Phòng/g;
s/\bher right leg\b/her_right_leg/g;
s/\ba family of\b/a_family_of/g;
s/\bCountess Palatine\b/Countess_Palatine/g;
s/\bYnys Môn\b/Ynys_Môn/g;
s/\bWestminster Choir\b/Westminster_Choir/g;
s/\bthe Pleiades\b/the_Pleiades/g;
s/\bcharging station\b/charging_station/g;
s/\bAttorneys General\b/Attorneys_General/g;
s/\bSaint James\b/Saint_James/g;
s/\bgeneral anesthesia\b/general_anesthesia/g;
s/\bcold-blooded murder\b/cold-blooded_murder/g;
s/\bAdam Clayton\b/Adam_Clayton/g;
s/\bmentally impaired\b/mentally_impaired/g;
s/\bResearch Lab\b/Research_Lab/g;
s/\bMazhabi Sikhs\b/Mazhabi_Sikhs/g;
s/\bthe reaction mixture\b/the_reaction_mixture/g;
s/\bthe church\b/the_church/g;
s/\bCurb Your Enthusiasm\b/Curb_Your_Enthusiasm/g;
s/\bDallas Mavericks\b/Dallas_Mavericks/g;
s/\bHeyting algebra\b/Heyting_algebra/g;
s/\bbefore later joining\b/before_later_joining/g;
s/\bacts on\b/acts_on/g;
s/\bCFDA Vogue\b/CFDA_Vogue/g;
s/\bpolygamous marriages\b/polygamous_marriages/g;
s/\bCindy Crawford\b/Cindy_Crawford/g;
s/\bའ ི་\b/འ_ི་/g;
s/\breport card\b/report_card/g;
s/\bLe roi\b/Le_roi/g;
s/\b599 GTB\b/599_GTB/g;
s/\band research activities\b/and_research_activities/g;
s/\bEdna Krabappel\b/Edna_Krabappel/g;
s/\bbiological weapon\b/biological_weapon/g;
s/\bEdith Sitwell\b/Edith_Sitwell/g;
s/\bSkinny Puppy\b/Skinny_Puppy/g;
s/\bleads into\b/leads_into/g;
s/\bLindsey district\b/Lindsey_district/g;
s/\bwe suppose\b/we_suppose/g;
s/\b60 minutes\b/60_minutes/g;
s/\borders her to\b/orders_her_to/g;
s/\bcomes into\b/comes_into/g;
s/\bthe Colombo Plan\b/the_Colombo_Plan/g;
s/\b20H 20Lienhard\b/20H_20Lienhard/g;
s/\bIn 1613\b/In_1613/g;
s/\bErnst Lubitsch\b/Ernst_Lubitsch/g;
s/\bits tributary\b/its_tributary/g;
s/\bclips from\b/clips_from/g;
s/\bSeattle Mariners\b/Seattle_Mariners/g;
s/\bcharitable causes\b/charitable_causes/g;
s/\bConfucianism Taoism\b/Confucianism_Taoism/g;
s/\bbrought prosperity\b/brought_prosperity/g;
s/\bAir Express\b/Air_Express/g;
s/\bcloseness to\b/closeness_to/g;
s/\bgreater honeyguide\b/greater_honeyguide/g;
s/\bsurvived by\b/survived_by/g;
s/\bnatural satellites\b/natural_satellites/g;
s/\bat Burnley\b/at_Burnley/g;
s/\bDel Mastro\b/Del_Mastro/g;
s/\b400 feet\b/400_feet/g;
s/\bGuest Conductor\b/Guest_Conductor/g;
s/\bThe vehicle\b/The_vehicle/g;
s/\bFazlul Haque\b/Fazlul_Haque/g;
s/\bPerfection of Wisdom\b/Perfection_of_Wisdom/g;
s/\ba platoon\b/a_platoon/g;
s/\bthree gradings given\b/three_gradings_given/g;
s/\bMarawi City\b/Marawi_City/g;
s/\bScott Pilgrim\b/Scott_Pilgrim/g;
s/\bscoring 13\b/scoring_13/g;
s/\bAdrian Willaert\b/Adrian_Willaert/g;
s/\brecruitment of\b/recruitment_of/g;
s/\bDejan Lovren\b/Dejan_Lovren/g;
s/\bWalled Lake\b/Walled_Lake/g;
s/\bAAMI Park\b/AAMI_Park/g;
s/\bMountstuart Elphinstone\b/Mountstuart_Elphinstone/g;
s/\bholding that\b/holding_that/g;
s/\braising awareness\b/raising_awareness/g;
s/\bless skilled\b/less_skilled/g;
s/\bCharlie Chan\b/Charlie_Chan/g;
s/\ba front for\b/a_front_for/g;
s/\bRNA and DNA\b/RNA_and_DNA/g;
s/\bStonewall Riots\b/Stonewall_Riots/g;
s/\bBob Gainey\b/Bob_Gainey/g;
s/\bMystic Seaport\b/Mystic_Seaport/g;
s/\bWest Was\b/West_Was/g;
s/\bEarth s\b/Earth_s/g;
s/\bSki jumping\b/Ski_jumping/g;
s/\bMy Voice\b/My_Voice/g;
s/\bHelmut Zemo\b/Helmut_Zemo/g;
s/\bStrategic Missile\b/Strategic_Missile/g;
s/\bprepare him for\b/prepare_him_for/g;
s/\bBroadcast Center\b/Broadcast_Center/g;
s/\band General Dynamics\b/and_General_Dynamics/g;
s/\bNFL season\b/NFL_season/g;
s/\blongtime collaborators\b/longtime_collaborators/g;
s/\bvan Loo\b/van_Loo/g;
s/\bmarginalized groups\b/marginalized_groups/g;
s/\bArt Direction\b/Art_Direction/g;
s/\bMost Popular Newcomer\b/Most_Popular_Newcomer/g;
s/\bPopulation 2013 est\b/Population_2013_est/g;
s/\ban editorial\b/an_editorial/g;
s/\bPhilip Seymour Hoffman\b/Philip_Seymour_Hoffman/g;
s/\bTeenage Fanclub\b/Teenage_Fanclub/g;
s/\bPublisher M H\b/Publisher_M_H/g;
s/\bthe butt of\b/the_butt_of/g;
s/\bthe area that\b/the_area_that/g;
s/\bjust aft\b/just_aft/g;
s/\bcommercial vehicles\b/commercial_vehicles/g;
s/\bBlondie s\b/Blondie_s/g;
s/\bbasketball competitions\b/basketball_competitions/g;
s/\bParachrostiinae 1867 1-136\b/Parachrostiinae_1867_1-136/g;
s/\bTonbridge and Malling\b/Tonbridge_and_Malling/g;
s/\bUsha Uthup\b/Usha_Uthup/g;
s/\bDaimler Fleetline\b/Daimler_Fleetline/g;
s/\bSydney Sixers\b/Sydney_Sixers/g;
s/\b40th minute\b/40th_minute/g;
s/\bdone via\b/done_via/g;
s/\band engineered by\b/and_engineered_by/g;
s/\bthirteenth season\b/thirteenth_season/g;
s/\bPharmaceutical Sciences\b/Pharmaceutical_Sciences/g;
s/\bcontributions towards\b/contributions_towards/g;
s/\ban EF3\b/an_EF3/g;
s/\bhard line\b/hard_line/g;
s/\bAntonov An-24\b/Antonov_An-24/g;
s/\bShip Island\b/Ship_Island/g;
s/\btrade unions\b/trade_unions/g;
s/\bEddie Guerrero\b/Eddie_Guerrero/g;
s/\bA penumbral\b/A_penumbral/g;
s/\ba bribe\b/a_bribe/g;
s/\bSouth Waziristan\b/South_Waziristan/g;
s/\bportrait photography\b/portrait_photography/g;
s/\bChoral Festival\b/Choral_Festival/g;
s/\bSouthern California\b/Southern_California/g;
s/\bHockey East\b/Hockey_East/g;
s/\bNo 51\b/No_51/g;
s/\bSharni Vinson\b/Sharni_Vinson/g;
s/\btrium liberorum\b/trium_liberorum/g;
s/\bwill probably\b/will_probably/g;
s/\bprelate who\b/prelate_who/g;
s/\bnorth London\b/north_London/g;
s/\bThe relationship of\b/The_relationship_of/g;
s/\bwould write\b/would_write/g;
s/\bEventually he\b/Eventually_he/g;
s/\bindigenous groups\b/indigenous_groups/g;
s/\bIndian classical\b/Indian_classical/g;
s/\bconstitutional amendment\b/constitutional_amendment/g;
s/\bphysical abuse\b/physical_abuse/g;
s/\bbombing missions\b/bombing_missions/g;
s/\bIn 1776\b/In_1776/g;
s/\bSaturday night\b/Saturday_night/g;
s/\bVajrayana Buddhism\b/Vajrayana_Buddhism/g;
s/\bGlastonbury Festival\b/Glastonbury_Festival/g;
s/\bGalena Illinois\b/Galena_Illinois/g;
s/\bastroturf pitch\b/astroturf_pitch/g;
s/\bMount Barker\b/Mount_Barker/g;
s/\bMachine Readable\b/Machine_Readable/g;
s/\bDąbrowa Biskupia\b/Dąbrowa_Biskupia/g;
s/\bcentral Poland\b/central_Poland/g;
s/\bSmall Craft\b/Small_Craft/g;
s/\bYoo Jae-suk\b/Yoo_Jae-suk/g;
s/\bParadise Garage\b/Paradise_Garage/g;
s/\btwo towns\b/two_towns/g;
s/\blaser diodes\b/laser_diodes/g;
s/\bThe release of\b/The_release_of/g;
s/\bKrisztián Sárneczky\b/Krisztián_Sárneczky/g;
s/\bHrvatske ceste\b/Hrvatske_ceste/g;
s/\bclassify it as\b/classify_it_as/g;
s/\bAncrene Wisse\b/Ancrene_Wisse/g;
s/\bet de sculpture\b/et_de_sculpture/g;
s/\bis a 1978\b/is_a_1978/g;
s/\bevaluated as\b/evaluated_as/g;
s/\bPharmaceutical Benefits\b/Pharmaceutical_Benefits/g;
s/\ba massacre of\b/a_massacre_of/g;
s/\bSpecial Areas\b/Special_Areas/g;
s/\bGaozong s\b/Gaozong_s/g;
s/\bburden on\b/burden_on/g;
s/\binstructions are\b/instructions_are/g;
s/\bLong Depression\b/Long_Depression/g;
s/\bthe Dniester\b/the_Dniester/g;
s/\bhighly symbolic\b/highly_symbolic/g;
s/\bRassemblement Démocratique\b/Rassemblement_Démocratique/g;
s/\ba three-piece\b/a_three-piece/g;
s/\bUnborn Child\b/Unborn_Child/g;
s/\btheir ninth\b/their_ninth/g;
s/\bDash 7\b/Dash_7/g;
s/\bFalaise Gap\b/Falaise_Gap/g;
s/\blocal traffic\b/local_traffic/g;
s/\bIn 1739\b/In_1739/g;
s/\ban action for\b/an_action_for/g;
s/\bvocal trio\b/vocal_trio/g;
s/\bcult classics\b/cult_classics/g;
s/\bJolly Boys\b/Jolly_Boys/g;
s/\bIraqi officials\b/Iraqi_officials/g;
s/\bNavigation Company\b/Navigation_Company/g;
s/\bLes Contes\b/Les_Contes/g;
s/\ban Italian\b/an_Italian/g;
s/\btetrastyle portico\b/tetrastyle_portico/g;
s/\bMink Stole\b/Mink_Stole/g;
s/\bParañaque City\b/Parañaque_City/g;
s/\bneutrophil elastase\b/neutrophil_elastase/g;
s/\bat Bangalore\b/at_Bangalore/g;
s/\bDebby Boone\b/Debby_Boone/g;
s/\bFra Angelico\b/Fra_Angelico/g;
s/\bAlicante Spain\b/Alicante_Spain/g;
s/\bwas opened\b/was_opened/g;
s/\bMike Holmgren\b/Mike_Holmgren/g;
s/\bNationalist Movement\b/Nationalist_Movement/g;
s/\bwicker baskets\b/wicker_baskets/g;
s/\b59 88\b/59_88/g;
s/\bChief Government Whip\b/Chief_Government_Whip/g;
s/\bVowel Shift\b/Vowel_Shift/g;
s/\bnearly completed\b/nearly_completed/g;
s/\bbattles including\b/battles_including/g;
s/\bwelded steel\b/welded_steel/g;
s/\bsports society\b/sports_society/g;
s/\bcontributed substantially to\b/contributed_substantially_to/g;
s/\bsecondary alcohols\b/secondary_alcohols/g;
s/\bMegaptera novaeangliae\b/Megaptera_novaeangliae/g;
s/\bhis short life\b/his_short_life/g;
s/\bin the Nord\b/in_the_Nord/g;
s/\bSufian District Shabestar\b/Sufian_District_Shabestar/g;
s/\bnothing new\b/nothing_new/g;
s/\bthe banner of\b/the_banner_of/g;
s/\bRed Planet\b/Red_Planet/g;
s/\bSomaly Mam\b/Somaly_Mam/g;
s/\bBy 1989\b/By_1989/g;
s/\bMikhail Saakashvili\b/Mikhail_Saakashvili/g;
s/\bGraduate School\b/Graduate_School/g;
s/\bAll-Academic Team\b/All-Academic_Team/g;
s/\brelative importance\b/relative_importance/g;
s/\bShe authored\b/She_authored/g;
s/\ban intermediary\b/an_intermediary/g;
s/\bSV Elversberg\b/SV_Elversberg/g;
s/\bimitations of\b/imitations_of/g;
s/\bStephen Baxter\b/Stephen_Baxter/g;
s/\bpeppercorn rent\b/peppercorn_rent/g;
s/\bvertical shaft\b/vertical_shaft/g;
s/\bwhich dominates\b/which_dominates/g;
s/\btook a turn\b/took_a_turn/g;
s/\bNuremberg trials\b/Nuremberg_trials/g;
s/\bAmélie Mauresmo\b/Amélie_Mauresmo/g;
s/\bG Karachkina\b/G_Karachkina/g;
s/\bthe bridge s\b/the_bridge_s/g;
s/\bmoved elsewhere\b/moved_elsewhere/g;
s/\bin this war\b/in_this_war/g;
s/\bFrancesca Annis\b/Francesca_Annis/g;
s/\bLe Verrier\b/Le_Verrier/g;
s/\bwas overhauled\b/was_overhauled/g;
s/\bwould start\b/would_start/g;
s/\bthe Rock Island\b/the_Rock_Island/g;
s/\ban affordable\b/an_affordable/g;
s/\bbreakfast and lunch\b/breakfast_and_lunch/g;
s/\ba two hour\b/a_two_hour/g;
s/\bGröbner bases\b/Gröbner_bases/g;
s/\bDave Simpson\b/Dave_Simpson/g;
s/\bThutmose IV\b/Thutmose_IV/g;
s/\bDemocratic parties\b/Democratic_parties/g;
s/\bBurning Pestle\b/Burning_Pestle/g;
s/\bblack tie\b/black_tie/g;
s/\bMiss Texas\b/Miss_Texas/g;
s/\bLandscape Architecture\b/Landscape_Architecture/g;
s/\bTennis Club\b/Tennis_Club/g;
s/\bQuintin Hogg\b/Quintin_Hogg/g;
s/\bNorthern Bullants\b/Northern_Bullants/g;
s/\bleading run-scorer\b/leading_run-scorer/g;
s/\bpoliticization of\b/politicization_of/g;
s/\bValmiki Ramayana\b/Valmiki_Ramayana/g;
s/\bFrederick Law Olmsted\b/Frederick_Law_Olmsted/g;
s/\bDavid M\b/David_M/g;
s/\bmillion facility\b/million_facility/g;
s/\bDungeons and Dragons\b/Dungeons_and_Dragons/g;
s/\bprofessional careers\b/professional_careers/g;
s/\bভল ি উম\b/ভল_ি_উম/g;
s/\bRafik Hariri\b/Rafik_Hariri/g;
s/\bgeographic location\b/geographic_location/g;
s/\bJan Hus\b/Jan_Hus/g;
s/\bFrom 1909\b/From_1909/g;
s/\bDick Vermeil\b/Dick_Vermeil/g;
s/\bHoward Beach\b/Howard_Beach/g;
s/\binvaded Egypt\b/invaded_Egypt/g;
s/\bCaptain EO\b/Captain_EO/g;
s/\bthe young artist\b/the_young_artist/g;
s/\bYour Daddy\b/Your_Daddy/g;
s/\battract females\b/attract_females/g;
s/\b3600 m\b/3600_m/g;
s/\band hand grenades\b/and_hand_grenades/g;
s/\bKoo Wee Rup\b/Koo_Wee_Rup/g;
s/\bMoringa oleifera\b/Moringa_oleifera/g;
s/\bwritten and storyboarded\b/written_and_storyboarded/g;
s/\bCarbon nanotubes\b/Carbon_nanotubes/g;
s/\brepresented Italy\b/represented_Italy/g;
s/\bmethods are\b/methods_are/g;
s/\bRichard Dreyfuss\b/Richard_Dreyfuss/g;
s/\bSterling Cooper\b/Sterling_Cooper/g;
s/\bcolors are\b/colors_are/g;
s/\bTownship is one\b/Township_is_one/g;
s/\bthe Kansas River\b/the_Kansas_River/g;
s/\bdescribed to be\b/described_to_be/g;
s/\bchooses one\b/chooses_one/g;
s/\b38 sqmi\b/38_sqmi/g;
s/\ba European species\b/a_European_species/g;
s/\bFärjestads BK\b/Färjestads_BK/g;
s/\badrenaline rush\b/adrenaline_rush/g;
s/\bshed light on\b/shed_light_on/g;
s/\badvertising company\b/advertising_company/g;
s/\bSweeney s\b/Sweeney_s/g;
s/\bExpeditionary Force\b/Expeditionary_Force/g;
s/\bChris Willman\b/Chris_Willman/g;
s/\bco-operates with\b/co-operates_with/g;
s/\ba bit\b/a_bit/g;
s/\bhas been repeatedly\b/has_been_repeatedly/g;
s/\bWrestle Kingdom\b/Wrestle_Kingdom/g;
s/\bMegan Mullally\b/Megan_Mullally/g;
s/\bEddie Redmayne\b/Eddie_Redmayne/g;
s/\bdesigned by\b/designed_by/g;
s/\bbeta decay\b/beta_decay/g;
s/\bMichelle Visage\b/Michelle_Visage/g;
s/\bAnoop Menon\b/Anoop_Menon/g;
s/\bHenry A Wise\b/Henry_A_Wise/g;
s/\bresponding to\b/responding_to/g;
s/\bsuffices to\b/suffices_to/g;
s/\bmalignant melanoma\b/malignant_melanoma/g;
s/\bchancel with\b/chancel_with/g;
s/\bLeinster Senior\b/Leinster_Senior/g;
s/\bAsbury Jukes\b/Asbury_Jukes/g;
s/\bArtemis Entreri\b/Artemis_Entreri/g;
s/\bIn 1898\b/In_1898/g;
s/\borbitofrontal cortex\b/orbitofrontal_cortex/g;
s/\bsquare root\b/square_root/g;
s/\bKennet and Avon\b/Kennet_and_Avon/g;
s/\bScott s\b/Scott_s/g;
s/\bα helices\b/α_helices/g;
s/\bGower Champion\b/Gower_Champion/g;
s/\bwary of\b/wary_of/g;
s/\bspokesman for\b/spokesman_for/g;
s/\bISO 26262\b/ISO_26262/g;
s/\bduring peak hours\b/during_peak_hours/g;
s/\bin several fields\b/in_several_fields/g;
s/\bcould resume\b/could_resume/g;
s/\bTwin Otters\b/Twin_Otters/g;
s/\bSan Justo\b/San_Justo/g;
s/\bpoet translator\b/poet_translator/g;
s/\bSalvadore Cammarano\b/Salvadore_Cammarano/g;
s/\bhigh casualties\b/high_casualties/g;
s/\bAir Assault\b/Air_Assault/g;
s/\bProfessor of\b/Professor_of/g;
s/\bBobby Tench\b/Bobby_Tench/g;
s/\bbut never\b/but_never/g;
s/\bat this level\b/at_this_level/g;
s/\bTamil Nadu\b/Tamil_Nadu/g;
s/\bknown to infect\b/known_to_infect/g;
s/\ba mountain of\b/a_mountain_of/g;
s/\bDamien Dempsey\b/Damien_Dempsey/g;
s/\bin Dunedin\b/in_Dunedin/g;
s/\bAncient Greek\b/Ancient_Greek/g;
s/\bProfessor John\b/Professor_John/g;
s/\bkabuki actors\b/kabuki_actors/g;
s/\bHürrem Sultan\b/Hürrem_Sultan/g;
s/\bin the category\b/in_the_category/g;
s/\bThe first election\b/The_first_election/g;
s/\bTu Bishvat\b/Tu_Bishvat/g;
s/\bde Uruguay\b/de_Uruguay/g;
s/\bNever Knew\b/Never_Knew/g;
s/\bsalad bar\b/salad_bar/g;
s/\bSince May\b/Since_May/g;
s/\bForbes magazine\b/Forbes_magazine/g;
s/\ba backbencher\b/a_backbencher/g;
s/\b20 mph\b/20_mph/g;
s/\bparallel bars\b/parallel_bars/g;
s/\bwould offend\b/would_offend/g;
s/\bfantasizing about\b/fantasizing_about/g;
s/\bharmed by\b/harmed_by/g;
s/\bcommensurate with\b/commensurate_with/g;
s/\bNobel prize-winning\b/Nobel_prize-winning/g;
s/\bRiverside California\b/Riverside_California/g;
s/\bTeófilo Braga\b/Teófilo_Braga/g;
s/\bDramatists Guild\b/Dramatists_Guild/g;
s/\badvocated that\b/advocated_that/g;
s/\bி ம\b/ி_ம/g;
s/\bOrontes River\b/Orontes_River/g;
s/\bSarah Miles\b/Sarah_Miles/g;
s/\bYoungstown Ohio\b/Youngstown_Ohio/g;
s/\bRowan Williams\b/Rowan_Williams/g;
s/\brepresentative of\b/representative_of/g;
s/\bFas Alzamora\b/Fas_Alzamora/g;
s/\bClwydian Range\b/Clwydian_Range/g;
s/\bBrad Ausmus\b/Brad_Ausmus/g;
s/\biridescent blue\b/iridescent_blue/g;
s/\bsummer school\b/summer_school/g;
s/\bculled from\b/culled_from/g;
s/\bSão Toméan\b/São_Toméan/g;
s/\ba twin-engined\b/a_twin-engined/g;
s/\bHenrik Wergeland\b/Henrik_Wergeland/g;
s/\bMing court\b/Ming_court/g;
s/\bFrederick Gibberd\b/Frederick_Gibberd/g;
s/\bShortly after\b/Shortly_after/g;
s/\bWorcestershire Canal\b/Worcestershire_Canal/g;
s/\bSoulcalibur IV\b/Soulcalibur_IV/g;
s/\bAnd you\b/And_you/g;
s/\bBy 1850\b/By_1850/g;
s/\ban end-to-end\b/an_end-to-end/g;
s/\bgeological strata\b/geological_strata/g;
s/\bis taken\b/is_taken/g;
s/\bpurchased a house\b/purchased_a_house/g;
s/\bDr med\b/Dr_med/g;
s/\bDonald Rumsfeld\b/Donald_Rumsfeld/g;
s/\bVerwaltungsgemeinschaft Administrative\b/Verwaltungsgemeinschaft_Administrative/g;
s/\bToledo Walleye\b/Toledo_Walleye/g;
s/\bMel Lastman\b/Mel_Lastman/g;
s/\bbut died\b/but_died/g;
s/\bGuitar Slim\b/Guitar_Slim/g;
s/\bKryvyi Rih\b/Kryvyi_Rih/g;
s/\bAsian records were\b/Asian_records_were/g;
s/\bmusic duo\b/music_duo/g;
s/\bsurvey work\b/survey_work/g;
s/\ba death penalty\b/a_death_penalty/g;
s/\bIn 1729\b/In_1729/g;
s/\bpublic – private\b/public_–_private/g;
s/\bAiredale Terrier\b/Airedale_Terrier/g;
s/\bflowing waters\b/flowing_waters/g;
s/\bethical conduct\b/ethical_conduct/g;
s/\bhot and often\b/hot_and_often/g;
s/\bCounty East Azerbaijan\b/County_East_Azerbaijan/g;
s/\bDerek Sherinian\b/Derek_Sherinian/g;
s/\bLéon Theremin\b/Léon_Theremin/g;
s/\bplays guitar\b/plays_guitar/g;
s/\bknown popularly as\b/known_popularly_as/g;
s/\bSangam period\b/Sangam_period/g;
s/\bPrimary Care\b/Primary_Care/g;
s/\bMartin Rushent\b/Martin_Rushent/g;
s/\bregulatory issues\b/regulatory_issues/g;
s/\bat various\b/at_various/g;
s/\bOperation Barbarossa\b/Operation_Barbarossa/g;
s/\bBouncing Souls\b/Bouncing_Souls/g;
s/\ba helicopter\b/a_helicopter/g;
s/\bcardiac surgery\b/cardiac_surgery/g;
s/\bgreatly simplifies\b/greatly_simplifies/g;
s/\bthe Decatur Staleys\b/the_Decatur_Staleys/g;
s/\bpro bono\b/pro_bono/g;
s/\bMITOS Novocherkassk\b/MITOS_Novocherkassk/g;
s/\bSteam Packet\b/Steam_Packet/g;
s/\bLand Grant\b/Land_Grant/g;
s/\bBhopal Habibganj\b/Bhopal_Habibganj/g;
s/\battracted over\b/attracted_over/g;
s/\bSingle Action\b/Single_Action/g;
s/\bGifted Talented\b/Gifted_Talented/g;
s/\bPruszcz Gdański\b/Pruszcz_Gdański/g;
s/\bCapitoline Hill\b/Capitoline_Hill/g;
s/\bTorneo Cibernetico\b/Torneo_Cibernetico/g;
s/\bwould ordinarily\b/would_ordinarily/g;
s/\bKoine Greek\b/Koine_Greek/g;
s/\bnaval gunfire\b/naval_gunfire/g;
s/\bArjen Robben\b/Arjen_Robben/g;
s/\bin Katowice\b/in_Katowice/g;
s/\bdomestic helpers\b/domestic_helpers/g;
s/\bKe Phool\b/Ke_Phool/g;
s/\bOphichthidae worm snake\b/Ophichthidae_worm_snake/g;
s/\bcorpore sano\b/corpore_sano/g;
s/\bJacques Tati\b/Jacques_Tati/g;
s/\bAnimal Rescue\b/Animal_Rescue/g;
s/\bdistinct entities\b/distinct_entities/g;
s/\bcoconut palms\b/coconut_palms/g;
s/\bMille Lacs\b/Mille_Lacs/g;
s/\bSt Moritz\b/St_Moritz/g;
s/\bdorsal fins\b/dorsal_fins/g;
s/\btwo villages\b/two_villages/g;
s/\barea code\b/area_code/g;
s/\btool and die\b/tool_and_die/g;
s/\bThutmose III\b/Thutmose_III/g;
s/\b2400 m\b/2400_m/g;
s/\bArcelor Mittal\b/Arcelor_Mittal/g;
s/\ba dead person\b/a_dead_person/g;
s/\bသ ူ\b/သ_ူ/g;
s/\bvanishing point\b/vanishing_point/g;
s/\bLászló Rajk\b/László_Rajk/g;
s/\bSpVgg Fürth\b/SpVgg_Fürth/g;
s/\bThousand Faces\b/Thousand_Faces/g;
s/\bပည ာ\b/ပည_ာ/g;
s/\bMonday morning\b/Monday_morning/g;
s/\bclose season\b/close_season/g;
s/\bCaravan Park\b/Caravan_Park/g;
s/\bnursing care\b/nursing_care/g;
s/\ban admixture\b/an_admixture/g;
s/\bbrings her to\b/brings_her_to/g;
s/\bIn 1932\b/In_1932/g;
s/\bVolume 5\b/Volume_5/g;
s/\bexchanges between\b/exchanges_between/g;
s/\bPhil Collen\b/Phil_Collen/g;
s/\bhigh ratings\b/high_ratings/g;
s/\bonly open to\b/only_open_to/g;
s/\bRed Electoral Alliance\b/Red_Electoral_Alliance/g;
s/\bIn 1960\b/In_1960/g;
s/\bRicky Butcher\b/Ricky_Butcher/g;
s/\b2013-14 season\b/2013-14_season/g;
s/\bFigure 2\b/Figure_2/g;
s/\bannexed to\b/annexed_to/g;
s/\bImperial Japan\b/Imperial_Japan/g;
s/\bDarley Stud\b/Darley_Stud/g;
s/\bSlavko Kvaternik\b/Slavko_Kvaternik/g;
s/\bcoupling rods\b/coupling_rods/g;
s/\bDoug Pinnick\b/Doug_Pinnick/g;
s/\bSteven Klein\b/Steven_Klein/g;
s/\bBinaca Geetmala\b/Binaca_Geetmala/g;
s/\bWladimir Klitschko\b/Wladimir_Klitschko/g;
s/\bher then-husband\b/her_then-husband/g;
s/\bhistone acetyltransferase\b/histone_acetyltransferase/g;
s/\binsertions and deletions\b/insertions_and_deletions/g;
s/\bศ ู นย\b/ศ_ู_นย/g;
s/\bLen Cariou\b/Len_Cariou/g;
s/\bRecovery Program\b/Recovery_Program/g;
s/\bmilitant groups\b/militant_groups/g;
s/\bReal Maryland Monarchs\b/Real_Maryland_Monarchs/g;
s/\bAdam Dutkiewicz\b/Adam_Dutkiewicz/g;
s/\bmeters long\b/meters_long/g;
s/\bKen Doherty\b/Ken_Doherty/g;
s/\bSammi Cheng\b/Sammi_Cheng/g;
s/\bValentina Matviyenko\b/Valentina_Matviyenko/g;
s/\bWestminster Assembly\b/Westminster_Assembly/g;
s/\bFicus religiosa\b/Ficus_religiosa/g;
s/\bmetallic tints\b/metallic_tints/g;
s/\bhigh importance\b/high_importance/g;
s/\bDandie Dinmont\b/Dandie_Dinmont/g;
s/\bmesic forests\b/mesic_forests/g;
s/\bThese locomotives\b/These_locomotives/g;
s/\bBy studying\b/By_studying/g;
s/\bstay together\b/stay_together/g;
s/\bpornographic content\b/pornographic_content/g;
s/\bhappy couple\b/happy_couple/g;
s/\bat about 2\b/at_about_2/g;
s/\bin the Orne\b/in_the_Orne/g;
s/\bpractical applications of\b/practical_applications_of/g;
s/\bcoordinating committee\b/coordinating_committee/g;
s/\bboxing referee\b/boxing_referee/g;
s/\bfreshwater lake\b/freshwater_lake/g;
s/\bBuffy Sainte-Marie\b/Buffy_Sainte-Marie/g;
s/\bScritti Politti\b/Scritti_Politti/g;
s/\bvoice communications\b/voice_communications/g;
s/\barchaeological work\b/archaeological_work/g;
s/\bin Wilmington\b/in_Wilmington/g;
s/\bzinc chloride\b/zinc_chloride/g;
s/\bSluggy Freelance\b/Sluggy_Freelance/g;
s/\bֹ ה\b/ֹ_ה/g;
s/\bHindu deities\b/Hindu_deities/g;
s/\bMircea Geoană\b/Mircea_Geoană/g;
s/\bEstoril Praia\b/Estoril_Praia/g;
s/\bEl Brazo\b/El_Brazo/g;
s/\bOtaqvar District Langarud\b/Otaqvar_District_Langarud/g;
s/\bAnnabella Sciorra\b/Annabella_Sciorra/g;
s/\bTim LaHaye\b/Tim_LaHaye/g;
s/\bCaptain James\b/Captain_James/g;
s/\bDaily Inquirer\b/Daily_Inquirer/g;
s/\bpelvic pain\b/pelvic_pain/g;
s/\b≠ 0\b/≠_0/g;
s/\bFrançois Bayrou\b/François_Bayrou/g;
s/\bcabaret artist\b/cabaret_artist/g;
s/\bKonstantin Nikolayevich\b/Konstantin_Nikolayevich/g;
s/\bFunding School\b/Funding_School/g;
s/\bthe destiny of\b/the_destiny_of/g;
s/\bsilky sifaka\b/silky_sifaka/g;
s/\bmemory bandwidth\b/memory_bandwidth/g;
s/\blower level\b/lower_level/g;
s/\bPine Brook\b/Pine_Brook/g;
s/\b18th hole\b/18th_hole/g;
s/\bthe first pitch\b/the_first_pitch/g;
s/\bpreventing her from\b/preventing_her_from/g;
s/\bnegative stereotypes\b/negative_stereotypes/g;
s/\bBif Naked\b/Bif_Naked/g;
s/\bHold It Against\b/Hold_It_Against/g;
s/\bBusiness Insider\b/Business_Insider/g;
s/\bhas now been\b/has_now_been/g;
s/\bOak Grove\b/Oak_Grove/g;
s/\bLivery Companies\b/Livery_Companies/g;
s/\bfirst conceived\b/first_conceived/g;
s/\bfinancial disaster\b/financial_disaster/g;
s/\bMira Mesa\b/Mira_Mesa/g;
s/\bmetric spaces\b/metric_spaces/g;
s/\btakes up\b/takes_up/g;
s/\bthe Medellín Cartel\b/the_Medellín_Cartel/g;
s/\bhexagonal crystal\b/hexagonal_crystal/g;
s/\bstraight-line winds\b/straight-line_winds/g;
s/\bnegotiation process\b/negotiation_process/g;
s/\band features programing\b/and_features_programing/g;
s/\bAnwar Maqsood\b/Anwar_Maqsood/g;
s/\bDetroit Michigan\b/Detroit_Michigan/g;
s/\bcrushed stone\b/crushed_stone/g;
s/\bbacklog of\b/backlog_of/g;
s/\bthe Opposition\b/the_Opposition/g;
s/\bcell biology\b/cell_biology/g;
s/\bLucien Bouchard\b/Lucien_Bouchard/g;
s/\bIn 1648\b/In_1648/g;
s/\bbus stop\b/bus_stop/g;
s/\blocal councillor\b/local_councillor/g;
s/\bHe remained\b/He_remained/g;
s/\bAnton Reicha\b/Anton_Reicha/g;
s/\belectric instruments\b/electric_instruments/g;
s/\bdefined to be\b/defined_to_be/g;
s/\bpopulation increase\b/population_increase/g;
s/\bProgressive Architecture\b/Progressive_Architecture/g;
s/\bNorthumberland and Durham\b/Northumberland_and_Durham/g;
s/\bRohit Ramachandran\b/Rohit_Ramachandran/g;
s/\bNSCAA adidas\b/NSCAA_adidas/g;
s/\bAllied war effort\b/Allied_war_effort/g;
s/\bnon-profit group\b/non-profit_group/g;
s/\brequested by\b/requested_by/g;
s/\bMāori culture\b/Māori_culture/g;
s/\bthe Future\b/the_Future/g;
s/\bin 1694\b/in_1694/g;
s/\bDelmarva Shorebirds\b/Delmarva_Shorebirds/g;
s/\bTai Tokerau\b/Tai_Tokerau/g;
s/\bsatellite technology\b/satellite_technology/g;
s/\bHod HaSharon\b/Hod_HaSharon/g;
s/\bbridge builder\b/bridge_builder/g;
s/\bKenneth Slessor\b/Kenneth_Slessor/g;
s/\btarot card\b/tarot_card/g;
s/\bart and culture\b/art_and_culture/g;
s/\bcomply with\b/comply_with/g;
s/\bconstruction worker\b/construction_worker/g;
s/\band Police Leader\b/and_Police_Leader/g;
s/\bIn 1857\b/In_1857/g;
s/\bHenri Pescarolo\b/Henri_Pescarolo/g;
s/\bmind-altering drugs\b/mind-altering_drugs/g;
s/\bfont-size 85\b/font-size_85/g;
s/\bwithout adequate\b/without_adequate/g;
s/\bcontributing author to\b/contributing_author_to/g;
s/\bAir Chief Marshal\b/Air_Chief_Marshal/g;
s/\bGovernors Association\b/Governors_Association/g;
s/\bPolitical Commissar\b/Political_Commissar/g;
s/\banalog channel\b/analog_channel/g;
s/\bKuk Sool\b/Kuk_Sool/g;
s/\bMaster Mason\b/Master_Mason/g;
s/\bCopper Cliff\b/Copper_Cliff/g;
s/\bthe Ashanti\b/the_Ashanti/g;
s/\ba kiss\b/a_kiss/g;
s/\bappeals to\b/appeals_to/g;
s/\bLucchese crime\b/Lucchese_crime/g;
s/\bthe assistant manager\b/the_assistant_manager/g;
s/\bN astirh\b/N_astirh/g;
s/\bwas sighted\b/was_sighted/g;
s/\bֵ ל\b/ֵ_ל/g;
s/\bcapacity factor\b/capacity_factor/g;
s/\bMilitary Command\b/Military_Command/g;
s/\bsacrificed to\b/sacrificed_to/g;
s/\bDaniela Hantuchová\b/Daniela_Hantuchová/g;
s/\bsporting career\b/sporting_career/g;
s/\bRecipients AKCR\b/Recipients_AKCR/g;
s/\bDebre Tabor\b/Debre_Tabor/g;
s/\bsettle voluntarily\b/settle_voluntarily/g;
s/\bdiv Scale\b/div_Scale/g;
s/\bantisubmarine exercises\b/antisubmarine_exercises/g;
s/\bNavy Fleet\b/Navy_Fleet/g;
s/\b102 JAMZ\b/102_JAMZ/g;
s/\bHold on Me\b/Hold_on_Me/g;
s/\bpoints were scored\b/points_were_scored/g;
s/\bartists and groups\b/artists_and_groups/g;
s/\bhas been under\b/has_been_under/g;
s/\bat all costs\b/at_all_costs/g;
s/\ba ship s\b/a_ship_s/g;
s/\bTriStar Pictures\b/TriStar_Pictures/g;
s/\ba clear day\b/a_clear_day/g;
s/\bmay appoint\b/may_appoint/g;
s/\bpattern of\b/pattern_of/g;
s/\bher early childhood\b/her_early_childhood/g;
s/\bred and white\b/red_and_white/g;
s/\b· edit\b/·_edit/g;
s/\bher young\b/her_young/g;
s/\bprofessional debut for\b/professional_debut_for/g;
s/\bMinister-President of\b/Minister-President_of/g;
s/\bLitt D\b/Litt_D/g;
s/\bdrained soils\b/drained_soils/g;
s/\bJustin Allgaier\b/Justin_Allgaier/g;
s/\bLectures on\b/Lectures_on/g;
s/\btablet PCs\b/tablet_PCs/g;
s/\bMacchi M\b/Macchi_M/g;
s/\ban acceleration\b/an_acceleration/g;
s/\bHimachal Pradesh\b/Himachal_Pradesh/g;
s/\b9 hours\b/9_hours/g;
s/\bsaline soils\b/saline_soils/g;
s/\bin orbit around\b/in_orbit_around/g;
s/\bCritically acclaimed\b/Critically_acclaimed/g;
s/\bErta Ale\b/Erta_Ale/g;
s/\bbudget shortfall\b/budget_shortfall/g;
s/\bCarolingian dynasty\b/Carolingian_dynasty/g;
s/\b10th round\b/10th_round/g;
s/\bQueen Regent\b/Queen_Regent/g;
s/\bTanzania Togo\b/Tanzania_Togo/g;
s/\bplaying football with\b/playing_football_with/g;
s/\brevolving around\b/revolving_around/g;
s/\bsedimentary strata\b/sedimentary_strata/g;
s/\bRamon Fernandez\b/Ramon_Fernandez/g;
s/\bdo whatever\b/do_whatever/g;
s/\b75 0\b/75_0/g;
s/\bspherical symmetry\b/spherical_symmetry/g;
s/\bTV roles\b/TV_roles/g;
s/\bDowney Jr\b/Downey_Jr/g;
s/\bextra-marital affairs\b/extra-marital_affairs/g;
s/\bAll Day\b/All_Day/g;
s/\babdominal aorta\b/abdominal_aorta/g;
s/\bis a 1965\b/is_a_1965/g;
s/\bMount Tamalpais\b/Mount_Tamalpais/g;
s/\bQueensboro Bridge\b/Queensboro_Bridge/g;
s/\bhis prison sentence\b/his_prison_sentence/g;
s/\bMagda Olivero\b/Magda_Olivero/g;
s/\bgiallo film\b/giallo_film/g;
s/\bmany cases\b/many_cases/g;
s/\brecording songs\b/recording_songs/g;
s/\brelief panels\b/relief_panels/g;
s/\brefresher course\b/refresher_course/g;
s/\bAll-Star Futures Game\b/All-Star_Futures_Game/g;
s/\badrenal gland\b/adrenal_gland/g;
s/\bthe 107th\b/the_107th/g;
s/\bThe tour\b/The_tour/g;
s/\ban 11-point\b/an_11-point/g;
s/\bNational Committeewoman\b/National_Committeewoman/g;
s/\bfinancial distress\b/financial_distress/g;
s/\bਾ ਲ\b/ਾ_ਲ/g;
s/\bTokyo Metropolitan Government\b/Tokyo_Metropolitan_Government/g;
s/\bfocuses heavily on\b/focuses_heavily_on/g;
s/\bBa Cụt\b/Ba_Cụt/g;
s/\bmore powerful\b/more_powerful/g;
s/\bThe Classroom for\b/The_Classroom_for/g;
s/\bToby Whithouse\b/Toby_Whithouse/g;
s/\bZürcher Oberland\b/Zürcher_Oberland/g;
s/\bAnnual General Meeting\b/Annual_General_Meeting/g;
s/\bUmeå Sweden\b/Umeå_Sweden/g;
s/\bBlue Note label\b/Blue_Note_label/g;
s/\bComparative Anatomy\b/Comparative_Anatomy/g;
s/\bKorać Cup\b/Korać_Cup/g;
s/\bdays until\b/days_until/g;
s/\bhydrogen sulphide\b/hydrogen_sulphide/g;
s/\bMadras India\b/Madras_India/g;
s/\bError rider\b/Error_rider/g;
s/\bties to\b/ties_to/g;
s/\bwas renumbered\b/was_renumbered/g;
s/\bTuesdays and Fridays\b/Tuesdays_and_Fridays/g;
s/\bChoctaw Nation\b/Choctaw_Nation/g;
s/\bSociété Française\b/Société_Française/g;
s/\bMontgomery Blair\b/Montgomery_Blair/g;
s/\bpale golden\b/pale_golden/g;
s/\bis a Ugandan\b/is_a_Ugandan/g;
s/\ban adept\b/an_adept/g;
s/\bKatholieke Universiteit\b/Katholieke_Universiteit/g;
s/\bBritish explorer\b/British_explorer/g;
s/\bprehistoric period\b/prehistoric_period/g;
s/\bjazz saxophonist\b/jazz_saxophonist/g;
s/\btwelve feet\b/twelve_feet/g;
s/\bre-branded as\b/re-branded_as/g;
s/\bgender discrimination\b/gender_discrimination/g;
s/\bchanged hands\b/changed_hands/g;
s/\bscreech owls\b/screech_owls/g;
s/\bAvram Iancu\b/Avram_Iancu/g;
s/\bcommunity-acquired pneumonia\b/community-acquired_pneumonia/g;
s/\btraveled to\b/traveled_to/g;
s/\bCounty Wisconsin\b/County_Wisconsin/g;
s/\bFrom that date\b/From_that_date/g;
s/\bBishop of\b/Bishop_of/g;
s/\bी ह\b/ी_ह/g;
s/\ba foreigner\b/a_foreigner/g;
s/\bSaif al-Islam\b/Saif_al-Islam/g;
s/\bLate Triassic\b/Late_Triassic/g;
s/\blaw and medicine\b/law_and_medicine/g;
s/\beventual champions\b/eventual_champions/g;
s/\btwo bays\b/two_bays/g;
s/\bKamieniec Ząbkowicki\b/Kamieniec_Ząbkowicki/g;
s/\b$50 billion\b/$50_billion/g;
s/\b175 m\b/175_m/g;
s/\bEmpress Theodora\b/Empress_Theodora/g;
s/\bnervous system\b/nervous_system/g;
s/\bvan Beuningen\b/van_Beuningen/g;
